<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Tarazpad.Desktop</AssemblyName>
    <RootNamespace>Tarazpad.Desktop</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>2.0.0</Version>
    <FileVersion>2.0.0.0</FileVersion>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <InvariantGlobalization>false</InvariantGlobalization>
    <BaseOutputPath>../../../.artifacts/desktop/bin/</BaseOutputPath>
    <BaseIntermediateOutputPath>../../../.artifacts/desktop/obj/</BaseIntermediateOutputPath>
  </PropertyGroup>
</Project>
