(()=>{
 const faNum=new Intl.NumberFormat('fa-IR');
 const stFa={NEW:'جدید',ACTIVE:'فعال',PAUSED:'متوقف',WON:'موفق',LOST:'از دست‌رفته',DO_NOT_CONTACT:'عدم تماس',OPEN:'باز',IN_PROGRESS:'در حال انجام',COMPLETED:'انجام‌شده',CANCELLED:'لغو شده',LOW:'کم',NORMAL:'عادی',HIGH:'بالا',CRITICAL:'بحرانی'};
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const faDate=v=>{if(!v)return '—';const d=new Date(String(v).replace(' ','T'));return Number.isNaN(d.getTime())?esc(v):new Intl.DateTimeFormat('fa-IR-u-ca-persian',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(d)};
 const api=async(path,o={})=>{const token=localStorage.getItem('tarazpad_token');const h={'Content-Type':'application/json',...(o.headers||{})};if(token)h.Authorization=`Bearer ${token}`;const r=await fetch(path,{...o,headers:h});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error([b.error,...(Array.isArray(b.details)?b.details:[])].filter(Boolean).join(' — ')||'خطای سرور');return b};
 let users=[],customers=[],followups=[],imports=[],currentTab='customers';
 const page=()=>document.getElementById('customerClubPage');
 const toast=(m,bad=false)=>{const t=document.getElementById('toast');if(!t)return alert(m);t.textContent=m;t.className='toast show'+(bad?' error':'');setTimeout(()=>t.classList.remove('show'),3500)};
 const ownerOptions=(selected='')=>users.map(u=>`<option value="${u.id}" ${String(selected)===String(u.id)?'selected':''}>${esc(u.full_name)} — ${esc(u.email)}</option>`).join('');
 function inject(){
   if(document.querySelector('[data-module="customerclub"]'))return;
   const groups=[...document.querySelectorAll('.menu-group')];const target=groups.find(g=>g.querySelector('.menu-group-title')?.textContent.includes('فروش و ارتباط'))||groups[0];if(!target)return setTimeout(inject,300);
   const b=document.createElement('button');b.className='menu-item';b.dataset.module='customerclub';b.innerHTML='<span class="menu-icon">♧</span><span class="menu-label">باشگاه مشتریان و پیگیری</span>';
   b.onclick=e=>{e.preventDefault();e.stopPropagation();openPage()};target.appendChild(b);
   document.addEventListener('click',e=>{const m=e.target.closest?.('.menu-item');if(m&&m.dataset.module!=='customerclub')hidePage()},true);
 }
 function hidePage(){page()?.classList.remove('active')}
 async function openPage(){
   document.getElementById('dashboardPage')?.classList.remove('active');document.getElementById('modulePage')?.classList.remove('active');page()?.classList.add('active');
   document.querySelectorAll('.menu-item').forEach(x=>x.classList.toggle('active',x.dataset.module==='customerclub'));
   const pt=document.getElementById('pageTitle');if(pt)pt.textContent='باشگاه مشتریان و پیگیری';const ps=document.getElementById('pageSubtitle');if(ps)ps.textContent='عملیات داخلی، تخصیص کارشناس، صف پیگیری و وفاداری';
   try{users=await api('/api/iran/customer-club/users');await Promise.all([loadDashboard(),loadTab(currentTab)])}catch(e){toast(e.message,true)}
 }
 async function loadDashboard(){const d=await api('/api/iran/customer-club/dashboard');const items=[['کل مشتریان',d.customers],['جدید',d.new_customers],['فعال',d.active_customers],['پیگیری معوق',d.overdue],['پیگیری امروز',d.due_today],['متوقف',d.paused_customers]];document.getElementById('ccKpis').innerHTML=items.map(x=>`<div class="cc-kpi"><small>${x[0]}</small><strong>${faNum.format(Number(x[1]||0))}</strong></div>`).join('');const owner=document.getElementById('ccOwner');if(owner){const old=owner.value;owner.innerHTML='<option value="">همه کارشناسان</option>'+ownerOptions(old);owner.value=old}}
 async function loadTab(tab){currentTab=tab;document.querySelectorAll('[data-cctab]').forEach(b=>b.classList.toggle('active',b.dataset.cctab===tab));document.getElementById('ccCustomerFilters').style.display=tab==='customers'?'flex':'none';document.getElementById('ccFollowupFilters').style.display=tab==='followups'?'flex':'none';if(tab==='customers')await loadCustomers();else if(tab==='followups')await loadFollowups();else await loadImports()}
 function qs(id){return document.getElementById(id)?.value||''}
 async function loadCustomers(){const p=new URLSearchParams();if(qs('ccSearch'))p.set('q',qs('ccSearch'));if(qs('ccStatus'))p.set('status',qs('ccStatus'));if(qs('ccDue'))p.set('due',qs('ccDue'));if(qs('ccOwner'))p.set('ownerUserId',qs('ccOwner'));customers=await api('/api/iran/customer-club/customers?'+p);const body=document.getElementById('ccBody');if(!customers.length){body.innerHTML='<div class="cc-empty">مشتری باشگاه با این فیلتر پیدا نشد.</div>';return}body.innerHTML=`<div class="cc-table-wrap"><table class="cc-table"><thead><tr><th>عضویت</th><th>مشتری</th><th>موبایل</th><th>کارشناس</th><th>وضعیت</th><th>اولویت</th><th>اقدام بعدی</th><th>آخرین نتیجه</th><th>امتیاز</th><th>عملیات</th></tr></thead><tbody>${customers.map((r,i)=>`<tr><td>${esc(r.member_no||'—')}</td><td><b>${esc(r.name)}</b><br><small>${esc(r.code||r.national_id||'')}</small></td><td>${esc(r.mobile||'—')}</td><td>${esc(r.owner_name)}</td><td><span class="cc-badge">${stFa[r.lifecycle_status]||esc(r.lifecycle_status)}</span></td><td>${stFa[r.priority]||esc(r.priority)}</td><td class="${r.next_action_at&&new Date(r.next_action_at)<new Date()?'cc-overdue':''}">${faDate(r.next_action_at)}<br><small>${esc(r.next_action_title||'')}</small></td><td>${esc(r.last_result||'—')}</td><td>${faNum.format(Number(r.points_balance||0))}</td><td><div class="cc-row-actions"><button data-cc-follow="${i}">پیگیری</button><button data-cc-assign="${i}">ارجاع/وضعیت</button></div></td></tr>`).join('')}</tbody></table></div>`;body.querySelectorAll('[data-cc-follow]').forEach(b=>b.onclick=()=>followupModal(customers[Number(b.dataset.ccFollow)]));body.querySelectorAll('[data-cc-assign]').forEach(b=>b.onclick=()=>assignmentModal(customers[Number(b.dataset.ccAssign)]))}
 async function loadFollowups(){const p=new URLSearchParams();if(qs('ccFollowDue'))p.set('due',qs('ccFollowDue'));if(qs('ccFollowStatus'))p.set('status',qs('ccFollowStatus'));if(qs('ccOwner'))p.set('ownerUserId',qs('ccOwner'));followups=await api('/api/iran/customer-club/followups?'+p);const body=document.getElementById('ccBody');if(!followups.length){body.innerHTML='<div class="cc-empty">پیگیری‌ای با این فیلتر وجود ندارد.</div>';return}body.innerHTML=`<div class="cc-table-wrap"><table class="cc-table"><thead><tr><th>زمان</th><th>مشتری</th><th>نوع</th><th>موضوع</th><th>کارشناس</th><th>وضعیت</th><th>نتیجه</th><th>عملیات</th></tr></thead><tbody>${followups.map((r,i)=>`<tr><td class="${r.scheduled_at&&new Date(r.scheduled_at)<new Date()&&!['COMPLETED','CANCELLED'].includes(r.status)?'cc-overdue':''}">${faDate(r.scheduled_at)}</td><td><b>${esc(r.customer)}</b><br><small>${esc(r.mobile||'')}</small></td><td>${esc(r.activity_type)}</td><td>${esc(r.subject)}</td><td>${esc(r.owner_name)}</td><td>${stFa[r.status]||esc(r.status)}</td><td>${esc(r.result||'—')}</td><td>${!['COMPLETED','CANCELLED'].includes(r.status)?`<button data-cc-complete="${i}">ثبت نتیجه</button>`:'—'}</td></tr>`).join('')}</tbody></table></div>`;body.querySelectorAll('[data-cc-complete]').forEach(b=>b.onclick=()=>completeModal(followups[Number(b.dataset.ccComplete)]))}
 async function loadImports(){imports=await api('/api/iran/customer-club/imports');const body=document.getElementById('ccBody');if(!imports.length){body.innerHTML='<div class="cc-empty">هنوز ورود گروهی انجام نشده است.</div>';return}body.innerHTML=`<div class="cc-table-wrap"><table class="cc-table"><thead><tr><th>تاریخ</th><th>فایل/منبع</th><th>کارشناس پیش‌فرض</th><th>کل</th><th>جدید</th><th>به‌روزرسانی</th><th>ردشده</th><th>وضعیت</th><th>خطاها</th></tr></thead><tbody>${imports.map(r=>`<tr><td>${faDate(r.created_at)}</td><td>${esc(r.source_name||r.default_source||'—')}</td><td>${esc(r.default_owner_name||'—')}</td><td>${faNum.format(r.total_rows||0)}</td><td>${faNum.format(r.inserted_rows||0)}</td><td>${faNum.format(r.updated_rows||0)}</td><td>${faNum.format(r.rejected_rows||0)}</td><td>${esc(r.status)}</td><td>${Number(r.rejected_rows)>0?`<button data-cc-errors="${r.id}">مشاهده</button>`:'—'}</td></tr>`).join('')}</tbody></table></div>`;body.querySelectorAll('[data-cc-errors]').forEach(b=>b.onclick=()=>showImportErrors(b.dataset.ccErrors))}
 function modal(title,html,onSubmit){const root=document.getElementById('ccModal');document.getElementById('ccModalTitle').textContent=title;const f=document.getElementById('ccModalForm');f.innerHTML=html+'<div class="cc-form-actions"><button type="button" data-cc-close>انصراف</button><button class="primary" type="submit">ثبت</button></div>';root.classList.remove('hidden');f.querySelector('[data-cc-close]').onclick=()=>root.classList.add('hidden');f.onsubmit=async e=>{e.preventDefault();try{await onSubmit(f);root.classList.add('hidden');toast('عملیات با موفقیت ثبت شد.');await Promise.all([loadDashboard(),loadTab(currentTab)])}catch(x){toast(x.message,true)}}}
 function addCustomerModal(){modal('ثبت مشتری باشگاه',`<label>نام مشتری<input name="name" required></label><label>نوع شخص<select name="partyType"><option value="NATURAL">حقیقی</option><option value="LEGAL">حقوقی</option></select></label><label>کد مشتری<input name="code"></label><label>کد/شناسه ملی<input name="nationalId"></label><label>موبایل<input name="mobile"></label><label>تلفن<input name="phone"></label><label>ایمیل<input name="email" type="email"></label><label>کارشناس<select name="ownerUserId">${ownerOptions()}</select></label><label>اولویت<select name="priority"><option value="NORMAL">عادی</option><option value="HIGH">بالا</option><option value="CRITICAL">بحرانی</option><option value="LOW">کم</option></select></label><label>منبع جذب<input name="source"></label><label>زمان پیگیری بعدی<input name="nextActionAt" type="datetime-local"></label><label>موضوع پیگیری<input name="nextActionTitle"></label><label class="wide">آدرس<textarea name="address"></textarea></label><label class="wide">توضیحات<textarea name="notes"></textarea></label>`,async f=>{const d=Object.fromEntries(new FormData(f));d.ownerUserId=Number(d.ownerUserId);await api('/api/iran/customer-club/customers',{method:'POST',body:JSON.stringify(d)})})}
 function assignmentModal(r){modal(`ارجاع و وضعیت — ${r.name}`,`<label>کارشناس<select name="ownerUserId">${ownerOptions(r.owner_user_id)}</select></label><label>وضعیت<select name="lifecycleStatus"><option value="NEW">جدید</option><option value="ACTIVE">فعال</option><option value="PAUSED">متوقف</option><option value="WON">موفق</option><option value="LOST">از دست‌رفته</option><option value="DO_NOT_CONTACT">عدم تماس</option></select></label><label>اولویت<select name="priority"><option value="NORMAL">عادی</option><option value="HIGH">بالا</option><option value="CRITICAL">بحرانی</option><option value="LOW">کم</option></select></label><label>پیگیری بعدی<input name="nextActionAt" type="datetime-local"></label><label class="wide">عنوان اقدام بعدی<input name="nextActionTitle" value="${esc(r.next_action_title||'')}"></label>`,async f=>{f.elements.lifecycleStatus.value=f.elements.lifecycleStatus.value||r.lifecycle_status;const d=Object.fromEntries(new FormData(f));d.ownerUserId=Number(d.ownerUserId);await api(`/api/iran/customer-club/customers/${r.party_id}/assignment`,{method:'PUT',body:JSON.stringify(d)})});setTimeout(()=>{const f=document.getElementById('ccModalForm');f.elements.lifecycleStatus.value=r.lifecycle_status;f.elements.priority.value=r.priority},0)}
 function followupModal(r){modal(`ایجاد پیگیری — ${r.name}`,`<label>نوع<select name="activityType"><option value="CALL">تماس</option><option value="MESSAGE">پیام</option><option value="VISIT">ویزیت</option><option value="MEETING">جلسه</option><option value="FOLLOW_UP">پیگیری</option><option value="TASK">کار</option></select></label><label>کارشناس<select name="ownerUserId">${ownerOptions(r.owner_user_id)}</select></label><label class="wide">موضوع<input name="subject" required></label><label>زمان انجام<input name="scheduledAt" type="datetime-local" required></label><label>عنوان اقدام بعدی<input name="nextActionTitle"></label><label class="wide">شرح<textarea name="description"></textarea></label>`,async f=>{const d=Object.fromEntries(new FormData(f));d.ownerUserId=Number(d.ownerUserId);await api(`/api/iran/customer-club/customers/${r.party_id}/followups`,{method:'POST',body:JSON.stringify(d)})})}
 function completeModal(r){modal(`ثبت نتیجه — ${r.customer}`,`<label class="wide">نتیجه پیگیری<textarea name="result" required></textarea></label><label>وضعیت مشتری<select name="lifecycleStatus"><option value="ACTIVE">فعال</option><option value="PAUSED">متوقف</option><option value="WON">موفق</option><option value="LOST">از دست‌رفته</option><option value="DO_NOT_CONTACT">عدم تماس</option></select></label><label>پیگیری بعدی<input name="nextActionAt" type="datetime-local"></label><label class="wide">موضوع پیگیری بعدی<input name="nextActionTitle"></label>`,async f=>{const d=Object.fromEntries(new FormData(f));await api(`/api/iran/customer-club/followups/${r.id}/complete`,{method:'PUT',body:JSON.stringify(d)})})}
 function importModal(){modal('ورود گروهی مشتریان از CSV',`<label class="wide">فایل CSV<input name="file" type="file" accept=".csv,text/csv" required></label><label>کارشناس پیش‌فرض<select name="defaultOwnerUserId">${ownerOptions()}</select></label><label>منبع داده<input name="defaultSource" placeholder="مثلاً نمایشگاه، تماس ورودی، فایل قدیمی"></label><div class="wide cc-import-note">ستون‌های فارسی یا انگلیسی شناخته می‌شوند؛ نمونه‌ها: نام مشتری، کد مشتری، موبایل، کد ملی، ایمیل، استان، شهر، آدرس، اولویت، تاریخ پیگیری، موضوع پیگیری، کارشناس. ردیف‌های تکراری بر اساس کد ملی، موبایل یا کد مشتری به‌روزرسانی می‌شوند و خطاهای هر ردیف نگهداری می‌شود.</div>`,async f=>{const file=f.elements.file.files[0];if(!file)throw new Error('فایل انتخاب نشده است.');const csvText=await file.text();const payload={csvText,sourceName:file.name,defaultOwnerUserId:Number(f.elements.defaultOwnerUserId.value),defaultSource:f.elements.defaultSource.value};const r=await api('/api/iran/customer-club/import',{method:'POST',body:JSON.stringify(payload)});toast(`ورود انجام شد: ${r.inserted} جدید، ${r.updated} به‌روزرسانی، ${r.rejected} ردشده`,r.rejected>0)})}
 async function showImportErrors(id){const rows=await api(`/api/iran/customer-club/imports/${id}/errors`);modal('خطاهای ورود',`<div class="wide cc-table-wrap"><table class="cc-table"><thead><tr><th>ردیف</th><th>شناسه</th><th>خطا</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${faNum.format(r.row_no)}</td><td>${esc(r.identity_key||'—')}</td><td>${esc(r.error_message)}</td></tr>`).join('')}</tbody></table></div>`,async()=>{});document.querySelector('#ccModalForm .primary').style.display='none'}
 function bind(){document.getElementById('ccNewCustomer').onclick=addCustomerModal;document.getElementById('ccImport').onclick=importModal;document.getElementById('ccRefresh').onclick=()=>Promise.all([loadDashboard(),loadTab(currentTab)]).catch(e=>toast(e.message,true));document.querySelectorAll('[data-cctab]').forEach(b=>b.onclick=()=>loadTab(b.dataset.cctab).catch(e=>toast(e.message,true)));['ccSearch','ccStatus','ccDue','ccOwner'].forEach(id=>{const e=document.getElementById(id);if(e)e.onchange=()=>loadCustomers().catch(x=>toast(x.message,true))});let t;document.getElementById('ccSearch').oninput=()=>{clearTimeout(t);t=setTimeout(()=>loadCustomers().catch(x=>toast(x.message,true)),300)};['ccFollowDue','ccFollowStatus'].forEach(id=>document.getElementById(id).onchange=()=>loadFollowups().catch(x=>toast(x.message,true)));document.getElementById('ccModalClose').onclick=()=>document.getElementById('ccModal').classList.add('hidden')}
 function init(){inject();bind()}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
