using System.Text.Json;

namespace Tarazpad.Desktop.Services;

public sealed class AppSettings
{
    public string ServerUrl { get; set; } = "http://127.0.0.1:8080";
    public bool RememberServer { get; set; } = true;

    public static string MachineSettingsDirectory => Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData),
        "Tarazpad", "client");

    public static string MachineSettingsPath => Path.Combine(MachineSettingsDirectory, "client.json");

    public static string UserSettingsDirectory => Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
        "Tarazpad", "client");

    public static string UserSettingsPath => Path.Combine(UserSettingsDirectory, "client.json");

    // Kept for UI compatibility: user changes are intentionally stored per-user so
    // a normal Windows user does not need administrator permission to change LAN server.
    public static string SettingsDirectory => UserSettingsDirectory;
    public static string SettingsPath => UserSettingsPath;

    public static AppSettings Load()
    {
        foreach (var path in new[] { UserSettingsPath, MachineSettingsPath })
        {
            try
            {
                if (!File.Exists(path)) continue;
                var value = JsonSerializer.Deserialize<AppSettings>(File.ReadAllText(path));
                if (value is not null && !string.IsNullOrWhiteSpace(value.ServerUrl)) return value;
            }
            catch
            {
                // A corrupt user override must not make the client unusable; fall back
                // to the machine default generated by the installer, then localhost.
            }
        }
        return new AppSettings();
    }

    public void Save()
    {
        Directory.CreateDirectory(UserSettingsDirectory);
        var temp = UserSettingsPath + ".tmp";
        File.WriteAllText(temp, JsonSerializer.Serialize(this, new JsonSerializerOptions { WriteIndented = true }));
        File.Move(temp, UserSettingsPath, true);
    }
}
