CREATE TABLE IF NOT EXISTS accounts (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, company_id BIGINT UNSIGNED NOT NULL, parent_id BIGINT UNSIGNED NULL, code VARCHAR(50) NOT NULL, title VARCHAR(200) NOT NULL, level_no TINYINT UNSIGNED NOT NULL DEFAULT 1,
  nature ENUM('DEBIT','CREDIT','MIXED') NOT NULL DEFAULT 'MIXED',account_type ENUM('ASSET','LIABILITY','EQUITY','REVENUE','EXPENSE','OTHER') NOT NULL,allow_posting TINYINT(1) NOT NULL DEFAULT 1,is_active TINYINT(1) NOT NULL DEFAULT 1,
  UNIQUE KEY uq_account_company_code(company_id,code),KEY ix_account_parent(parent_id),CONSTRAINT fk_account_company FOREIGN KEY(company_id) REFERENCES companies(id),CONSTRAINT fk_account_parent FOREIGN KEY(parent_id) REFERENCES accounts(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS journal_entries (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,company_id BIGINT UNSIGNED NOT NULL,entry_no VARCHAR(80) NOT NULL,entry_date DATE NOT NULL,posting_date DATE NULL,status ENUM('DRAFT','PREPARED','CHECKED','APPROVED','POSTED','LOCKED','VOID') NOT NULL DEFAULT 'DRAFT',source_type VARCHAR(80) NULL,source_id BIGINT UNSIGNED NULL,description VARCHAR(500) NULL,created_by BIGINT UNSIGNED NOT NULL,checked_by BIGINT UNSIGNED NULL,approved_by BIGINT UNSIGNED NULL,posted_at DATETIME NULL,void_reason VARCHAR(500) NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY uq_je_company_no(company_id,entry_no),KEY ix_je_date(company_id,entry_date),KEY ix_je_source(source_type,source_id),CONSTRAINT fk_je_company FOREIGN KEY(company_id) REFERENCES companies(id),CONSTRAINT fk_je_creator FOREIGN KEY(created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS parties (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,company_id BIGINT UNSIGNED NOT NULL,party_type ENUM('LEGAL','NATURAL') NOT NULL DEFAULT 'LEGAL',code VARCHAR(50) NULL,name VARCHAR(250) NOT NULL,national_id VARCHAR(30) NULL,economic_code VARCHAR(40) NULL,mobile VARCHAR(30) NULL,phone VARCHAR(50) NULL,email VARCHAR(190) NULL,address TEXT NULL,is_active TINYINT(1) NOT NULL DEFAULT 1,is_deleted TINYINT(1) NOT NULL DEFAULT 0,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 KEY ix_party_company_name(company_id,name),KEY ix_party_national(company_id,national_id),KEY ix_party_mobile(company_id,mobile),CONSTRAINT fk_party_company FOREIGN KEY(company_id) REFERENCES companies(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS party_roles (party_id BIGINT UNSIGNED NOT NULL,role_code ENUM('CUSTOMER','SUPPLIER','EMPLOYEE','SALESPERSON','DRIVER','CONTRACTOR','AGENT','OTHER') NOT NULL,PRIMARY KEY(party_id,role_code),CONSTRAINT fk_party_role_party FOREIGN KEY(party_id) REFERENCES parties(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS customer_profiles (party_id BIGINT UNSIGNED PRIMARY KEY,credit_limit DECIMAL(20,2) NOT NULL DEFAULT 0,payment_terms_days INT NOT NULL DEFAULT 0,discount_limit_pct DECIMAL(8,4) NOT NULL DEFAULT 0,health_score DECIMAL(8,2) NULL,loyalty_tier VARCHAR(50) NULL,CONSTRAINT fk_customer_party FOREIGN KEY(party_id) REFERENCES parties(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS supplier_profiles (party_id BIGINT UNSIGNED PRIMARY KEY,payment_terms_days INT NOT NULL DEFAULT 0,bank_iban VARCHAR(40) NULL,bank_change_pending TINYINT(1) NOT NULL DEFAULT 0,performance_score DECIMAL(8,2) NULL,CONSTRAINT fk_supplier_party FOREIGN KEY(party_id) REFERENCES parties(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS journal_lines (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,journal_entry_id BIGINT UNSIGNED NOT NULL,account_id BIGINT UNSIGNED NOT NULL,party_id BIGINT UNSIGNED NULL,cost_center_code VARCHAR(50) NULL,project_code VARCHAR(50) NULL,debit DECIMAL(20,2) NOT NULL DEFAULT 0,credit DECIMAL(20,2) NOT NULL DEFAULT 0,description VARCHAR(500) NULL,
 KEY ix_jl_entry(journal_entry_id),KEY ix_jl_account(account_id),KEY ix_jl_party(party_id),CONSTRAINT fk_jl_entry FOREIGN KEY(journal_entry_id) REFERENCES journal_entries(id) ON DELETE CASCADE,CONSTRAINT fk_jl_account FOREIGN KEY(account_id) REFERENCES accounts(id),CONSTRAINT fk_jl_party FOREIGN KEY(party_id) REFERENCES parties(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS accounting_mappings (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,company_id BIGINT UNSIGNED NOT NULL,event_code VARCHAR(80) NOT NULL,debit_account_id BIGINT UNSIGNED NOT NULL,credit_account_id BIGINT UNSIGNED NOT NULL,is_active TINYINT(1) NOT NULL DEFAULT 1,UNIQUE KEY uq_mapping(company_id,event_code),CONSTRAINT fk_map_company FOREIGN KEY(company_id) REFERENCES companies(id),CONSTRAINT fk_map_debit FOREIGN KEY(debit_account_id) REFERENCES accounts(id),CONSTRAINT fk_map_credit FOREIGN KEY(credit_account_id) REFERENCES accounts(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS receipts (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,company_id BIGINT UNSIGNED NOT NULL,receipt_no VARCHAR(80) NOT NULL,party_id BIGINT UNSIGNED NULL,receipt_date DATE NOT NULL,method ENUM('CASH','BANK','POS','CHEQUE','TRANSFER','OFFSET') NOT NULL,amount DECIMAL(20,2) NOT NULL,status ENUM('DRAFT','APPROVED','POSTED','RECONCILED','VOID') NOT NULL DEFAULT 'DRAFT',reference_no VARCHAR(120) NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_receipt(company_id,receipt_no),KEY ix_receipt_date(company_id,receipt_date),CONSTRAINT fk_receipt_company FOREIGN KEY(company_id) REFERENCES companies(id),CONSTRAINT fk_receipt_party FOREIGN KEY(party_id) REFERENCES parties(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS payments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,company_id BIGINT UNSIGNED NOT NULL,payment_no VARCHAR(80) NOT NULL,party_id BIGINT UNSIGNED NULL,payment_date DATE NOT NULL,method ENUM('CASH','BANK','CHEQUE','TRANSFER','PETTY_CASH','OFFSET') NOT NULL,amount DECIMAL(20,2) NOT NULL,status ENUM('DRAFT','REQUESTED','APPROVED','SCHEDULED','POSTED','RECONCILED','VOID') NOT NULL DEFAULT 'DRAFT',reference_no VARCHAR(120) NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_payment(company_id,payment_no),KEY ix_payment_date(company_id,payment_date),CONSTRAINT fk_payment_company FOREIGN KEY(company_id) REFERENCES companies(id),CONSTRAINT fk_payment_party FOREIGN KEY(party_id) REFERENCES parties(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;