ALTER TABLE compliance_periods
  MODIFY COLUMN status ENUM('OPEN','CALCULATED','REVIEWED','READY_TO_FILE','FILED','ACCEPTED','REJECTED','PAYMENT_DUE','PAID','CLOSED','NOT_APPLICABLE') NOT NULL DEFAULT 'OPEN',
  ADD COLUMN calculation_details_json JSON NULL,
  ADD COLUMN calculated_at DATETIME NULL,
  ADD COLUMN reviewed_at DATETIME NULL,
  ADD COLUMN approved_at DATETIME NULL,
  ADD COLUMN filed_by BIGINT UNSIGNED NULL,
  ADD COLUMN paid_by BIGINT UNSIGNED NULL,
  ADD CONSTRAINT fk_cp_filer FOREIGN KEY(filed_by) REFERENCES users(id),
  ADD CONSTRAINT fk_cp_payer FOREIGN KEY(paid_by) REFERENCES users(id);
