using System.Data;
using Bestplus.Data;
using Bestplus.Services;

namespace Bestplus.UI;

public sealed class InvoiceForm : BaseForm
{
    private readonly long _userId;private readonly string _kind;private readonly BusinessService _svc;
    private readonly ComboBox _person=Ui.Combo(310),_warehouse=Ui.Combo(210);private readonly TextBox _date=Ui.TextBox(120),_due=Ui.TextBox(120),_notes=Ui.TextBox(400);
    private readonly NumericUpDown _headerDiscount=Ui.Money(150),_freight=Ui.Money(150);private readonly DataGridView _grid=new();
    private readonly Label _subtotal=new(),_discTotal=new(),_taxTotal=new(),_grand=new();
    private bool _busy;

    public InvoiceForm(long userId,string kind)
    {
        _userId=userId;_kind=kind;_svc=new BusinessService(userId);Text=Title(kind);Width=1240;Height=780;MinimumSize=new Size(1050,700);Build();LoadLookups();Recalc();
    }
    private static string Title(string k)=>k switch{"SALE"=>"فاکتور فروش","PURCHASE"=>"فاکتور خرید","SALE_RETURN"=>"برگشت از فروش",_=>"برگشت از خرید"};
    private void Build()
    {
        var top=new RoundedPanel{Dock=DockStyle.Top,Height=132,BackColor=Color.White,Padding=new Padding(15)};var t=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=6,RowCount=2};for(int i=0;i<6;i++)t.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,i%2==0?12:21.3f));
        Add(t,"طرف حساب",_person,0,0);Add(t,"تاریخ",_date,2,0);Add(t,"سررسید",_due,4,0);Add(t,"انبار",_warehouse,0,1);Add(t,"تخفیف کلی",_headerDiscount,2,1);Add(t,"حمل / خدمات",_freight,4,1);top.Controls.Add(t);

        _grid.Dock=DockStyle.Fill;_grid.RightToLeft=RightToLeft.Yes;_grid.BackgroundColor=Color.White;_grid.BorderStyle=BorderStyle.None;_grid.RowHeadersVisible=false;_grid.AllowUserToAddRows=false;_grid.SelectionMode=DataGridViewSelectionMode.FullRowSelect;_grid.MultiSelect=false;_grid.AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill;_grid.Font=Ui.Font;_grid.RowTemplate.Height=36;_grid.EnableHeadersVisualStyles=false;_grid.ColumnHeadersHeight=40;_grid.ColumnHeadersDefaultCellStyle.BackColor=Color.FromArgb(232,238,247);_grid.ColumnHeadersDefaultCellStyle.Font=new Font("Tahoma",9,FontStyle.Bold);
        _grid.Columns.Add(new DataGridViewTextBoxColumn{Name="product_id",Visible=false});_grid.Columns.Add(new DataGridViewTextBoxColumn{Name="code",HeaderText="کد",ReadOnly=true,FillWeight=55});_grid.Columns.Add(new DataGridViewTextBoxColumn{Name="name",HeaderText="نام کالا",ReadOnly=true,FillWeight=180});
        _grid.Columns.Add(new DataGridViewTextBoxColumn{Name="qty",HeaderText="مقدار",FillWeight=60});_grid.Columns.Add(new DataGridViewTextBoxColumn{Name="unit",HeaderText="واحد",ReadOnly=true,FillWeight=60});_grid.Columns.Add(new DataGridViewTextBoxColumn{Name="factor",Visible=false});
        _grid.Columns.Add(new DataGridViewTextBoxColumn{Name="price",HeaderText="فی",FillWeight=90});_grid.Columns.Add(new DataGridViewTextBoxColumn{Name="discount",HeaderText="تخفیف",FillWeight=80});_grid.Columns.Add(new DataGridViewTextBoxColumn{Name="tax_percent",HeaderText="مالیات %",FillWeight=65});_grid.Columns.Add(new DataGridViewTextBoxColumn{Name="line_total",HeaderText="جمع ردیف",ReadOnly=true,FillWeight=100});
        _grid.CellEndEdit+=(_,__)=>Recalc();_grid.CellValueChanged+=(_,__)=>{if(!_busy)Recalc();};

        var tools=Ui.Toolbar();tools.Controls.Add(Ui.Button("+ افزودن کالا",(_,__)=>AddProduct(),true));tools.Controls.Add(Ui.Button("حذف ردیف",(_,__)=>{if(_grid.CurrentRow!=null)_grid.Rows.Remove(_grid.CurrentRow);Recalc();}));tools.Controls.Add(Ui.Button("تغییر واحد",(_,__)=>ChangeUnit()));
        var center=new Panel{Dock=DockStyle.Fill,BackColor=Color.White,Padding=new Padding(0)};center.Controls.Add(_grid);center.Controls.Add(tools);

        var bottom=new RoundedPanel{Dock=DockStyle.Bottom,Height=150,BackColor=Color.White,Padding=new Padding(15)};var summary=new FlowLayoutPanel{Dock=DockStyle.Top,Height=58,FlowDirection=FlowDirection.RightToLeft};SetupSum(_subtotal,"جمع کالا");SetupSum(_discTotal,"تخفیف");SetupSum(_taxTotal,"مالیات");SetupSum(_grand,"قابل پرداخت",true);summary.Controls.Add(_grand);summary.Controls.Add(_taxTotal);summary.Controls.Add(_discTotal);summary.Controls.Add(_subtotal);
        var actions=new FlowLayoutPanel{Dock=DockStyle.Bottom,Height=52,FlowDirection=FlowDirection.RightToLeft};actions.Controls.Add(Ui.Button("ثبت نهایی",(_,__)=>Save(),true));actions.Controls.Add(Ui.Button("انصراف",(_,__)=>Close()));_notes.Width=520;actions.Controls.Add(new Label{Text="توضیحات",AutoSize=true,Padding=new Padding(10,10,0,0)});actions.Controls.Add(_notes);bottom.Controls.Add(actions);bottom.Controls.Add(summary);
        Controls.Add(center);Controls.Add(bottom);Controls.Add(top);_headerDiscount.ValueChanged+=(_,__)=>Recalc();_freight.ValueChanged+=(_,__)=>Recalc();
    }
    private static void Add(TableLayoutPanel t,string label,Control c,int col,int row){t.Controls.Add(new Label{Text=label,Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleRight},col,row);c.Dock=DockStyle.Fill;t.Controls.Add(c,col+1,row);}
    private void SetupSum(Label l,string title,bool strong=false){l.Width=235;l.Height=50;l.Padding=new Padding(12,4,12,0);l.TextAlign=ContentAlignment.MiddleRight;l.ForeColor=strong?Ui.Accent:Ui.Text;l.Font=new Font("Tahoma",strong?11.5f:9.5f,strong?FontStyle.Bold:FontStyle.Regular);l.Tag=title;}
    private void LoadLookups(){foreach(DataRow r in Database.Query("SELECT id,name FROM persons WHERE is_active=1 ORDER BY name").Rows)_person.Items.Add(new ComboItem(Convert.ToInt64(r["id"]),Convert.ToString(r["name"])!));if(_person.Items.Count>0)_person.SelectedIndex=0;foreach(DataRow r in Database.Query("SELECT id,name FROM warehouses WHERE is_active=1 ORDER BY name").Rows)_warehouse.Items.Add(new ComboItem(Convert.ToInt64(r["id"]),Convert.ToString(r["name"])!));if(_warehouse.Items.Count>0)_warehouse.SelectedIndex=0;_date.Text=PersianDate.Format(DateTime.Today);_due.Text=PersianDate.Format(DateTime.Today);}
    private void AddProduct(){using var f=new ProductPicker(_kind);if(f.ShowDialog()!=DialogResult.OK)return;var i=_grid.Rows.Add(f.ProductId,f.Code,f.ProductName,1d,f.Unit,f.UnitFactor,f.Price,0L,f.TaxPercent,0L);_grid.CurrentCell=_grid.Rows[i].Cells["qty"];Recalc();}
    private void ChangeUnit(){if(_grid.CurrentRow==null)return;var pid=Convert.ToInt64(_grid.CurrentRow.Cells["product_id"].Value);var d=Database.Query("SELECT base_unit,pack_unit,pack_factor FROM products WHERE id=@p",("@p",pid));if(d.Rows.Count==0)return;var r=d.Rows[0];var b=$"{r["base_unit"]}";var p=$"{r["pack_unit"]}";var factor=Convert.ToDouble(r["pack_factor"]);if(string.IsNullOrWhiteSpace(p)){MessageBox.Show("برای این کالا واحد بسته تعریف نشده است.");return;}var current=$"{_grid.CurrentRow.Cells["unit"].Value}";if(current==b){_grid.CurrentRow.Cells["unit"].Value=p;_grid.CurrentRow.Cells["factor"].Value=factor;}else{_grid.CurrentRow.Cells["unit"].Value=b;_grid.CurrentRow.Cells["factor"].Value=1d;}Recalc();}
    private long CellLong(DataGridViewRow r,string c){var s=Convert.ToString(r.Cells[c].Value)?.Replace(",","").Replace("٬","")??"0";return long.TryParse(s,out var v)?v:0;}
    private double CellDouble(DataGridViewRow r,string c){var s=Convert.ToString(r.Cells[c].Value)??"0";return double.TryParse(s,out var v)?v:0;}
    private (long subtotal,long disc,long tax,long total) Totals(){var rows=_grid.Rows.Cast<DataGridViewRow>().ToList();var gross=rows.Sum(r=>checked((long)Math.Round(CellDouble(r,"qty")*CellLong(r,"price"))));var itemDisc=rows.Sum(r=>Math.Max(0,CellLong(r,"discount")));var hd=(long)_headerDiscount.Value;var basis=rows.Sum(r=>Math.Max(0L,checked((long)Math.Round(CellDouble(r,"qty")*CellLong(r,"price")))-Math.Max(0,CellLong(r,"discount"))));long tax=0,used=0;for(int i=0;i<rows.Count;i++){var gr=checked((long)Math.Round(CellDouble(rows[i],"qty")*CellLong(rows[i],"price")));var b=Math.Max(0L,gr-Math.Max(0,CellLong(rows[i],"discount")));var share=i==rows.Count-1?hd-used:(basis==0?0:checked((long)Math.Round(hd*(double)b/basis)));used+=share;var taxable=Math.Max(0L,b-share);tax+=checked((long)Math.Round(taxable*CellDouble(rows[i],"tax_percent")/100d));}return(gross,itemDisc+hd,tax,checked(gross-itemDisc-hd+tax+(long)_freight.Value));}
    private void Recalc(){if(_busy)return;_busy=true;try{foreach(DataGridViewRow r in _grid.Rows){var gross=checked((long)Math.Round(CellDouble(r,"qty")*CellLong(r,"price")));var tax=checked((long)Math.Round(Math.Max(0,gross-CellLong(r,"discount"))*CellDouble(r,"tax_percent")/100d));r.Cells["line_total"].Value=(gross-CellLong(r,"discount")+tax).ToString("N0");}var x=Totals();_subtotal.Text=$"{_subtotal.Tag}\n{x.subtotal:N0}";_discTotal.Text=$"{_discTotal.Tag}\n{x.disc:N0}";_taxTotal.Text=$"{_taxTotal.Tag}\n{x.tax:N0}";_grand.Text=$"{_grand.Tag}\n{x.total:N0} {Database.GetSetting("currency","ریال")}";}finally{_busy=false;}}
    private void Save(){if(_person.SelectedItem is not ComboItem person||_warehouse.SelectedItem is not ComboItem wh){MessageBox.Show("طرف حساب و انبار را انتخاب کنید.");return;}if(!PersianDate.TryParse(_date.Text,out var date)){MessageBox.Show("تاریخ فاکتور صحیح نیست.");return;}DateTime? due=null;if(!string.IsNullOrWhiteSpace(_due.Text)){if(!PersianDate.TryParse(_due.Text,out var dd)){MessageBox.Show("تاریخ سررسید صحیح نیست.");return;}due=dd;}var d=new InvoiceDraft{Kind=_kind,Date=date,DueDate=due,PersonId=person.Id,WarehouseId=wh.Id,HeaderDiscount=(long)_headerDiscount.Value,Freight=(long)_freight.Value,Notes=_notes.Text.Trim()};foreach(DataGridViewRow r in _grid.Rows){var q=CellDouble(r,"qty");if(q<=0)continue;d.Items.Add(new InvoiceItemDraft{ProductId=Convert.ToInt64(r.Cells["product_id"].Value),ProductCode=$"{r.Cells["code"].Value}",ProductName=$"{r.Cells["name"].Value}",Qty=q,Unit=$"{r.Cells["unit"].Value}",UnitFactor=CellDouble(r,"factor"),UnitPrice=CellLong(r,"price"),Discount=CellLong(r,"discount"),TaxPercent=CellDouble(r,"tax_percent")});}try{var preview=Totals();if(_kind=="SALE"){var p=Database.Query("SELECT credit_limit FROM persons WHERE id=@p",("@p",person.Id));var limit=p.Rows.Count==0?0:Convert.ToInt64(p.Rows[0]["credit_limit"]);var bal=BusinessService.PersonBalance(person.Id);if(limit>0&&bal+preview.total>limit&&MessageBox.Show($"سقف اعتبار مشتری عبور می‌کند.\nمانده فعلی: {bal:N0}\nفاکتور: {preview.total:N0}\nسقف: {limit:N0}\n\nادامه؟","کنترل اعتبار",MessageBoxButtons.YesNo,MessageBoxIcon.Warning)!=DialogResult.Yes)return;}var result=_svc.CreateInvoice(d);MessageBox.Show($"فاکتور {result.Number} با مبلغ {result.Total:N0} ثبت شد.","ثبت موفق",MessageBoxButtons.OK,MessageBoxIcon.Information);DialogResult=DialogResult.OK;Close();}catch(Exception ex){MessageBox.Show(ex.Message,"ثبت فاکتور",MessageBoxButtons.OK,MessageBoxIcon.Error);}}
}

public sealed class ProductPicker : BaseForm
{
    private readonly string _kind;private readonly DataGridView _g=Ui.Grid();private readonly TextBox _search=Ui.TextBox(280);private readonly ComboBox _unit=Ui.Combo(170);public long ProductId;public string Code="",ProductName="",Unit="";public double UnitFactor=1,TaxPercent;public long Price;
    public ProductPicker(string kind){_kind=kind;Text="انتخاب کالا";Width=900;Height=620;var bar=Ui.Toolbar();bar.Controls.Add(Ui.Button("انتخاب",(_,__)=>Pick(),true));bar.Controls.Add(_search);bar.Controls.Add(_unit);Controls.Add(_g);Controls.Add(bar);_search.TextChanged+=(_,__)=>Bind();_g.SelectionChanged+=(_,__)=>Units();_g.CellDoubleClick+=(_,__)=>Pick();Bind();}
    private void Bind(){_g.DataSource=Database.Query(@"SELECT p.id,p.code,p.barcode,p.name,p.base_unit,p.pack_unit,p.pack_factor,p.buy_price,p.sell_price,p.tax_percent,ROUND(COALESCE(SUM(ps.qty),0),3) stock FROM products p LEFT JOIN product_stock ps ON ps.product_id=p.id WHERE p.is_active=1 AND (@q='' OR p.name LIKE '%'||@q||'%' OR p.code LIKE '%'||@q||'%' OR p.barcode LIKE '%'||@q||'%') GROUP BY p.id ORDER BY p.name",("@q",_search.Text.Trim()));Ui.Hide(_g,"id","pack_factor");Ui.Header(_g,"code","کد");Ui.Header(_g,"barcode","بارکد");Ui.Header(_g,"name","کالا");Ui.Header(_g,"base_unit","واحد");Ui.Header(_g,"pack_unit","بسته");Ui.Header(_g,"buy_price","خرید");Ui.Header(_g,"sell_price","فروش");Ui.Header(_g,"tax_percent","مالیات %");Ui.Header(_g,"stock","موجودی");Ui.MoneyColumn(_g,"buy_price");Ui.MoneyColumn(_g,"sell_price");Units();}
    private void Units(){_unit.Items.Clear();if(_g.CurrentRow==null)return;var b=$"{_g.CurrentRow.Cells["base_unit"].Value}";var p=$"{_g.CurrentRow.Cells["pack_unit"].Value}";_unit.Items.Add(b);if(!string.IsNullOrWhiteSpace(p))_unit.Items.Add(p);_unit.SelectedIndex=0;}
    private void Pick(){if(_g.CurrentRow==null)return;ProductId=Convert.ToInt64(_g.CurrentRow.Cells["id"].Value);Code=$"{_g.CurrentRow.Cells["code"].Value}";ProductName=$"{_g.CurrentRow.Cells["name"].Value}";var b=$"{_g.CurrentRow.Cells["base_unit"].Value}";var p=$"{_g.CurrentRow.Cells["pack_unit"].Value}";var f=Convert.ToDouble(_g.CurrentRow.Cells["pack_factor"].Value);Unit=_unit.Text;UnitFactor=Unit==p&&!string.IsNullOrWhiteSpace(p)?f:1d;TaxPercent=Convert.ToDouble(_g.CurrentRow.Cells["tax_percent"].Value);Price=_kind is "PURCHASE" or "PURCHASE_RETURN"?Convert.ToInt64(_g.CurrentRow.Cells["buy_price"].Value):Convert.ToInt64(_g.CurrentRow.Cells["sell_price"].Value);DialogResult=DialogResult.OK;Close();}
}
