import bcrypt from 'bcryptjs';
import { pool, withTransaction } from './db.js';
import { requireRole } from './auth.js';
const txt=v=>String(v??'').trim();
const fail=(m,s=400,d=null)=>{const e=new Error(m);e.status=s;e.details=d;throw e};
const wrap=fn=>async(req,res)=>{try{await fn(req,res)}catch(e){console.error('admin v2 error',e);res.status(e.status||400).json({error:e.message,details:e.details||undefined})}};
async function audit(req,a,type,id,before,after){try{await pool.execute(`INSERT INTO audit_logs(company_id,user_id,action,entity_type,entity_id,before_json,after_json,ip_address,user_agent) VALUES (?,?,?,?,?,?,?,?,?)`,[req.user.companyId,Number(req.user.sub),a,type,id,before?JSON.stringify(before):null,after?JSON.stringify(after):null,req.ip,req.headers['user-agent']||null])}catch{}}
async function roleIds(conn,codes){if(!Array.isArray(codes)||!codes.length)return[];const clean=[...new Set(codes.map(x=>txt(x).toUpperCase()).filter(Boolean))];const marks=clean.map(()=>'?').join(',');const [rows]=await conn.query(`SELECT id,code FROM roles WHERE code IN (${marks})`,clean);if(rows.length!==clean.length){const got=new Set(rows.map(x=>x.code));fail('یک یا چند نقش معتبر نیست.',422,{invalid:clean.filter(x=>!got.has(x))})}return rows}
async function userWithRoles(conn,id,companyId){const [r]=await conn.execute(`SELECT u.id,u.company_id,u.branch_id,u.full_name,u.email,u.is_active,u.last_login_at,u.created_at,GROUP_CONCAT(ro.code ORDER BY ro.code) roles FROM users u LEFT JOIN user_roles ur ON ur.user_id=u.id LEFT JOIN roles ro ON ro.id=ur.role_id WHERE u.id=? AND u.company_id=? GROUP BY u.id`,[id,companyId]);return r[0]||null}
export function registerAdminV2Routes(app){
 app.get('/api/iran/admin/roles',requireRole('SUPER_ADMIN'),wrap(async(req,res)=>{const [rows]=await pool.execute('SELECT id,code,title,is_system FROM roles ORDER BY is_system DESC,title');res.json(rows)}));
 app.get('/api/iran/admin/users',requireRole('SUPER_ADMIN'),wrap(async(req,res)=>{const q=txt(req.query.q),active=txt(req.query.active),where=['u.company_id=?'],p=[req.user.companyId];if(q){const l=`%${q}%`;where.push('(u.full_name LIKE ? OR u.email LIKE ?)');p.push(l,l)}if(active!==''){where.push('u.is_active=?');p.push(active==='1'||active==='true'?1:0)}const [rows]=await pool.execute(`SELECT u.id,u.branch_id,u.full_name,u.email,u.is_active,u.last_login_at,u.created_at,b.name branch_name,GROUP_CONCAT(r.code ORDER BY r.code) role_codes,GROUP_CONCAT(r.title ORDER BY r.title SEPARATOR '، ') role_titles FROM users u LEFT JOIN branches b ON b.id=u.branch_id LEFT JOIN user_roles ur ON ur.user_id=u.id LEFT JOIN roles r ON r.id=ur.role_id WHERE ${where.join(' AND ')} GROUP BY u.id ORDER BY u.is_active DESC,u.full_name`,p);res.json(rows)}));
 app.post('/api/iran/admin/users',requireRole('SUPER_ADMIN'),wrap(async(req,res)=>{const b=req.body||{},name=txt(b.fullName),email=txt(b.email).toLowerCase(),password=String(b.password||'');if(!name||!email||!email.includes('@'))fail('نام و ایمیل معتبر الزامی است.');if(password.length<10)fail('رمز عبور باید حداقل ۱۰ نویسه داشته باشد.');const roles=Array.isArray(b.roleCodes)?b.roleCodes:[];if(!roles.length)fail('حداقل یک نقش برای کاربر انتخاب کنید.');const result=await withTransaction(async conn=>{const [old]=await conn.execute('SELECT id FROM users WHERE email=?',[email]);if(old.length)fail('این ایمیل قبلاً ثبت شده است.',409);if(b.branchId){const [br]=await conn.execute('SELECT id FROM branches WHERE id=? AND company_id=? AND is_active=1',[b.branchId,req.user.companyId]);if(!br.length)fail('شعبه انتخاب‌شده معتبر نیست.',422)}const rs=await roleIds(conn,roles),hash=await bcrypt.hash(password,12),[r]=await conn.execute(`INSERT INTO users(company_id,branch_id,full_name,email,password_hash,is_active) VALUES (?,?,?,?,?,1)`,[req.user.companyId,b.branchId||null,name,email,hash]);for(const role of rs)await conn.execute('INSERT INTO user_roles(user_id,role_id) VALUES (?,?)',[r.insertId,role.id]);return await userWithRoles(conn,r.insertId,req.user.companyId)});await audit(req,'CREATE','user',result.id,null,{...result,password:undefined});res.status(201).json(result)}));
 app.put('/api/iran/admin/users/:id',requireRole('SUPER_ADMIN'),wrap(async(req,res)=>{const id=Number(req.params.id),b=req.body||{};const result=await withTransaction(async conn=>{const before=await userWithRoles(conn,id,req.user.companyId);if(!before)fail('کاربر پیدا نشد.',404);if(b.branchId!==undefined&&b.branchId!==null){const [br]=await conn.execute('SELECT id FROM branches WHERE id=? AND company_id=? AND is_active=1',[b.branchId,req.user.companyId]);if(!br.length)fail('شعبه معتبر نیست.',422)}await conn.execute(`UPDATE users SET full_name=COALESCE(?,full_name),branch_id=?,email=COALESCE(?,email) WHERE id=? AND company_id=?`,[b.fullName??null,b.branchId===undefined?before.branch_id:(b.branchId||null),b.email?txt(b.email).toLowerCase():null,id,req.user.companyId]);const after=await userWithRoles(conn,id,req.user.companyId);return{before,after}});await audit(req,'UPDATE','user',id,result.before,result.after);res.json(result.after)}));
 app.put('/api/iran/admin/users/:id/roles',requireRole('SUPER_ADMIN'),wrap(async(req,res)=>{const id=Number(req.params.id),codes=req.body?.roleCodes;if(!Array.isArray(codes)||!codes.length)fail('حداقل یک نقش الزامی است.');const result=await withTransaction(async conn=>{const before=await userWithRoles(conn,id,req.user.companyId);if(!before)fail('کاربر پیدا نشد.',404);const rs=await roleIds(conn,codes),newCodes=rs.map(x=>x.code);if(id===Number(req.user.sub)&&String(before.roles||'').split(',').includes('SUPER_ADMIN')&&!newCodes.includes('SUPER_ADMIN')){const [[cnt]]=await conn.execute(`SELECT COUNT(DISTINCT u.id) cnt FROM users u JOIN user_roles ur ON ur.user_id=u.id JOIN roles r ON r.id=ur.role_id WHERE u.company_id=? AND u.is_active=1 AND r.code='SUPER_ADMIN'`,[req.user.companyId]);if(Number(cnt.cnt)<=1)fail('آخرین مدیر ارشد سیستم نمی‌تواند نقش مدیر ارشد خود را حذف کند.',409)}await conn.execute('DELETE FROM user_roles WHERE user_id=?',[id]);for(const r of rs)await conn.execute('INSERT INTO user_roles(user_id,role_id) VALUES (?,?)',[id,r.id]);return{before,after:await userWithRoles(conn,id,req.user.companyId)}});await audit(req,'ROLE_CHANGE','user',id,result.before,result.after);res.json(result.after)}));
 app.put('/api/iran/admin/users/:id/status',requireRole('SUPER_ADMIN'),wrap(async(req,res)=>{const id=Number(req.params.id),active=Boolean(req.body?.isActive);if(id===Number(req.user.sub)&&!active)fail('کاربر جاری نمی‌تواند حساب خودش را غیرفعال کند.',409);const [before]=await pool.execute('SELECT id,full_name,email,is_active FROM users WHERE id=? AND company_id=?',[id,req.user.companyId]);if(!before.length)fail('کاربر پیدا نشد.',404);await pool.execute('UPDATE users SET is_active=? WHERE id=? AND company_id=?',[active?1:0,id,req.user.companyId]);await audit(req,active?'ACTIVATE':'DEACTIVATE','user',id,before[0],{is_active:active});res.json({ok:true,isActive:active})}));
 app.post('/api/iran/admin/users/:id/reset-password',requireRole('SUPER_ADMIN'),wrap(async(req,res)=>{const id=Number(req.params.id),password=String(req.body?.password||'');if(password.length<10)fail('رمز عبور جدید باید حداقل ۱۰ نویسه داشته باشد.');const hash=await bcrypt.hash(password,12),[r]=await pool.execute('UPDATE users SET password_hash=? WHERE id=? AND company_id=?',[hash,id,req.user.companyId]);if(!r.affectedRows)fail('کاربر پیدا نشد.',404);await audit(req,'PASSWORD_RESET','user',id,null,{resetBy:Number(req.user.sub)});res.json({ok:true})}));
}
