import crypto from 'node:crypto';
import { pool, withTransaction } from './db.js';
import { requireRole } from './auth.js';
const n=v=>Number(v||0),txt=v=>String(v??'').trim();
const fail=(m,s=400,d=null)=>{const e=new Error(m);e.status=s;e.details=d;throw e};
const wrap=fn=>async(req,res)=>{try{await fn(req,res)}catch(e){console.error('bank import v2 error',e);res.status(e.status||400).json({error:e.message,details:e.details||undefined})}};
function rowHash(bankAccountId,r){return crypto.createHash('sha256').update([bankAccountId,txt(r.statementDate),n(r.debit),n(r.credit),txt(r.referenceNo),txt(r.description),txt(r.externalId)].join('|')).digest('hex')}
export function registerBankImportV2Routes(app){
 app.post('/api/iran/treasury/bank-statements/preview',requireRole('ACCOUNTANT','FINANCE_MANAGER'),wrap(async(req,res)=>{const b=req.body||{},bank=Number(b.bankAccountId),rows=Array.isArray(b.rows)?b.rows:[];if(!bank||!rows.length)fail('حساب بانکی و ردیف‌های گردش الزامی است.');const [ba]=await pool.execute('SELECT id FROM bank_accounts WHERE id=? AND company_id=?',[bank,req.user.companyId]);if(!ba.length)fail('حساب بانکی معتبر نیست.',422);const prepared=[],hashes=[];for(let i=0;i<rows.length;i++){const r=rows[i],debit=n(r.debit),credit=n(r.credit),valid=Boolean(txt(r.statementDate))&&debit>=0&&credit>=0&&!(debit>0&&credit>0)&&(debit>0||credit>0);const hash=rowHash(bank,r);hashes.push(hash);prepared.push({rowNo:i+1,...r,debit,credit,rowHash:hash,valid,error:valid?null:'تاریخ و یکی از ستون‌های برداشت/واریز باید معتبر باشد.'})}let existing=new Set();if(hashes.length){const marks=hashes.map(()=>'?').join(',');const [x]=await pool.query(`SELECT row_hash FROM bank_statement_lines WHERE company_id=? AND bank_account_id=? AND row_hash IN (${marks})`,[req.user.companyId,bank,...hashes]);existing=new Set(x.map(x=>x.row_hash))}for(const r of prepared)r.duplicate=existing.has(r.rowHash);res.json({rows:prepared,total:prepared.length,valid:prepared.filter(x=>x.valid&&!x.duplicate).length,duplicates:prepared.filter(x=>x.duplicate).length,invalid:prepared.filter(x=>!x.valid).length})}));
 app.post('/api/iran/treasury/bank-statements/import',requireRole('ACCOUNTANT','FINANCE_MANAGER'),wrap(async(req,res)=>{const b=req.body||{},bank=Number(b.bankAccountId),rows=Array.isArray(b.rows)?b.rows:[];if(!bank||!rows.length)fail('حساب بانکی و ردیف‌های گردش الزامی است.');const result=await withTransaction(async conn=>{const [ba]=await conn.execute('SELECT id FROM bank_accounts WHERE id=? AND company_id=? FOR UPDATE',[bank,req.user.companyId]);if(!ba.length)fail('حساب بانکی معتبر نیست.',422);const fileHash=b.fileHash||crypto.createHash('sha256').update(`${bank}|${txt(b.fileName)}|${JSON.stringify(rows)}`).digest('hex');const [oldBatch]=await conn.execute('SELECT * FROM bank_import_batches WHERE company_id=? AND bank_account_id=? AND file_hash=?',[req.user.companyId,bank,fileHash]);if(oldBatch.length)return{batchId:oldBatch[0].id,imported:Number(oldBatch[0].imported_rows),duplicates:Number(oldBatch[0].duplicate_rows),invalid:Number(oldBatch[0].invalid_rows),duplicateBatch:true};const [batch]=await conn.execute(`INSERT INTO bank_import_batches(company_id,bank_account_id,file_name,file_hash,imported_by) VALUES (?,?,?,?,?)`,[req.user.companyId,bank,b.fileName||null,fileHash,Number(req.user.sub)]);let imported=0,duplicates=0,invalid=0;for(const r of rows){const debit=n(r.debit),credit=n(r.credit),valid=Boolean(txt(r.statementDate))&&debit>=0&&credit>=0&&!(debit>0&&credit>0)&&(debit>0||credit>0);if(!valid){invalid++;continue}const hash=rowHash(bank,r);try{await conn.execute(`INSERT INTO bank_statement_lines(company_id,bank_account_id,statement_date,debit,credit,description,reference_no,match_status,import_batch_id,row_hash) VALUES (?,?,?,?,?,?,?,'UNMATCHED',?,?)`,[req.user.companyId,bank,r.statementDate,debit,credit,r.description||null,r.referenceNo||null,batch.insertId,hash]);imported++}catch(e){if(e.code==='ER_DUP_ENTRY')duplicates++;else throw e}}await conn.execute(`UPDATE bank_import_batches SET imported_rows=?,duplicate_rows=?,invalid_rows=? WHERE id=?`,[imported,duplicates,invalid,batch.insertId]);return{batchId:batch.insertId,imported,duplicates,invalid,fileHash}});res.status(result.duplicateBatch?200:201).json(result)}));
 app.get('/api/iran/treasury/bank-statements/import-batches',requireRole('ACCOUNTANT','FINANCE_MANAGER'),wrap(async(req,res)=>{const [rows]=await pool.execute(`SELECT b.*,ba.bank_name,ba.account_title,u.full_name imported_by_name FROM bank_import_batches b JOIN bank_accounts ba ON ba.id=b.bank_account_id JOIN users u ON u.id=b.imported_by WHERE b.company_id=? ORDER BY b.imported_at DESC,b.id DESC LIMIT 200`,[req.user.companyId]);res.json(rows)}));
}
