import { pool, withTransaction } from './db.js';
import { requireRole } from './auth.js';
const n=v=>Number(v||0),txt=v=>String(v??'').trim();
const fail=(m,s=400)=>{const e=new Error(m);e.status=s;throw e};
const wrap=fn=>async(req,res)=>{try{await fn(req,res)}catch(e){console.error('bi v5 error',e);res.status(e.status||400).json({error:e.message})}};
const range=req=>({from:txt(req.query.dateFrom)||'1900-01-01',to:txt(req.query.dateTo)||'2999-12-31'});
async function scalar(sql,p){const [r]=await pool.execute(sql,p);return n(r[0]?.value)}

const kpis={
 NET_SALES:async(req)=>{const d=range(req);return scalar(`SELECT COALESCE(SUM(net_total),0) value FROM sales_invoices WHERE company_id=? AND is_void=0 AND posted_at IS NOT NULL AND invoice_date BETWEEN ? AND ?`,[req.user.companyId,d.from,d.to])},
 GROSS_PROFIT:async(req)=>{const d=range(req);return scalar(`SELECT COALESCE(SUM(l.gross_profit_amount),0) value FROM sales_invoice_lines l JOIN sales_invoices h ON h.id=l.invoice_id WHERE h.company_id=? AND h.is_void=0 AND h.posted_at IS NOT NULL AND h.invoice_date BETWEEN ? AND ?`,[req.user.companyId,d.from,d.to])},
 GROSS_MARGIN:async(req)=>{const d=range(req),[r]=await pool.execute(`SELECT COALESCE(SUM(h.net_total),0) sales,COALESCE(SUM(x.gp),0) gp FROM sales_invoices h LEFT JOIN (SELECT invoice_id,SUM(gross_profit_amount) gp FROM sales_invoice_lines GROUP BY invoice_id)x ON x.invoice_id=h.id WHERE h.company_id=? AND h.is_void=0 AND h.posted_at IS NOT NULL AND h.invoice_date BETWEEN ? AND ?`,[req.user.companyId,d.from,d.to]);return n(r[0]?.sales)?n(r[0]?.gp)/n(r[0]?.sales)*100:0},
 AR_BALANCE:async(req)=>scalar(`SELECT COALESCE(SUM(outstanding_amount),0) value FROM sales_invoices WHERE company_id=? AND is_void=0 AND outstanding_amount>0`,[req.user.companyId]),
 AP_BALANCE:async(req)=>scalar(`SELECT COALESCE(SUM(outstanding_amount),0) value FROM purchase_invoices WHERE company_id=? AND is_void=0 AND outstanding_amount>0`,[req.user.companyId]),
 OVERDUE_AR:async(req)=>scalar(`SELECT COALESCE(SUM(outstanding_amount),0) value FROM sales_invoices WHERE company_id=? AND is_void=0 AND outstanding_amount>0 AND due_date IS NOT NULL AND due_date<CURRENT_DATE`,[req.user.companyId]),
 CASH_POSITION:async(req)=>scalar(`SELECT COALESCE(SUM(CASE WHEN a.nature='CREDIT' THEN jl.credit-jl.debit ELSE jl.debit-jl.credit END),0) value FROM journal_lines jl JOIN journal_entries je ON je.id=jl.journal_entry_id JOIN accounts a ON a.id=jl.account_id WHERE je.company_id=? AND je.status IN ('POSTED','LOCKED') AND (jl.account_id IN (SELECT gl_account_id FROM bank_accounts WHERE company_id=? AND is_active=1 AND gl_account_id IS NOT NULL) OR jl.account_id=(SELECT cash_account_id FROM treasury_account_settings WHERE company_id=? LIMIT 1))`,[req.user.companyId,req.user.companyId,req.user.companyId]),
 INVENTORY_VALUE:async(req)=>scalar(`SELECT COALESCE(SUM(on_hand_qty*average_cost),0) value FROM inventory_balances WHERE company_id=?`,[req.user.companyId]),
 DELIVERY_RATE:async(req)=>{const [r]=await pool.execute(`SELECT COUNT(*) total,SUM(s.status='DELIVERED') delivered FROM trip_stops s JOIN trips t ON t.id=s.trip_id WHERE t.company_id=?`,[req.user.companyId]);return n(r[0]?.total)?n(r[0]?.delivered)/n(r[0]?.total)*100:0},
 HEADCOUNT:async(req)=>scalar(`SELECT COUNT(*) value FROM employee_profiles ep JOIN parties p ON p.id=ep.party_id WHERE p.company_id=? AND ep.employment_status='ACTIVE' AND p.is_deleted=0`,[req.user.companyId]),
 PAYROLL_NET:async(req)=>scalar(`SELECT total_net value FROM payroll_batches WHERE company_id=? AND status IN ('CALCULATED','REVIEWED','APPROVED','POSTED','PAID','CLOSED') ORDER BY year_no DESC,month_no DESC LIMIT 1`,[req.user.companyId])
};

export function registerBiV5Routes(app){
 app.get('/api/iran/bi/kpi/:code',wrap(async(req,res)=>{const code=txt(req.params.code).toUpperCase(),fn=kpis[code];if(!fn)fail('شاخص تعریف‌شده در موتور اجرایی پیدا نشد.',404);const value=await fn(req);res.json({code,value,calculatedAt:new Date().toISOString(),filters:{dateFrom:req.query.dateFrom||null,dateTo:req.query.dateTo||null}})}));
 app.get('/api/iran/bi/kpis',wrap(async(req,res)=>{const [rows]=await pool.execute(`SELECT * FROM kpi_definitions WHERE (company_id=? OR company_id IS NULL) AND is_active=1 AND effective_from<=CURRENT_DATE AND (effective_to IS NULL OR effective_to>=CURRENT_DATE) ORDER BY domain_code,title_fa`,[req.user.companyId]);res.json(rows)}));
 app.get('/api/iran/bi/semantic-models',wrap(async(req,res)=>{const [models]=await pool.execute(`SELECT * FROM semantic_models WHERE (company_id=? OR company_id IS NULL) AND is_active=1 ORDER BY domain_code,title_fa`,[req.user.companyId]);for(const m of models){const [f]=await pool.execute('SELECT * FROM semantic_fields WHERE semantic_model_id=? AND is_active=1 ORDER BY id',[m.id]);m.fields=f}res.json(models)}));
 app.post('/api/iran/bi/semantic-models',requireRole('FINANCE_MANAGER','SUPER_ADMIN'),wrap(async(req,res)=>{const b=req.body||{};if(!txt(b.code)||!txt(b.title)||!txt(b.domain)||!txt(b.baseSource))fail('کد، عنوان، حوزه و منبع مدل معنایی الزامی است.');const [r]=await pool.execute(`INSERT INTO semantic_models(company_id,code,title_fa,domain_code,base_source,grain_description,row_filter_sql,created_by) VALUES (?,?,?,?,?,?,?,?)`,[req.user.companyId,b.code,b.title,b.domain,b.baseSource,b.grainDescription||'',b.rowFilterSql||null,Number(req.user.sub)]);res.status(201).json({id:r.insertId})}));
 app.get('/api/iran/bi/widget-catalog',wrap(async(req,res)=>{const [rows]=await pool.execute(`SELECT * FROM dashboard_widget_catalog WHERE is_active=1 ORDER BY domain_code,title_fa`);res.json(rows)}));
 app.get('/api/iran/bi/dashboards',wrap(async(req,res)=>{const [rows]=await pool.execute(`SELECT * FROM user_dashboards WHERE company_id=? AND (user_id=? OR scope IN ('COMPANY','EXECUTIVE')) ORDER BY is_default DESC,id`,[req.user.companyId,Number(req.user.sub)]);for(const d of rows){const [w]=await pool.execute(`SELECT uw.*,c.title_fa,c.domain_code,c.widget_type,c.data_endpoint,c.default_size FROM user_dashboard_widgets uw JOIN dashboard_widget_catalog c ON c.code=uw.widget_code WHERE uw.dashboard_id=? ORDER BY uw.sort_order,uw.position_y,uw.position_x`,[d.id]);d.widgets=w}res.json(rows)}));
 app.post('/api/iran/bi/dashboards',wrap(async(req,res)=>{const b=req.body||{};const code=txt(b.dashboardCode)||`PERSONAL-${Date.now()}`,title=txt(b.title)||'داشبورد شخصی';const [r]=await pool.execute(`INSERT INTO user_dashboards(company_id,user_id,dashboard_code,title,scope,global_filters_json,is_default) VALUES (?,?,?,?,?,?,?)`,[req.user.companyId,Number(req.user.sub),code,title,b.scope||'PERSONAL',JSON.stringify(b.globalFilters||{}),b.isDefault?1:0]);res.status(201).json({id:r.insertId,dashboardCode:code})}));
 app.put('/api/iran/bi/dashboards/:id/widgets',wrap(async(req,res)=>{const id=Number(req.params.id),widgets=Array.isArray(req.body?.widgets)?req.body.widgets:[];await withTransaction(async conn=>{const [d]=await conn.execute(`SELECT * FROM user_dashboards WHERE id=? AND company_id=? AND (user_id=? OR ?=1) FOR UPDATE`,[id,req.user.companyId,Number(req.user.sub),(req.user.roles||[]).includes('SUPER_ADMIN')?1:0]);if(!d.length)fail('داشبورد قابل ویرایش نیست.',403);await conn.execute('DELETE FROM user_dashboard_widgets WHERE dashboard_id=?',[id]);let order=0;for(const w of widgets){if(!txt(w.widgetCode))continue;order++;await conn.execute(`INSERT INTO user_dashboard_widgets(dashboard_id,widget_code,position_x,position_y,width_units,height_units,config_json,is_visible,sort_order) VALUES (?,?,?,?,?,?,?,?,?)`,[id,w.widgetCode,n(w.x),n(w.y),Math.max(1,n(w.width)||4),Math.max(1,n(w.height)||2),JSON.stringify(w.config||{}),w.visible===false?0:1,order])}});res.json({ok:true,count:widgets.length})}));

 app.get('/api/iran/bi/top-customers',wrap(async(req,res)=>{const d=range(req);const [rows]=await pool.execute(`SELECT p.id,p.name,COUNT(si.id) invoice_count,SUM(si.net_total) net_sales,SUM(si.outstanding_amount) outstanding FROM sales_invoices si JOIN parties p ON p.id=si.customer_party_id WHERE si.company_id=? AND si.is_void=0 AND si.posted_at IS NOT NULL AND si.invoice_date BETWEEN ? AND ? GROUP BY p.id,p.name ORDER BY net_sales DESC LIMIT 20`,[req.user.companyId,d.from,d.to]);res.json(rows)}));
 app.get('/api/iran/bi/top-products',wrap(async(req,res)=>{const d=range(req);const [rows]=await pool.execute(`SELECT p.id,p.sku,p.name,SUM(l.qty) qty,SUM(l.amount_after_discount) net_sales,SUM(l.gross_profit_amount) gross_profit FROM sales_invoice_lines l JOIN sales_invoices si ON si.id=l.invoice_id JOIN products p ON p.id=l.product_id WHERE si.company_id=? AND si.is_void=0 AND si.posted_at IS NOT NULL AND si.invoice_date BETWEEN ? AND ? GROUP BY p.id,p.sku,p.name ORDER BY net_sales DESC LIMIT 20`,[req.user.companyId,d.from,d.to]);res.json(rows)}));
 app.get('/api/iran/bi/low-stock',wrap(async(req,res)=>{const [rows]=await pool.execute(`SELECT p.id,p.sku,p.name,p.reorder_point,COALESCE(SUM(ib.on_hand_qty-ib.reserved_qty-ib.quarantine_qty-ib.damaged_qty),0) available_qty FROM products p LEFT JOIN inventory_balances ib ON ib.product_id=p.id AND ib.company_id=p.company_id WHERE p.company_id=? AND p.is_deleted=0 AND p.product_type='GOODS' GROUP BY p.id,p.sku,p.name,p.reorder_point HAVING available_qty<=p.reorder_point ORDER BY available_qty LIMIT 100`,[req.user.companyId]);res.json(rows)}));
 app.get('/api/iran/bi/near-expiry',wrap(async(req,res)=>{const days=Math.min(365,Math.max(1,n(req.query.days)||30));const [rows]=await pool.execute(`SELECT ib.*,p.sku,p.name,w.name warehouse FROM inventory_balances ib JOIN products p ON p.id=ib.product_id JOIN warehouses w ON w.id=ib.warehouse_id WHERE ib.company_id=? AND ib.on_hand_qty>0 AND ib.expiry_date BETWEEN CURRENT_DATE AND DATE_ADD(CURRENT_DATE,INTERVAL ${days} DAY) ORDER BY ib.expiry_date LIMIT 200`,[req.user.companyId]);res.json(rows)}));
 app.get('/api/iran/bi/treasury-7d',wrap(async(req,res)=>{const [rows]=await pool.execute(`SELECT 'RECEIVABLE' item_type,invoice_no ref_no,due_date,customer_party_id party_id,outstanding_amount amount FROM sales_invoices WHERE company_id=? AND is_void=0 AND outstanding_amount>0 AND due_date BETWEEN CURRENT_DATE AND DATE_ADD(CURRENT_DATE,INTERVAL 7 DAY) UNION ALL SELECT 'PAYABLE',invoice_no,due_date,supplier_party_id,outstanding_amount FROM purchase_invoices WHERE company_id=? AND is_void=0 AND outstanding_amount>0 AND due_date BETWEEN CURRENT_DATE AND DATE_ADD(CURRENT_DATE,INTERVAL 7 DAY) ORDER BY 3`,[req.user.companyId,req.user.companyId]);res.json(rows)}));
 app.get('/api/iran/bi/trips',wrap(async(req,res)=>{const [rows]=await pool.execute(`SELECT status,COUNT(*) count,COALESCE(SUM(expected_collection),0) expected_collection,COALESCE(SUM(actual_collection),0) actual_collection FROM trips WHERE company_id=? AND trip_date>=DATE_SUB(CURRENT_DATE,INTERVAL 30 DAY) GROUP BY status ORDER BY status`,[req.user.companyId]);res.json(rows)}));
 app.get('/api/iran/bi/crm-pipeline',wrap(async(req,res)=>{const [rows]=await pool.execute(`SELECT stage,COUNT(*) count,COALESCE(SUM(estimated_value),0) expected_value FROM crm_opportunities WHERE company_id=? AND stage NOT IN ('WON','LOST') GROUP BY stage ORDER BY FIELD(stage,'QUALIFICATION','NEEDS_ANALYSIS','PROPOSAL','NEGOTIATION','DECISION')`,[req.user.companyId]);res.json(rows)}));
 app.get('/api/iran/bi/crm-overdue',wrap(async(req,res)=>{const [rows]=await pool.execute(`SELECT * FROM crm_activities WHERE company_id=? AND COALESCE(next_action_at,scheduled_at)<CURRENT_TIMESTAMP AND status NOT IN ('COMPLETED','CANCELLED') ORDER BY COALESCE(next_action_at,scheduled_at) LIMIT 100`,[req.user.companyId]);res.json(rows)}));
 app.get('/api/iran/bi/control-exceptions',wrap(async(req,res)=>{const [rows]=await pool.execute(`SELECT 'OVERDUE_AR' exception_type,COUNT(*) count,COALESCE(SUM(outstanding_amount),0) amount FROM sales_invoices WHERE company_id=? AND is_void=0 AND outstanding_amount>0 AND due_date<CURRENT_DATE UNION ALL SELECT 'NEGATIVE_STOCK',COUNT(*),0 FROM inventory_balances WHERE company_id=? AND on_hand_qty<0 UNION ALL SELECT 'UNMATCHED_BANK',COUNT(*),0 FROM bank_statement_lines WHERE company_id=? AND match_status='UNMATCHED' UNION ALL SELECT 'FAILED_JOB',COUNT(*),0 FROM background_job_failures WHERE status IN ('FAILED','RETRYING')`,[req.user.companyId,req.user.companyId,req.user.companyId]);res.json(rows)}));
}
