import { pool } from './db.js';
import { requireRole } from './auth.js';
const n=v=>Number(v||0),txt=v=>String(v??'').trim(),obj=v=>{if(!v)return{};if(typeof v==='object')return v;try{return JSON.parse(v)}catch{return{}}};
const fail=(m,s=400,d=null)=>{const e=new Error(m);e.status=s;e.details=d;throw e};
const wrap=fn=>async(req,res)=>{try{await fn(req,res)}catch(e){console.error('campaign v4 error',e);res.status(e.status||400).json({error:e.message,details:e.details||undefined})}};
function channelConsent(channel){return channel==='MULTI'?null:channel}
export function registerCampaignV4Routes(app){
 app.post('/api/iran/crm/campaigns',requireRole('CRM_MANAGER','SALES_MANAGER'),wrap(async(req,res)=>{const b=req.body||{};if(!txt(b.code)||!txt(b.title)||!b.channel||!b.content)fail('کد، عنوان، کانال و محتوا الزامی است.');const [r]=await pool.execute(`INSERT INTO crm_campaigns(company_id,code,title,channel,audience_filter_json,content_json,start_at,end_at,status,created_by) VALUES (?,?,?,?,?,?,?,?,?,?)`,[req.user.companyId,b.code,b.title,b.channel,JSON.stringify(b.audienceFilter||{}),JSON.stringify(b.content),b.startAt||null,b.endAt||null,b.status||'DRAFT',Number(req.user.sub)]);res.status(201).json({id:r.insertId})}));
 app.get('/api/iran/crm/campaigns',requireRole('CRM_MANAGER','SALES_MANAGER'),wrap(async(req,res)=>{const [rows]=await pool.execute(`SELECT c.*,(SELECT COUNT(DISTINCT party_id) FROM campaign_events e WHERE e.campaign_id=c.id AND e.event_type IN ('SENT','DELIVERED','OPENED','CLICKED','REPLIED','CONVERTED')) audience_count,(SELECT COUNT(*) FROM campaign_events e WHERE e.campaign_id=c.id AND e.event_type='CONVERTED') conversions,(SELECT COALESCE(SUM(value_amount),0) FROM campaign_events e WHERE e.campaign_id=c.id AND e.event_type='CONVERTED') conversion_value FROM crm_campaigns c WHERE c.company_id=? ORDER BY c.created_at DESC`,[req.user.companyId]);res.json(rows)}));
 app.post('/api/iran/crm/campaigns/:id/audience',requireRole('CRM_MANAGER','SALES_MANAGER'),wrap(async(req,res)=>{const id=Number(req.params.id),[c]=await pool.execute('SELECT * FROM crm_campaigns WHERE id=? AND company_id=?',[id,req.user.companyId]);if(!c.length)fail('کمپین پیدا نشد.',404);const f=obj(c[0].audience_filter_json),where=['p.company_id=?','p.is_deleted=0','EXISTS(SELECT 1 FROM party_roles pr WHERE pr.party_id=p.id AND pr.role_code=\'CUSTOMER\')'],params=[req.user.companyId];if(Array.isArray(f.partyIds)&&f.partyIds.length){where.push(`p.id IN (${f.partyIds.map(()=>'?').join(',')})`);params.push(...f.partyIds.map(Number))}if(f.city){where.push('p.city=?');params.push(f.city)}if(f.province){where.push('p.province=?');params.push(f.province)}if(f.minSales){where.push('(SELECT COALESCE(SUM(net_total),0) FROM sales_invoices si WHERE si.company_id=p.company_id AND si.customer_party_id=p.id AND si.is_void=0)>=?');params.push(n(f.minSales))}if(f.inactiveDays){where.push('(SELECT MAX(invoice_date) FROM sales_invoices si WHERE si.company_id=p.company_id AND si.customer_party_id=p.id AND si.is_void=0)<DATE_SUB(CURRENT_DATE,INTERVAL ? DAY)');params.push(n(f.inactiveDays))}const cc=channelConsent(c[0].channel);if(cc){where.push(`NOT EXISTS(SELECT 1 FROM contact_consents cs WHERE cs.company_id=p.company_id AND cs.party_id=p.id AND cs.channel=? AND cs.consent_status='OPT_OUT')`);params.push(cc);where.push(`(SELECT COUNT(*) FROM campaign_events ce JOIN crm_campaigns c2 ON c2.id=ce.campaign_id WHERE ce.party_id=p.id AND c2.company_id=p.company_id AND c2.channel=? AND ce.event_type IN ('SENT','DELIVERED') AND ce.event_at>=DATE_SUB(NOW(),INTERVAL 7 DAY)) < COALESCE((SELECT frequency_cap_per_week FROM contact_consents cs2 WHERE cs2.company_id=p.company_id AND cs2.party_id=p.id AND cs2.channel=?),999999)`);params.push(cc,cc)}const [rows]=await pool.execute(`SELECT p.id,p.name,p.mobile,p.email,p.city,p.province FROM parties p WHERE ${where.join(' AND ')} ORDER BY p.name LIMIT 5000`,params);res.json({campaignId:id,count:rows.length,rows})}));
 app.post('/api/iran/crm/campaigns/:id/events',requireRole('CRM_MANAGER','SALES_MANAGER'),wrap(async(req,res)=>{const id=Number(req.params.id),b=req.body||{};if(!b.partyId||!b.eventType)fail('مشتری و نوع رویداد الزامی است.');const [c]=await pool.execute('SELECT id FROM crm_campaigns WHERE id=? AND company_id=?',[id,req.user.companyId]);if(!c.length)fail('کمپین پیدا نشد.',404);const [r]=await pool.execute(`INSERT INTO campaign_events(campaign_id,party_id,event_type,event_at,source_type,source_id,value_amount,details_json) VALUES (?,?,?,COALESCE(?,NOW()),?,?,?,?)`,[id,b.partyId,b.eventType,b.eventAt||null,b.sourceType||null,b.sourceId||null,n(b.valueAmount),JSON.stringify(b.details||{})]);if(b.eventType==='OPTED_OUT'&&b.channel)await pool.execute(`INSERT INTO contact_consents(company_id,party_id,channel,consent_status,consent_date,source,updated_by) VALUES (?,?,?,'OPT_OUT',NOW(),'CAMPAIGN',?) ON DUPLICATE KEY UPDATE consent_status='OPT_OUT',consent_date=NOW(),source='CAMPAIGN',updated_by=VALUES(updated_by)`,[req.user.companyId,b.partyId,b.channel,Number(req.user.sub)]);res.status(201).json({id:r.insertId})}));
 app.get('/api/iran/crm/campaigns/:id/analytics',requireRole('CRM_MANAGER','SALES_MANAGER'),wrap(async(req,res)=>{const id=Number(req.params.id),[rows]=await pool.execute(`SELECT event_type,COUNT(*) count,COUNT(DISTINCT party_id) unique_parties,COALESCE(SUM(value_amount),0) value_amount FROM campaign_events WHERE campaign_id=? GROUP BY event_type`,[id]);const m=Object.fromEntries(rows.map(x=>[x.event_type,x])),sent=n(m.SENT?.unique_parties||m.DELIVERED?.unique_parties),converted=n(m.CONVERTED?.unique_parties),value=n(m.CONVERTED?.value_amount);res.json({events:rows,sent,converted,conversionRate:sent?converted/sent*100:0,conversionValue:value})}));

 app.post('/api/iran/crm/surveys',requireRole('CRM_MANAGER','CUSTOMER_SERVICE'),wrap(async(req,res)=>{const b=req.body||{};if(!b.surveyType||!txt(b.title))fail('نوع و عنوان نظرسنجی الزامی است.');const [r]=await pool.execute(`INSERT INTO customer_surveys(company_id,survey_type,title,schema_json,is_active,created_by) VALUES (?,?,?,?,1,?)`,[req.user.companyId,b.surveyType,b.title,JSON.stringify(b.schema||{}),Number(req.user.sub)]);res.status(201).json({id:r.insertId})}));
 app.post('/api/iran/crm/surveys/:id/respond',wrap(async(req,res)=>{const id=Number(req.params.id),b=req.body||{},[s]=await pool.execute('SELECT * FROM customer_surveys WHERE id=? AND company_id=? AND is_active=1',[id,req.user.companyId]);if(!s.length)fail('نظرسنجی فعال پیدا نشد.',404);if(s[0].survey_type==='NPS'&&(n(b.score)<0||n(b.score)>10))fail('امتیاز NPS باید بین صفر و ۱۰ باشد.');if(s[0].survey_type==='CSAT'&&(n(b.score)<1||n(b.score)>5))fail('امتیاز رضایت باید بین ۱ و ۵ باشد.');const [r]=await pool.execute(`INSERT INTO customer_survey_responses(survey_id,party_id,score,response_json,source_type,source_id) VALUES (?,?,?,?,?,?)`,[id,b.partyId||null,b.score??null,JSON.stringify(b.response||{}),b.sourceType||null,b.sourceId||null]);res.status(201).json({id:r.insertId})}));
 app.get('/api/iran/crm/surveys/:id/results',requireRole('CRM_MANAGER','CUSTOMER_SERVICE'),wrap(async(req,res)=>{const id=Number(req.params.id),[s]=await pool.execute('SELECT * FROM customer_surveys WHERE id=? AND company_id=?',[id,req.user.companyId]);if(!s.length)fail('نظرسنجی پیدا نشد.',404);const [[a]]=await pool.execute(`SELECT COUNT(*) responses,AVG(score) avg_score,SUM(score>=9) promoters,SUM(score BETWEEN 7 AND 8) passives,SUM(score<=6) detractors FROM customer_survey_responses WHERE survey_id=?`,[id]);const total=n(a.responses),nps=s[0].survey_type==='NPS'&&total?((n(a.promoters)-n(a.detractors))/total*100):null;res.json({survey:s[0],responses:total,averageScore:n(a.avg_score),nps,promoters:n(a.promoters),passives:n(a.passives),detractors:n(a.detractors)})}));
}
