import { pool, withTransaction } from './db.js';
import { requireRole } from './auth.js';

const n=v=>Number(v||0), txt=v=>String(v??'').trim();
const fail=(m,s=400,d=null)=>{const e=new Error(m);e.status=s;e.details=d;throw e};
const wrap=fn=>async(req,res)=>{try{await fn(req,res)}catch(e){console.error('commercial v8 error',e);res.status(e.status||400).json({error:e.message,details:e.details||undefined})}};
const roles=['SUPER_ADMIN','FINANCE_MANAGER','ACCOUNTANT','SALES_MANAGER','WAREHOUSE_MANAGER','LOGISTICS_MANAGER','PURCHASE_MANAGER'];
const canRead=requireRole(...roles);
const canMaster=requireRole('SUPER_ADMIN','FINANCE_MANAGER','SALES_MANAGER','WAREHOUSE_MANAGER','PURCHASE_MANAGER');
const canLogistics=requireRole('SUPER_ADMIN','LOGISTICS_MANAGER','WAREHOUSE_MANAGER','SALES_MANAGER');

async function audit(req,action,type,id,payload){
  try{await pool.execute(`INSERT INTO audit_logs(company_id,user_id,action,entity_type,entity_id,after_json,ip_address,user_agent) VALUES (?,?,?,?,?,?,?,?)`,[req.user.companyId,Number(req.user.sub),action,type,String(id||''),JSON.stringify(payload||{}),req.ip,req.headers['user-agent']||null])}catch{}
}

async function nextNo(conn,companyId,type,prefix){
  const lock=`trz:v8:${companyId}:${type}`;
  const [[g]]=await conn.query('SELECT GET_LOCK(?,5) got',[lock]); if(!g?.got)fail('شماره‌گذاری موقتاً درگیر است.',409);
  try{
    let [r]=await conn.execute(`SELECT id,last_number,prefix,pad_length FROM document_sequences WHERE company_id=? AND branch_id IS NULL AND fiscal_year_id IS NULL AND document_type=? ORDER BY id LIMIT 1 FOR UPDATE`,[companyId,type]);
    if(!r.length){await conn.execute(`INSERT INTO document_sequences(company_id,document_type,prefix,last_number,pad_length) VALUES (?,?,?,0,6)`,[companyId,type,prefix]);[r]=await conn.execute(`SELECT id,last_number,prefix,pad_length FROM document_sequences WHERE company_id=? AND branch_id IS NULL AND fiscal_year_id IS NULL AND document_type=? ORDER BY id LIMIT 1 FOR UPDATE`,[companyId,type])}
    const x=r[0],v=n(x.last_number)+1;await conn.execute('UPDATE document_sequences SET last_number=? WHERE id=?',[v,x.id]);return `${x.prefix||prefix}-${String(v).padStart(Number(x.pad_length||6),'0')}`;
  } finally {await conn.query('SELECT RELEASE_LOCK(?)',[lock])}
}

function range(req){const from=txt(req.query.from)||'1900-01-01',to=txt(req.query.to)||'2999-12-31';return{from,to}}

export function registerCommercialMasterV8Routes(app){
  // Product group tree and media
  app.get('/api/iran/master/product-groups',canRead,wrap(async(req,res)=>{const [r]=await pool.execute(`SELECT g.*,COUNT(m.product_id) product_count FROM product_groups g LEFT JOIN product_group_members m ON m.group_id=g.id WHERE g.company_id=? GROUP BY g.id ORDER BY COALESCE(g.parent_id,0),g.sort_order,g.title`,[req.user.companyId]);res.json(r)}));
  app.post('/api/iran/master/product-groups',canMaster,wrap(async(req,res)=>{const b=req.body||{};if(!txt(b.code)||!txt(b.title))fail('کد و عنوان گروه کالا الزامی است.');const [r]=await pool.execute(`INSERT INTO product_groups(company_id,parent_id,code,title,sort_order) VALUES (?,?,?,?,?)`,[req.user.companyId,b.parentId||null,txt(b.code),txt(b.title),n(b.sortOrder)]);await audit(req,'CREATE','PRODUCT_GROUP',r.insertId,b);res.status(201).json({id:r.insertId})}));
  app.put('/api/iran/master/products/:id/classification',canMaster,wrap(async(req,res)=>{const id=Number(req.params.id),b=req.body||{};await withTransaction(async conn=>{const [p]=await conn.execute('SELECT id FROM products WHERE id=? AND company_id=?',[id,req.user.companyId]);if(!p.length)fail('کالا پیدا نشد.',404);if(b.groupIds){await conn.execute('DELETE FROM product_group_members WHERE product_id=?',[id]);for(const gid of b.groupIds)await conn.execute('INSERT INTO product_group_members(product_id,group_id,is_primary) VALUES (?,?,?)',[id,Number(gid),Number(gid)===Number(b.primaryGroupId)?1:0])}if(b.imageUrl){if(b.makePrimary!==false)await conn.execute('UPDATE product_media SET is_primary=0 WHERE product_id=?',[id]);await conn.execute(`INSERT INTO product_media(company_id,product_id,media_type,media_url,caption,is_primary,sort_order) VALUES (?,?,'IMAGE',?,?,?,?)`,[req.user.companyId,id,txt(b.imageUrl),txt(b.caption)||null,b.makePrimary===false?0:1,n(b.sortOrder)])}});await audit(req,'UPDATE_CLASSIFICATION','PRODUCT',id,b);res.json({ok:true})}));
  app.get('/api/iran/master/products/:id/profile',canRead,wrap(async(req,res)=>{const id=Number(req.params.id);const [[p]]=await pool.execute(`SELECT p.*,(SELECT media_url FROM product_media pm WHERE pm.product_id=p.id AND pm.media_type='IMAGE' ORDER BY pm.is_primary DESC,pm.sort_order,pm.id LIMIT 1) image_url FROM products p WHERE p.id=? AND p.company_id=?`,[id,req.user.companyId]);if(!p)fail('کالا پیدا نشد.',404);const [groups]=await pool.execute(`SELECT g.id,g.code,g.title,m.is_primary FROM product_group_members m JOIN product_groups g ON g.id=m.group_id WHERE m.product_id=? ORDER BY m.is_primary DESC,g.title`,[id]);const [media]=await pool.execute(`SELECT * FROM product_media WHERE product_id=? ORDER BY is_primary DESC,sort_order,id`,[id]);res.json({product:p,groups,media})}));

  // Party group tree, multiple contacts/addresses/banks
  app.get('/api/iran/master/party-groups',canRead,wrap(async(req,res)=>{const [r]=await pool.execute(`SELECT g.*,COUNT(m.party_id) party_count FROM party_groups g LEFT JOIN party_group_members m ON m.group_id=g.id WHERE g.company_id=? GROUP BY g.id ORDER BY COALESCE(g.parent_id,0),g.sort_order,g.title`,[req.user.companyId]);res.json(r)}));
  app.post('/api/iran/master/party-groups',canMaster,wrap(async(req,res)=>{const b=req.body||{};if(!txt(b.code)||!txt(b.title))fail('کد و عنوان گروه اشخاص الزامی است.');const [r]=await pool.execute(`INSERT INTO party_groups(company_id,parent_id,code,title,sort_order) VALUES (?,?,?,?,?)`,[req.user.companyId,b.parentId||null,txt(b.code),txt(b.title),n(b.sortOrder)]);await audit(req,'CREATE','PARTY_GROUP',r.insertId,b);res.status(201).json({id:r.insertId})}));
  app.get('/api/iran/master/parties/:id/profile',canRead,wrap(async(req,res)=>{const id=Number(req.params.id);const [[p]]=await pool.execute(`SELECT p.*,cp.credit_limit,cp.payment_terms_days,cp.discount_limit_pct,sp.performance_score FROM parties p LEFT JOIN customer_profiles cp ON cp.party_id=p.id LEFT JOIN supplier_profiles sp ON sp.party_id=p.id WHERE p.id=? AND p.company_id=?`,[id,req.user.companyId]);if(!p)fail('شخص پیدا نشد.',404);const [rolesR]=await pool.execute('SELECT role_code FROM party_roles WHERE party_id=?',[id]);const [groups]=await pool.execute(`SELECT g.id,g.code,g.title FROM party_group_members m JOIN party_groups g ON g.id=m.group_id WHERE m.party_id=? ORDER BY g.title`,[id]);const [contacts]=await pool.execute('SELECT * FROM party_contacts WHERE party_id=? ORDER BY is_primary DESC,id',[id]);const [addresses]=await pool.execute('SELECT * FROM party_addresses WHERE party_id=? ORDER BY is_primary DESC,id',[id]);const [banks]=await pool.execute('SELECT id,bank_name,branch_name,branch_code,account_type,account_no,card_no,iban,account_holder,is_primary,is_active FROM party_bank_accounts WHERE party_id=? ORDER BY is_primary DESC,id',[id]);res.json({party:p,roles:rolesR.map(x=>x.role_code),groups,contacts,addresses,banks})}));
  app.put('/api/iran/master/parties/:id/details',canMaster,wrap(async(req,res)=>{const id=Number(req.params.id),b=req.body||{};await withTransaction(async conn=>{const [p]=await conn.execute('SELECT id FROM parties WHERE id=? AND company_id=?',[id,req.user.companyId]);if(!p.length)fail('شخص پیدا نشد.',404);if(Array.isArray(b.groupIds)){await conn.execute('DELETE FROM party_group_members WHERE party_id=?',[id]);for(const gid of b.groupIds)await conn.execute('INSERT INTO party_group_members(party_id,group_id) VALUES (?,?)',[id,Number(gid)])}if(Array.isArray(b.contacts)){await conn.execute('DELETE FROM party_contacts WHERE party_id=?',[id]);for(const x of b.contacts)if(txt(x.value))await conn.execute(`INSERT INTO party_contacts(company_id,party_id,contact_type,title,contact_value,is_primary) VALUES (?,?,?,?,?,?)`,[req.user.companyId,id,x.type||'OTHER',txt(x.title)||null,txt(x.value),x.isPrimary?1:0])}if(Array.isArray(b.addresses)){await conn.execute('DELETE FROM party_addresses WHERE party_id=?',[id]);for(const x of b.addresses)if(txt(x.address))await conn.execute(`INSERT INTO party_addresses(company_id,party_id,address_type,title,province,city,postal_code,address_text,latitude,longitude,is_primary) VALUES (?,?,?,?,?,?,?,?,?,?,?)`,[req.user.companyId,id,x.type||'MAIN',txt(x.title)||null,txt(x.province)||null,txt(x.city)||null,txt(x.postalCode)||null,txt(x.address),x.latitude||null,x.longitude||null,x.isPrimary?1:0])}if(Array.isArray(b.banks)){await conn.execute('DELETE FROM party_bank_accounts WHERE party_id=?',[id]);for(const x of b.banks)if(txt(x.bankName))await conn.execute(`INSERT INTO party_bank_accounts(company_id,party_id,bank_name,branch_name,branch_code,account_type,account_no,card_no,iban,account_holder,is_primary) VALUES (?,?,?,?,?,?,?,?,?,?,?)`,[req.user.companyId,id,txt(x.bankName),txt(x.branchName)||null,txt(x.branchCode)||null,txt(x.accountType)||null,txt(x.accountNo)||null,txt(x.cardNo)||null,txt(x.iban)||null,txt(x.accountHolder)||null,x.isPrimary?1:0])}});await audit(req,'UPDATE_DETAILS','PARTY',id,b);res.json({ok:true})}));

  // Versioned price lists with image-aware items
  app.get('/api/iran/commercial/price-lists',canRead,wrap(async(req,res)=>{const [r]=await pool.execute(`SELECT pl.*,COUNT(i.id) item_count FROM price_lists pl LEFT JOIN price_list_items i ON i.price_list_id=pl.id WHERE pl.company_id=? GROUP BY pl.id ORDER BY pl.created_at DESC`,[req.user.companyId]);res.json(r)}));
  app.post('/api/iran/commercial/price-lists',canMaster,wrap(async(req,res)=>{const b=req.body||{},result=await withTransaction(async conn=>{const code=txt(b.code)||await nextNo(conn,req.user.companyId,'PRICE_LIST','PL');const [h]=await conn.execute(`INSERT INTO price_lists(company_id,code,title,valid_from,valid_to,currency_code,audience,party_group_id,party_id,status,notes,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`,[req.user.companyId,code,txt(b.title)||'لیست قیمت',b.validFrom||null,b.validTo||null,b.currencyCode||'IRR',b.audience||'PUBLIC',b.partyGroupId||null,b.partyId||null,b.status||'DRAFT',txt(b.notes)||null,Number(req.user.sub)]);for(const x of b.items||[])await conn.execute(`INSERT INTO price_list_items(price_list_id,product_id,unit_price,min_qty,max_discount_pct) VALUES (?,?,?,?,?)`,[h.insertId,Number(x.productId),n(x.unitPrice),n(x.minQty),n(x.maxDiscountPct)]);return{id:h.insertId,code}});await audit(req,'CREATE','PRICE_LIST',result.id,b);res.status(201).json(result)}));
  app.get('/api/iran/commercial/price-lists/:id',canRead,wrap(async(req,res)=>{const id=Number(req.params.id);const [[h]]=await pool.execute('SELECT * FROM price_lists WHERE id=? AND company_id=?',[id,req.user.companyId]);if(!h)fail('لیست قیمت پیدا نشد.',404);const [items]=await pool.execute(`SELECT i.*,p.sku,p.name,p.unit,p.brand,(SELECT media_url FROM product_media pm WHERE pm.product_id=p.id AND pm.media_type='IMAGE' ORDER BY pm.is_primary DESC,pm.sort_order,pm.id LIMIT 1) image_url FROM price_list_items i JOIN products p ON p.id=i.product_id WHERE i.price_list_id=? AND i.is_active=1 ORDER BY p.category,p.brand,p.name`,[id]);res.json({header:h,items})}));
  app.post('/api/iran/commercial/price-lists/:id/activate',canMaster,wrap(async(req,res)=>{const id=Number(req.params.id);const [r]=await pool.execute(`UPDATE price_lists SET status='ACTIVE' WHERE id=? AND company_id=? AND status IN ('DRAFT','EXPIRED')`,[id,req.user.companyId]);if(!r.affectedRows)fail('لیست قیمت قابل فعال‌سازی نیست.',422);await audit(req,'ACTIVATE','PRICE_LIST',id,{});res.json({ok:true})}));

  // Logistics waybill as a first-class document
  app.get('/api/iran/logistics/waybills',canRead,wrap(async(req,res)=>{const [r]=await pool.execute(`SELECT w.*,si.invoice_no,rp.name receiver_name_party,t.trip_no FROM logistics_waybills w LEFT JOIN sales_invoices si ON si.id=w.sales_invoice_id LEFT JOIN parties rp ON rp.id=w.receiver_party_id LEFT JOIN trips t ON t.id=w.trip_id WHERE w.company_id=? ORDER BY w.issue_date DESC,w.id DESC LIMIT 500`,[req.user.companyId]);res.json(r)}));
  app.post('/api/iran/logistics/waybills',canLogistics,wrap(async(req,res)=>{const b=req.body||{},result=await withTransaction(async conn=>{const no=txt(b.waybillNo)||await nextNo(conn,req.user.companyId,'WAYBILL','WB');let receiver=b.receiverPartyId||null;if(!receiver&&b.salesInvoiceId){const [[iv]]=await conn.execute('SELECT customer_party_id FROM sales_invoices WHERE id=? AND company_id=?',[Number(b.salesInvoiceId),req.user.companyId]);receiver=iv?.customer_party_id||null}const [r]=await conn.execute(`INSERT INTO logistics_waybills(company_id,waybill_no,issue_date,trip_id,trip_stop_id,sales_invoice_id,sender_party_id,receiver_party_id,carrier_name,tracking_no,origin_text,destination_text,package_count,gross_weight,net_weight,freight_amount,insurance_amount,other_charges,payment_method,description,receiver_name,receiver_phone,status,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[req.user.companyId,no,b.issueDate||new Date().toISOString().slice(0,10),b.tripId||null,b.tripStopId||null,b.salesInvoiceId||null,b.senderPartyId||null,receiver,txt(b.carrierName)||null,txt(b.trackingNo)||null,txt(b.origin)||null,txt(b.destination)||null,n(b.packageCount),n(b.grossWeight),n(b.netWeight),n(b.freightAmount),n(b.insuranceAmount),n(b.otherCharges),b.paymentMethod||'PREPAID',txt(b.description)||null,txt(b.receiverName)||null,txt(b.receiverPhone)||null,b.status||'ISSUED',Number(req.user.sub)]);return{id:r.insertId,waybillNo:no}});await audit(req,'CREATE','WAYBILL',result.id,b);res.status(201).json(result)}));
  app.get('/api/iran/logistics/waybills/:id/print-model',canRead,wrap(async(req,res)=>{const id=Number(req.params.id);const [[w]]=await pool.execute(`SELECT w.*,c.name company_name,si.invoice_no,rp.name receiver_party,sp.name sender_party,t.trip_no,v.plate_no FROM logistics_waybills w JOIN companies c ON c.id=w.company_id LEFT JOIN sales_invoices si ON si.id=w.sales_invoice_id LEFT JOIN parties rp ON rp.id=w.receiver_party_id LEFT JOIN parties sp ON sp.id=w.sender_party_id LEFT JOIN trips t ON t.id=w.trip_id LEFT JOIN vehicles v ON v.id=t.vehicle_id WHERE w.id=? AND w.company_id=?`,[id,req.user.companyId]);if(!w)fail('بارنامه پیدا نشد.',404);let lines=[];if(w.sales_invoice_id){[lines]=await pool.execute(`SELECT p.sku,p.name,p.unit,l.qty,l.unit_price,l.line_total FROM sales_invoice_lines l JOIN products p ON p.id=l.product_id WHERE l.invoice_id=? ORDER BY l.id`,[w.sales_invoice_id])}res.json({waybill:w,lines})}));

  // Print-ready invoice model
  app.get('/api/iran/sales-invoices/:id/print-model',canRead,wrap(async(req,res)=>{const id=Number(req.params.id);const [[h]]=await pool.execute(`SELECT si.*,c.name company_name,p.code customer_code,p.name customer_name,p.national_id,p.economic_code,p.mobile,p.phone,p.address FROM sales_invoices si JOIN companies c ON c.id=si.company_id JOIN parties p ON p.id=si.customer_party_id WHERE si.id=? AND si.company_id=?`,[id,req.user.companyId]);if(!h)fail('فاکتور پیدا نشد.',404);const [lines]=await pool.execute(`SELECT l.*,p.sku,p.barcode,p.name,p.unit,p.brand FROM sales_invoice_lines l JOIN products p ON p.id=l.product_id WHERE l.invoice_id=? ORDER BY l.id`,[id]);const [addresses]=await pool.execute(`SELECT * FROM party_addresses WHERE party_id=? AND is_active=1 ORDER BY is_primary DESC,id LIMIT 5`,[h.customer_party_id]);res.json({header:h,lines,addresses})}));

  // Product profitability dashboard and drill-down
  app.get('/api/iran/commercial/product-profitability',canRead,wrap(async(req,res)=>{const {from,to}=range(req);const [r]=await pool.execute(`SELECT p.id product_id,p.sku,p.name,p.unit,
    COALESCE(b.buy_qty,0) buy_qty,COALESCE(b.buy_amount,0) buy_amount,CASE WHEN COALESCE(b.buy_qty,0)=0 THEN 0 ELSE b.buy_amount/b.buy_qty END buy_avg,
    COALESCE(s.sale_qty,0) sale_qty,COALESCE(s.sale_amount,0) sale_amount,CASE WHEN COALESCE(s.sale_qty,0)=0 THEN 0 ELSE s.sale_amount/s.sale_qty END sale_avg,
    COALESCE(c.cogs,0) cogs,COALESCE(s.sale_amount,0)-COALESCE(c.cogs,0) gross_profit,
    CASE WHEN COALESCE(s.sale_qty,0)>COALESCE(b.buy_qty,0)+0.0001 THEN 'EXCESS_SALES' WHEN COALESCE(b.buy_qty,0)>COALESCE(s.sale_qty,0)+0.0001 THEN 'REMAINING' ELSE 'SETTLED' END movement_status,
    COALESCE(b.buy_qty,0)-COALESCE(s.sale_qty,0) qty_difference
  FROM products p
  LEFT JOIN (SELECT l.product_id,SUM(l.qty) buy_qty,SUM(l.line_total) buy_amount FROM purchase_invoice_lines l JOIN purchase_invoices h ON h.id=l.invoice_id WHERE h.company_id=? AND h.invoice_date BETWEEN ? AND ? AND h.status<>'VOID' GROUP BY l.product_id) b ON b.product_id=p.id
  LEFT JOIN (SELECT l.product_id,SUM(l.qty) sale_qty,SUM(l.line_total) sale_amount FROM sales_invoice_lines l JOIN sales_invoices h ON h.id=l.invoice_id WHERE h.company_id=? AND h.invoice_date BETWEEN ? AND ? AND h.status NOT IN ('CANCELLED','RETURNED') GROUP BY l.product_id) s ON s.product_id=p.id
  LEFT JOIN (SELECT fl.product_id,SUM(fl.actual_cost_amount) cogs FROM sales_fulfillment_lines fl JOIN sales_fulfillments f ON f.id=fl.fulfillment_id JOIN sales_invoices h ON h.id=f.sales_invoice_id WHERE f.company_id=? AND h.invoice_date BETWEEN ? AND ? AND f.status NOT IN ('CANCELLED','RETURNED') GROUP BY fl.product_id) c ON c.product_id=p.id
  WHERE p.company_id=? AND p.is_deleted=0 AND (COALESCE(b.buy_qty,0)<>0 OR COALESCE(s.sale_qty,0)<>0)
  ORDER BY gross_profit DESC,p.name`,[req.user.companyId,from,to,req.user.companyId,from,to,req.user.companyId,from,to,req.user.companyId]);res.json({from,to,rows:r,summary:{itemCount:r.length,buyTotal:r.reduce((a,x)=>a+n(x.buy_amount),0),salesTotal:r.reduce((a,x)=>a+n(x.sale_amount),0),grossProfit:r.reduce((a,x)=>a+n(x.gross_profit),0)}})}));
  app.get('/api/iran/commercial/product-profitability/:id/details',canRead,wrap(async(req,res)=>{const id=Number(req.params.id),{from,to}=range(req);const [purchases]=await pool.execute(`SELECT h.invoice_date,h.invoice_no,l.qty,l.unit_price,l.line_total,sp.name supplier FROM purchase_invoice_lines l JOIN purchase_invoices h ON h.id=l.invoice_id JOIN parties sp ON sp.id=h.supplier_party_id WHERE h.company_id=? AND l.product_id=? AND h.invoice_date BETWEEN ? AND ? AND h.status<>'VOID' ORDER BY h.invoice_date,h.id`,[req.user.companyId,id,from,to]);const [sales]=await pool.execute(`SELECT h.invoice_date,h.invoice_no,l.qty,l.unit_price,l.line_total,cp.name customer FROM sales_invoice_lines l JOIN sales_invoices h ON h.id=l.invoice_id JOIN parties cp ON cp.id=h.customer_party_id WHERE h.company_id=? AND l.product_id=? AND h.invoice_date BETWEEN ? AND ? AND h.status NOT IN ('CANCELLED','RETURNED') ORDER BY h.invoice_date,h.id`,[req.user.companyId,id,from,to]);res.json({purchases,sales})}));

  // Print profile catalog
  app.get('/api/iran/system/print-profiles',canRead,wrap(async(req,res)=>{const [r]=await pool.execute('SELECT * FROM print_profiles WHERE company_id=? AND is_active=1 ORDER BY document_type,is_default DESC,title',[req.user.companyId]);res.json(r)}));
  app.post('/api/iran/system/print-profiles',requireRole('SUPER_ADMIN','FINANCE_MANAGER'),wrap(async(req,res)=>{const b=req.body||{};if(!txt(b.code)||!txt(b.title)||!txt(b.documentType))fail('نوع سند، کد و عنوان الزامی است.');if(b.isDefault)await pool.execute('UPDATE print_profiles SET is_default=0 WHERE company_id=? AND document_type=?',[req.user.companyId,b.documentType]);const [r]=await pool.execute(`INSERT INTO print_profiles(company_id,document_type,code,title,paper_size,orientation,template_json,is_default) VALUES (?,?,?,?,?,?,?,?)`,[req.user.companyId,b.documentType,txt(b.code),txt(b.title),b.paperSize||'A4',b.orientation||'PORTRAIT',JSON.stringify(b.template||{}),b.isDefault?1:0]);res.status(201).json({id:r.insertId})}));
}
