import { pool, withTransaction } from './db.js';
import { requireRole } from './auth.js';
const txt=v=>String(v??'').trim(),n=v=>Number(v||0);const fail=(m,s=400)=>{const e=new Error(m);e.status=s;throw e};const wrap=fn=>async(req,res)=>{try{await fn(req,res)}catch(e){console.error('commercial compat v8',e);res.status(e.status||400).json({error:e.message})}};
const read=requireRole('SUPER_ADMIN','FINANCE_MANAGER','ACCOUNTANT','SALES_MANAGER','WAREHOUSE_MANAGER','PURCHASE_MANAGER','LOGISTICS_MANAGER');
const master=requireRole('SUPER_ADMIN','FINANCE_MANAGER','SALES_MANAGER','WAREHOUSE_MANAGER','PURCHASE_MANAGER');

export function registerCommercialCompatV8Routes(app){
  // Authoritative compatible party profile over the original 007 master-data schema.
  app.get('/api/iran/master/parties/:id/profile',read,wrap(async(req,res)=>{const id=Number(req.params.id);const [[p]]=await pool.execute(`SELECT p.*,cp.credit_limit,cp.payment_terms_days,cp.discount_limit_pct,sp.performance_score FROM parties p LEFT JOIN customer_profiles cp ON cp.party_id=p.id LEFT JOIN supplier_profiles sp ON sp.party_id=p.id WHERE p.id=? AND p.company_id=?`,[id,req.user.companyId]);if(!p)fail('شخص پیدا نشد.',404);const [roles]=await pool.execute('SELECT role_code FROM party_roles WHERE party_id=?',[id]);const [groups]=await pool.execute(`SELECT g.id,g.code,g.title FROM party_group_members m JOIN party_groups g ON g.id=m.group_id WHERE m.party_id=? ORDER BY g.title`,[id]);const [contacts]=await pool.execute(`SELECT id,full_name,job_title,mobile,phone,email,is_primary,notes FROM party_contacts WHERE party_id=? ORDER BY is_primary DESC,id`,[id]);const [addresses]=await pool.execute(`SELECT id,address_type,title,province,city,address,postal_code,phone,is_default,latitude,longitude FROM party_addresses WHERE party_id=? ORDER BY is_default DESC,id`,[id]);const [banks]=await pool.execute(`SELECT id,bank_name,branch_name,branch_code,account_type,account_no,card_no,iban,account_holder,is_default,verification_status FROM party_bank_accounts WHERE party_id=? ORDER BY is_default DESC,id`,[id]);res.json({party:p,roles:roles.map(x=>x.role_code),groups,contacts,addresses,banks})}));

  app.put('/api/iran/master/parties/:id/details',master,wrap(async(req,res)=>{const id=Number(req.params.id),b=req.body||{};await withTransaction(async conn=>{const [p]=await conn.execute('SELECT id FROM parties WHERE id=? AND company_id=? FOR UPDATE',[id,req.user.companyId]);if(!p.length)fail('شخص پیدا نشد.',404);if(Array.isArray(b.groupIds)){await conn.execute('DELETE FROM party_group_members WHERE party_id=?',[id]);for(const gid of b.groupIds)await conn.execute('INSERT INTO party_group_members(party_id,group_id) VALUES (?,?)',[id,Number(gid)])}if(Array.isArray(b.contacts)){await conn.execute('DELETE FROM party_contacts WHERE party_id=?',[id]);for(const x of b.contacts){const value=txt(x.value);if(!value)continue;const type=x.type||'OTHER',mobile=type==='MOBILE'||type==='WHATSAPP'?value:null,phone=type==='PHONE'||type==='FAX'?value:null,email=type==='EMAIL'?value:null;await conn.execute(`INSERT INTO party_contacts(party_id,full_name,job_title,mobile,phone,email,is_primary,notes) VALUES (?,?,?,?,?,?,?,?)`,[id,txt(x.title)||({MOBILE:'موبایل',WHATSAPP:'واتساپ',PHONE:'تلفن',FAX:'فکس',EMAIL:'ایمیل'}[type]||'راه ارتباطی'),txt(x.jobTitle)||null,mobile,phone,email,x.isPrimary?1:0,type==='WHATSAPP'?'واتساپ':null])}}if(Array.isArray(b.addresses)){await conn.execute('DELETE FROM party_addresses WHERE party_id=?',[id]);for(const x of b.addresses)if(txt(x.address))await conn.execute(`INSERT INTO party_addresses(party_id,address_type,title,province,city,address,postal_code,phone,is_default,latitude,longitude) VALUES (?,?,?,?,?,?,?,?,?,?,?)`,[id,x.type||'MAIN',txt(x.title)||null,txt(x.province)||null,txt(x.city)||null,txt(x.address),txt(x.postalCode)||null,txt(x.phone)||null,x.isPrimary?1:0,x.latitude||null,x.longitude||null])}if(Array.isArray(b.banks)){await conn.execute('DELETE FROM party_bank_accounts WHERE party_id=?',[id]);for(const x of b.banks)if(txt(x.bankName))await conn.execute(`INSERT INTO party_bank_accounts(party_id,bank_name,branch_name,branch_code,account_type,account_no,iban,card_no,account_holder,is_default,verification_status) VALUES (?,?,?,?,?,?,?,?,?,?,?)`,[id,txt(x.bankName),txt(x.branchName)||null,txt(x.branchCode)||null,txt(x.accountType)||null,txt(x.accountNo)||null,txt(x.iban)||null,txt(x.cardNo)||null,txt(x.accountHolder)||null,x.isPrimary?1:0,x.verificationStatus||'UNVERIFIED'])}});res.json({ok:true})}));

  // Services remain products with product_type=SERVICE, ensuring invoice/tax/accounting integration.
  app.get('/api/iran/master/services',read,wrap(async(req,res)=>{const q=`%${txt(req.query.q)}%`;const [rows]=await pool.execute(`SELECT p.id,p.sku code,p.name,p.unit,p.sale_price,p.goods_service_id,p.unit_code,p.vat_status,p.default_vat_rate,p.is_active,sp.commission_pct,sp.revenue_account_id,a.code revenue_account_code,a.title revenue_account_title,sp.estimated_duration_minutes,sp.service_notes FROM products p LEFT JOIN service_profiles sp ON sp.product_id=p.id LEFT JOIN accounts a ON a.id=sp.revenue_account_id WHERE p.company_id=? AND p.is_deleted=0 AND p.product_type='SERVICE' AND (?='%%' OR p.name LIKE ? OR p.sku LIKE ?) ORDER BY p.name`,[req.user.companyId,q,q,q]);res.json(rows)}));

  app.post('/api/iran/master/services',master,wrap(async(req,res)=>{const b=req.body||{};if(!txt(b.code)||!txt(b.name))fail('کد و نام خدمت الزامی است.');const id=await withTransaction(async conn=>{const [r]=await conn.execute(`INSERT INTO products(company_id,sku,name,unit,sale_price,goods_service_id,unit_code,vat_status,default_vat_rate,purchase_price,product_type,is_active) VALUES (?,?,?,?,?,?,?,?,?,0,'SERVICE',1)`,[req.user.companyId,txt(b.code),txt(b.name),txt(b.unit)||'عدد',n(b.salePrice),txt(b.goodsServiceId)||null,txt(b.unitCode)||null,b.vatStatus||'STANDARD',b.defaultVatRate==null?null:n(b.defaultVatRate)]);await conn.execute(`INSERT INTO service_profiles(product_id,commission_pct,revenue_account_id,estimated_duration_minutes,service_notes) VALUES (?,?,?,?,?)`,[r.insertId,n(b.commissionPct),b.revenueAccountId||null,b.durationMinutes==null?null:Number(b.durationMinutes),txt(b.notes)||null]);if(b.groupId)await conn.execute('INSERT INTO product_group_members(product_id,group_id,is_primary) VALUES (?,?,1)',[r.insertId,Number(b.groupId)]);return r.insertId});res.status(201).json({id})}));

  app.put('/api/iran/master/services/:id',master,wrap(async(req,res)=>{const id=Number(req.params.id),b=req.body||{};await withTransaction(async conn=>{const [p]=await conn.execute("SELECT id FROM products WHERE id=? AND company_id=? AND product_type='SERVICE' FOR UPDATE",[id,req.user.companyId]);if(!p.length)fail('خدمت پیدا نشد.',404);await conn.execute(`UPDATE products SET name=COALESCE(?,name),unit=COALESCE(?,unit),sale_price=COALESCE(?,sale_price),goods_service_id=COALESCE(?,goods_service_id),unit_code=COALESCE(?,unit_code),vat_status=COALESCE(?,vat_status),default_vat_rate=COALESCE(?,default_vat_rate),is_active=COALESCE(?,is_active) WHERE id=?`,[b.name??null,b.unit??null,b.salePrice==null?null:n(b.salePrice),b.goodsServiceId??null,b.unitCode??null,b.vatStatus??null,b.defaultVatRate==null?null:n(b.defaultVatRate),b.isActive==null?null:(b.isActive?1:0),id]);await conn.execute(`INSERT INTO service_profiles(product_id,commission_pct,revenue_account_id,estimated_duration_minutes,service_notes) VALUES (?,?,?,?,?) ON DUPLICATE KEY UPDATE commission_pct=VALUES(commission_pct),revenue_account_id=VALUES(revenue_account_id),estimated_duration_minutes=VALUES(estimated_duration_minutes),service_notes=VALUES(service_notes)`,[id,n(b.commissionPct),b.revenueAccountId||null,b.durationMinutes==null?null:Number(b.durationMinutes),txt(b.notes)||null])});res.json({ok:true})}));
}
