import crypto from 'node:crypto';
import { pool } from './db.js';
import { requireRole } from './auth.js';
const n=v=>Number(v||0),fail=(m,s=400,d=null)=>{const e=new Error(m);e.status=s;e.details=d;throw e},wrap=fn=>async(req,res)=>{try{await fn(req,res)}catch(e){console.error('compliance control v7',e);res.status(e.status||400).json({error:e.message,details:e.details||undefined})}};
const pf=new Intl.DateTimeFormat('en-US-u-ca-persian',{year:'numeric',month:'numeric',day:'numeric',timeZone:'UTC'});const pp=d=>Object.fromEntries(pf.formatToParts(new Date(`${String(d).slice(0,10)}T00:00:00Z`)).filter(x=>x.type!=='literal').map(x=>[x.type,Number(x.value)]));
async function currentHash(c,p){let data;if(p.code==='IR_VAT'){const [[x]]=await pool.execute(`SELECT (SELECT COALESCE(SUM(tax_total),0) FROM sales_invoices WHERE company_id=? AND invoice_classification='OFFICIAL' AND is_void=0 AND posted_at IS NOT NULL AND invoice_date BETWEEN ? AND ?) output_tax,(SELECT COALESCE(SUM(tax_total),0) FROM purchase_invoices WHERE company_id=? AND invoice_classification='OFFICIAL' AND is_void=0 AND status='POSTED' AND invoice_date BETWEEN ? AND ?) input_tax`,[c,p.period_start,p.period_end,c,p.period_start,p.period_end]);data=x}else if(p.code==='IR_TAXPAYER_INVOICE'){const [[x]]=await pool.execute(`SELECT COUNT(*) invoices,COALESCE(SUM(net_total),0) net_total,COALESCE(SUM(tax_total),0) tax_total,COALESCE(MAX(id),0) max_id FROM sales_invoices WHERE company_id=? AND invoice_classification='OFFICIAL' AND is_void=0 AND invoice_date BETWEEN ? AND ?`,[c,p.period_start,p.period_end]);data=x}else if(['IR_SALARY_TAX','IR_SOCIAL_SECURITY'].includes(p.code)){const x=pp(p.period_start),[[r]]=await pool.execute(`SELECT COUNT(*) slips,COALESCE(SUM(ps.salary_tax),0) salary_tax,COALESCE(SUM(ps.employee_insurance+ps.employer_insurance+ps.unemployment_insurance),0) insurance,COALESCE(MAX(ps.id),0) max_id FROM payroll_slips ps JOIN payroll_batches pb ON pb.id=ps.payroll_batch_id WHERE pb.company_id=? AND pb.year_no=? AND pb.month_no=?`,[c,x.year,x.month]);data=r}else data={periodId:p.id,calculatedAmount:n(p.calculated_amount),payableAmount:n(p.payable_amount)};return crypto.createHash('sha256').update(JSON.stringify(data||{})).digest('hex')}
async function get(id,c){const [r]=await pool.execute(`SELECT p.*,t.code,t.requires_filing,t.requires_payment FROM compliance_periods p JOIN compliance_obligation_types t ON t.id=p.obligation_type_id WHERE p.id=? AND p.company_id=?`,[id,c]);if(!r.length)fail('دوره تکلیف پیدا نشد.',404);return r[0]}
async function verify(p,c){const h=await currentHash(c,p);if(!p.source_hash||h!==p.source_hash)fail('داده‌های منبع پس از محاسبه تکلیف تغییر کرده‌اند؛ محاسبه مجدد الزامی است.',409,{storedHash:p.source_hash,currentHash:h});return h}
export function registerComplianceControlOverrideV7(app){
 app.post('/api/iran/compliance/periods/:id/review',requireRole('FINANCE_MANAGER','HR_MANAGER'),wrap(async(req,res)=>{const id=Number(req.params.id),p=await get(id,req.user.companyId);if(p.status!=='CALCULATED')fail('دوره در وضعیت قابل بازبینی نیست.',409);await verify(p,req.user.companyId);if(Number(p.prepared_by)===Number(req.user.sub))fail('بازبین باید مستقل از تهیه‌کننده باشد.',409);await pool.execute(`UPDATE compliance_periods SET status='REVIEWED',reviewed_by=?,reviewed_at=NOW() WHERE id=?`,[Number(req.user.sub),id]);res.json({ok:true,status:'REVIEWED'})}));
 app.post('/api/iran/compliance/periods/:id/approve',requireRole('FINANCE_MANAGER','SUPER_ADMIN'),wrap(async(req,res)=>{const id=Number(req.params.id),p=await get(id,req.user.companyId);if(p.status!=='REVIEWED')fail('دوره در وضعیت قابل تأیید نیست.',409);await verify(p,req.user.companyId);if([p.prepared_by,p.reviewed_by].map(Number).includes(Number(req.user.sub)))fail('تأییدکننده باید مستقل از تهیه‌کننده و بازبین باشد.',409);await pool.execute(`UPDATE compliance_periods SET status='READY_TO_FILE',approved_by=?,approved_at=NOW() WHERE id=?`,[Number(req.user.sub),id]);res.json({ok:true,status:'READY_TO_FILE'})}));
 app.post('/api/iran/compliance/periods/:id/file',requireRole('FINANCE_MANAGER','SUPER_ADMIN'),wrap(async(req,res)=>{const id=Number(req.params.id),ref=String(req.body?.filingReference||'').trim(),p=await get(id,req.user.companyId);if(p.status!=='READY_TO_FILE')fail('دوره آماده ثبت ارسال نیست.',409);if(!ref)fail('شماره/مرجع ارسال الزامی است.');await verify(p,req.user.companyId);await pool.execute(`UPDATE compliance_periods SET status='FILED',filing_reference=?,filing_at=NOW(),filed_by=? WHERE id=?`,[ref,Number(req.user.sub),id]);res.json({ok:true,status:'FILED',filingReference:ref})}));
}
