import { pool } from './db.js';
import { requireRole } from './auth.js';
const n=v=>Number(v||0),txt=v=>String(v??'').trim();
const wrap=fn=>async(req,res)=>{try{await fn(req,res)}catch(e){console.error('crm v4 extra error',e);res.status(e.status||400).json({error:e.message})}};
export function registerCrmV4ExtraRoutes(app){
 app.get('/api/iran/crm/dashboard',requireRole('CRM_MANAGER','SALES_MANAGER','CUSTOMER_SERVICE'),wrap(async(req,res)=>{const c=req.user.companyId;const [[x]]=await pool.execute(`SELECT (SELECT COUNT(*) FROM crm_leads WHERE company_id=? AND status NOT IN ('DISQUALIFIED','CONVERTED','CLOSED')) open_leads,(SELECT COUNT(*) FROM crm_opportunities WHERE company_id=? AND stage NOT IN ('WON','LOST')) open_opportunities,(SELECT COALESCE(SUM(estimated_value*probability/100),0) FROM crm_opportunities WHERE company_id=? AND stage NOT IN ('WON','LOST')) weighted_pipeline,(SELECT COUNT(*) FROM crm_opportunities WHERE company_id=? AND stage='WON') won_opportunities,(SELECT COUNT(*) FROM crm_opportunities WHERE company_id=? AND stage='LOST') lost_opportunities,(SELECT COUNT(*) FROM crm_activities WHERE company_id=? AND status IN ('OPEN','IN_PROGRESS') AND scheduled_at<=CURRENT_DATE) due_activities,(SELECT COUNT(*) FROM crm_activities WHERE company_id=? AND status IN ('OPEN','IN_PROGRESS') AND scheduled_at<NOW()) overdue_activities,(SELECT COUNT(*) FROM crm_tickets WHERE company_id=? AND status NOT IN ('RESOLVED','CLOSED','CANCELLED')) open_tickets,(SELECT COUNT(*) FROM crm_tickets WHERE company_id=? AND status NOT IN ('RESOLVED','CLOSED','CANCELLED') AND sla_due_at<NOW()) sla_breaches,(SELECT COUNT(*) FROM customer_health_snapshots h JOIN (SELECT party_id,MAX(id) id FROM customer_health_snapshots WHERE company_id=? GROUP BY party_id) z ON z.id=h.id WHERE h.health_state IN ('AT_RISK','CRITICAL')) at_risk_customers`,[c,c,c,c,c,c,c,c,c,c]);const totalOpp=n(x.won_opportunities)+n(x.lost_opportunities);x.win_rate=totalOpp?n(x.won_opportunities)/totalOpp*100:0;res.json(x)}));
 app.get('/api/iran/loyalty/tiers',requireRole('CRM_MANAGER','SALES_MANAGER','FINANCE_MANAGER'),wrap(async(req,res)=>{const [rows]=await pool.execute(`SELECT t.*,(SELECT COUNT(*) FROM loyalty_accounts a WHERE a.tier_id=t.id AND a.status='ACTIVE') members FROM loyalty_tiers t WHERE t.company_id=? ORDER BY t.priority`,[req.user.companyId]);res.json(rows)}));
 app.get('/api/iran/loyalty/rules',requireRole('CRM_MANAGER','FINANCE_MANAGER'),wrap(async(req,res)=>{const [rows]=await pool.execute(`SELECT * FROM loyalty_rules WHERE company_id=? ORDER BY is_active DESC,effective_from DESC,id DESC`,[req.user.companyId]);res.json(rows)}));
 app.get('/api/iran/loyalty/rewards',requireRole('CRM_MANAGER','SALES_MANAGER','FINANCE_MANAGER'),wrap(async(req,res)=>{const [rows]=await pool.execute(`SELECT * FROM loyalty_rewards WHERE company_id=? ORDER BY is_active DESC,valid_to,title`,[req.user.companyId]);res.json(rows)}));
 app.get('/api/iran/loyalty/redemptions',requireRole('CRM_MANAGER','SALES_MANAGER','FINANCE_MANAGER'),wrap(async(req,res)=>{const [rows]=await pool.execute(`SELECT r.*,p.name customer,a.member_no,w.title reward_title FROM loyalty_redemptions r JOIN loyalty_accounts a ON a.id=r.loyalty_account_id JOIN parties p ON p.id=a.party_id JOIN loyalty_rewards w ON w.id=r.reward_id WHERE r.company_id=? ORDER BY r.requested_at DESC,r.id DESC LIMIT 500`,[req.user.companyId]);res.json(rows)}));
 app.get('/api/iran/crm/surveys',requireRole('CRM_MANAGER','CUSTOMER_SERVICE'),wrap(async(req,res)=>{const [rows]=await pool.execute(`SELECT s.*,(SELECT COUNT(*) FROM customer_survey_responses r WHERE r.survey_id=s.id) responses,(SELECT AVG(score) FROM customer_survey_responses r WHERE r.survey_id=s.id) average_score FROM customer_surveys s WHERE s.company_id=? ORDER BY s.is_active DESC,s.id DESC`,[req.user.companyId]);res.json(rows)}));
 app.get('/api/iran/crm/customer-health',requireRole('CRM_MANAGER','SALES_MANAGER'),wrap(async(req,res)=>{const state=txt(req.query.state),[rows]=await pool.execute(`SELECT h.*,p.name customer,p.mobile FROM customer_health_snapshots h JOIN parties p ON p.id=h.party_id JOIN (SELECT party_id,MAX(id) id FROM customer_health_snapshots WHERE company_id=? GROUP BY party_id) z ON z.id=h.id WHERE (?='' OR h.health_state=?) ORDER BY h.health_score ASC,p.name`,[req.user.companyId,state,state]);res.json(rows)}));
}
