import { pool } from './db.js';
const cache=new Map(),TTL=30000;
const rank={HIDDEN:0,MASKED:1,READ_ONLY:2,FULL:3};
const normalized=p=>String(p||'').replace(/^\/api(?=\/)/,'');
const entityForPath=raw=>{const p=normalized(raw);return p.startsWith('/iran/hr/employees')?'EMPLOYEE':p.startsWith('/iran/payroll')?'PAYROLL':p.startsWith('/treasury/bank-accounts')||p.startsWith('/iran/treasury')?'TREASURY':p.startsWith('/parties')||p.startsWith('/iran/parties')||p.startsWith('/iran/crm/customer-360')?'PARTY':null};
function mask(v,pattern){if(v==null)return v;const s=String(v),p=String(pattern||'LAST4').toUpperCase();if(p==='EMAIL'){const [a,b]=s.split('@');return b?`${(a||'').slice(0,2)}***@${b}`:'***'}if(p==='PHONE')return s.length<=4?'****':`${'*'.repeat(Math.max(4,s.length-4))}${s.slice(-4)}`;if(p==='IBAN')return s.length<=6?'******':`${s.slice(0,4)}${'*'.repeat(Math.max(4,s.length-8))}${s.slice(-4)}`;const m=p.match(/^LAST(\d+)$/),k=m?Number(m[1]):4;return s.length<=k?'*'.repeat(s.length):`${'*'.repeat(Math.max(4,s.length-k))}${s.slice(-k)}`}
function transform(value,policies){if(Array.isArray(value))return value.map(x=>transform(x,policies));if(!value||typeof value!=='object')return value;const out={};for(const [k,v] of Object.entries(value)){const p=policies.get(k.toLowerCase());if(!p){out[k]=transform(v,policies);continue}if(p.access_mode==='HIDDEN')continue;if(p.access_mode==='MASKED')out[k]=mask(v,p.mask_pattern);else out[k]=transform(v,policies)}return out}
async function policies(companyId,roles,entity){const key=`${companyId}:${entity}:${[...roles].sort().join(',')}`,hit=cache.get(key);if(hit&&Date.now()-hit.at<TTL)return hit.value;if(!roles.length)return new Map();const q=roles.map(()=>'?').join(','),[rows]=await pool.execute(`SELECT * FROM field_access_policies WHERE (company_id=? OR company_id IS NULL) AND entity_type=? AND role_code IN (${q}) ORDER BY company_id IS NULL ASC`,[companyId,entity,...roles]);const byField=new Map();for(const r of rows){const f=String(r.field_name).toLowerCase(),old=byField.get(f);if(!old||rank[r.access_mode]>rank[old.access_mode])byField.set(f,r)}cache.set(key,{at:Date.now(),value:byField});return byField}
export async function fieldPolicyMiddleware(req,res,next){try{const entity=entityForPath(req.path);if(!entity||!req.user)return next();const p=await policies(req.user.companyId,req.user.roles||[],entity);if(!p.size)return next();const original=res.json.bind(res);res.json=body=>original(transform(body,p));next()}catch(e){console.error('field policy middleware error',e);next()}}
export function clearFieldPolicyCache(){cache.clear()}
