import { pool, withTransaction } from './db.js';
import { requireRole } from './auth.js';
const n=v=>Number(v||0),txt=v=>String(v??'').trim();
const fail=(m,s=400,d=null)=>{const e=new Error(m);e.status=s;e.details=d;throw e};
const wrap=fn=>async(req,res)=>{try{await fn(req,res)}catch(e){console.error('finance controls error',e);res.status(e.status||400).json({error:e.message,details:e.details||undefined})}};
const div=(a,b)=>Math.trunc(a/b),mod=(a,b)=>a-Math.trunc(a/b)*b;
function jalCal(jy,withoutLeap=false){const breaks=[-61,9,38,199,426,686,756,818,1111,1181,1210,1635,2060,2097,2192,2262,2324,2394,2456,3178];let bl=breaks.length,gy=jy+621,leapJ=-14,jp=breaks[0],jm,jump=0,leap,leapG,march,n,i;if(jy<jp||jy>=breaks[bl-1])throw new Error('سال شمسی خارج از محدوده پشتیبانی است.');for(i=1;i<bl;i++){jm=breaks[i];jump=jm-jp;if(jy<jm)break;leapJ+=div(jump,33)*8+div(mod(jump,33),4);jp=jm}n=jy-jp;leapJ+=div(n,33)*8+div(mod(n,33)+3,4);if(mod(jump,33)===4&&jump-n===4)leapJ++;leapG=div(gy,4)-div((div(gy,100)+1)*3,4)-150;march=20+leapJ-leapG;if(withoutLeap)return{gy,march};if(jump-n<6)n=n-jump+div(jump+4,33)*33;leap=mod(mod(n+1,33)-1,4);if(leap===-1)leap=4;return{leap,gy,march}}
function g2d(gy,gm,gd){let d=div((gy+div(gm-8,6)+100100)*1461,4)+div(153*mod(gm+9,12)+2,5)+gd-34840408;d=d-div(div(gy+100100+div(gm-8,6),100)*3,4)+752;return d}
function d2g(jdn){let j=4*jdn+139361631;j=j+div(div(4*jdn+183187720,146097)*3,4)*4-3908;const i=div(mod(j,1461),4)*5+308,gd=div(mod(i,153),5)+1,gm=mod(div(i,153),12)+1,gy=div(j,1461)-100100+div(8-gm,6);return{gy,gm,gd}}
function j2g(jy,jm,jd){const r=jalCal(jy,true),jdn=g2d(r.gy,3,r.march)+(jm-1)*31-div(jm,7)*(jm-7)+jd-1;return d2g(jdn)}
const iso=g=>`${g.gy}-${String(g.gm).padStart(2,'0')}-${String(g.gd).padStart(2,'0')}`;
function jalaliPeriods(year){const leap=jalCal(year).leap===0,arr=[];for(let m=1;m<=12;m++){const start=j2g(year,m,1),days=m<=6?31:m<=11?30:(leap?30:29),end=j2g(year,m,days);arr.push({periodNo:m,title:`${year}/${String(m).padStart(2,'0')}`,dateFrom:iso(start),dateTo:iso(end)})}return arr}
async function nextNo(conn,c,type,prefix){const lock=`trz:fctl:${c}:${type}`;const [[g]]=await conn.query('SELECT GET_LOCK(?,5) got',[lock]);if(!g?.got)fail('شماره‌گذاری سند موقتاً درگیر است.',409);try{let [r]=await conn.execute(`SELECT id,last_number,prefix,pad_length FROM document_sequences WHERE company_id=? AND branch_id IS NULL AND fiscal_year_id IS NULL AND document_type=? ORDER BY id LIMIT 1 FOR UPDATE`,[c,type]);if(!r.length){await conn.execute(`INSERT INTO document_sequences(company_id,document_type,prefix,last_number,pad_length) VALUES (?,?,?,0,6)`,[c,type,prefix]);[r]=await conn.execute(`SELECT id,last_number,prefix,pad_length FROM document_sequences WHERE company_id=? AND branch_id IS NULL AND fiscal_year_id IS NULL AND document_type=? ORDER BY id LIMIT 1 FOR UPDATE`,[c,type])}const x=r[0],v=n(x.last_number)+1;await conn.execute('UPDATE document_sequences SET last_number=? WHERE id=?',[v,x.id]);return`${x.prefix||prefix}-${String(v).padStart(Number(x.pad_length||6),'0')}`}finally{await conn.query('SELECT RELEASE_LOCK(?)',[lock])}}
async function account(conn,c,code){const [r]=await conn.execute('SELECT id FROM accounts WHERE company_id=? AND code=?',[c,code]);if(!r.length)fail(`حساب ${code} پیدا نشد.`,422);return r[0].id}
async function journal(conn,c,date,type,id,description,userId,lines){const [old]=await conn.execute(`SELECT id,entry_no FROM journal_entries WHERE company_id=? AND source_type=? AND source_id=? AND status<>'VOID'`,[c,type,id]);if(old.length)return{journalEntryId:old[0].id,duplicatePrevented:true};let dr=0,cr=0;for(const l of lines){dr+=n(l.debit);cr+=n(l.credit)}if(Math.abs(dr-cr)>1)fail('سند هزینه خرید تراز نیست.',422,{dr,cr});const no=await nextNo(conn,c,'JOURNAL_IR','JE'),[j]=await conn.execute(`INSERT INTO journal_entries(company_id,entry_no,entry_date,posting_date,status,source_type,source_id,description,created_by,posted_at) VALUES (?,?,?,?, 'POSTED',?,?,?,?,NOW())`,[c,no,date,date,type,id,description,userId]);for(const l of lines)if(n(l.debit)||n(l.credit))await conn.execute(`INSERT INTO journal_lines(journal_entry_id,account_id,debit,credit,description) VALUES (?,?,?,?,?)`,[j.insertId,l.accountId,n(l.debit),n(l.credit),description]);return{journalEntryId:j.insertId,entryNo:no,debit:dr,credit:cr}}

export function registerFinanceV3ControlRoutes(app){
 app.post('/api/iran/finance/budgets',requireRole('FINANCE_MANAGER'),wrap(async(req,res)=>{const b=req.body||{},jy=n(b.jalaliYear||String(b.fiscalYearLabel||'').replace(/[^0-9]/g,'')),periods=Array.isArray(b.periods)&&b.periods.length?b.periods:(jy?jalaliPeriods(jy):[]);if(!txt(b.title)||!periods.length||!Array.isArray(b.lines)||!b.lines.length)fail('عنوان، سال/دوره‌های مالی و ردیف‌های بودجه الزامی است.');const result=await withTransaction(async conn=>{const no=await nextNo(conn,req.user.companyId,'BUDGET','BUD'),start=periods[0].dateFrom,end=periods[periods.length-1].dateTo,[h]=await conn.execute(`INSERT INTO budget_headers(company_id,budget_no,title,fiscal_year_label,start_date,end_date,version_no,status,created_by) VALUES (?,?,?,?,?,?,?,'DRAFT',?)`,[req.user.companyId,no,b.title,b.fiscalYearLabel||String(jy),start,end,n(b.versionNo)||1,Number(req.user.sub)]),map={};for(const p of periods){if(n(p.periodNo)<1||!p.dateFrom||!p.dateTo)fail('تعریف دوره بودجه معتبر نیست.');const [r]=await conn.execute(`INSERT INTO budget_periods(budget_id,period_no,title,date_from,date_to) VALUES (?,?,?,?,?)`,[h.insertId,n(p.periodNo),p.title||String(p.periodNo),p.dateFrom,p.dateTo]);map[n(p.periodNo)]=r.insertId}for(const l of b.lines){if(!l.accountId||!map[n(l.periodNo)])fail('حساب یا دوره ردیف بودجه معتبر نیست.');await conn.execute(`INSERT INTO budget_lines(budget_id,account_id,branch_id,department_code,cost_center_code,project_code,budget_period_id,period_no,budget_amount,warning_percent,control_mode) VALUES (?,?,?,?,?,?,?,?,?,?,?)`,[h.insertId,l.accountId,l.branchId||null,l.departmentCode||null,l.costCenterCode||null,l.projectCode||null,map[n(l.periodNo)],n(l.periodNo),n(l.budgetAmount),n(l.warningPercent)||90,l.controlMode||'WARN'])}return{id:h.insertId,budgetNo:no,startDate:start,endDate:end,periods:periods.length}});res.status(201).json(result)}));

 app.get('/api/iran/finance/budgets/:id/status',requireRole('ACCOUNTANT','FINANCE_MANAGER'),wrap(async(req,res)=>{const id=Number(req.params.id),[h]=await pool.execute('SELECT * FROM budget_headers WHERE id=? AND company_id=?',[id,req.user.companyId]);if(!h.length)fail('بودجه پیدا نشد.',404);const [rows]=await pool.execute(`SELECT bl.*,bp.title period_title,bp.date_from,bp.date_to,a.code account_code,a.title account_title,COALESCE((SELECT SUM(jl.debit-jl.credit) FROM journal_lines jl JOIN journal_entries je ON je.id=jl.journal_entry_id WHERE jl.account_id=bl.account_id AND je.company_id=? AND je.status='POSTED' AND je.posting_date BETWEEN bp.date_from AND bp.date_to),0) actual_amount,COALESCE((SELECT SUM(bc.amount-bc.consumed_amount) FROM budget_commitments bc WHERE bc.budget_line_id=bl.id AND bc.status='RESERVED'),0) committed_amount FROM budget_lines bl JOIN budget_periods bp ON bp.id=bl.budget_period_id JOIN accounts a ON a.id=bl.account_id WHERE bl.budget_id=? ORDER BY bp.period_no,a.code`,[req.user.companyId,id]);for(const x of rows){x.available=n(x.budget_amount)-n(x.actual_amount)-n(x.committed_amount);x.utilizationPct=n(x.budget_amount)?((n(x.actual_amount)+n(x.committed_amount))/n(x.budget_amount)*100):0}res.json({budget:h[0],lines:rows,totalBudget:rows.reduce((s,x)=>s+n(x.budget_amount),0),totalActual:rows.reduce((s,x)=>s+n(x.actual_amount),0),totalCommitted:rows.reduce((s,x)=>s+n(x.committed_amount),0)})}));

 app.post('/api/iran/finance/budget-check',requireRole('ACCOUNTANT','FINANCE_MANAGER'),wrap(async(req,res)=>{const b=req.body||{},amount=n(b.amount),date=b.commitmentDate||new Date().toISOString().slice(0,10);if(!b.accountId||!b.sourceType||!b.sourceId||amount<=0)fail('اطلاعات کنترل بودجه ناقص است.');const result=await withTransaction(async conn=>{const p=[req.user.companyId,b.accountId,date,date],extra=[];let sql=`SELECT bl.*,bp.date_from,bp.date_to,bp.period_no FROM budget_lines bl JOIN budget_headers h ON h.id=bl.budget_id JOIN budget_periods bp ON bp.id=bl.budget_period_id WHERE h.company_id=? AND h.status='ACTIVE' AND bl.account_id=? AND ? BETWEEN bp.date_from AND bp.date_to`;if(b.branchId){sql+=' AND (bl.branch_id IS NULL OR bl.branch_id=?)';p.push(b.branchId)}sql+=' ORDER BY h.version_no DESC,bl.id DESC LIMIT 1 FOR UPDATE';const [ls]=await conn.execute(sql,p);if(!ls.length)return{controlled:false,decision:'ALLOW',message:'ردیف بودجه فعالی برای تاریخ و حساب انتخاب‌شده وجود ندارد.'};const l=ls[0],[[act]]=await conn.execute(`SELECT COALESCE(SUM(jl.debit-jl.credit),0) a FROM journal_lines jl JOIN journal_entries je ON je.id=jl.journal_entry_id WHERE jl.account_id=? AND je.company_id=? AND je.status='POSTED' AND je.posting_date BETWEEN ? AND ?`,[l.account_id,req.user.companyId,l.date_from,l.date_to]),[[comm]]=await conn.execute(`SELECT COALESCE(SUM(amount-consumed_amount),0) a FROM budget_commitments WHERE budget_line_id=? AND status='RESERVED'`,[l.id]),used=n(act.a)+n(comm.a),after=used+amount,pct=n(l.budget_amount)?after/n(l.budget_amount)*100:0;let decision='ALLOW';if(l.control_mode==='BLOCK'&&after>n(l.budget_amount))decision='BLOCK';else if(l.control_mode==='APPROVAL'&&after>n(l.budget_amount))decision='APPROVAL';else if(l.control_mode==='WARN'&&pct>=n(l.warning_percent))decision='WARN';if(b.reserve&&decision!=='BLOCK')await conn.execute(`INSERT INTO budget_commitments(company_id,budget_line_id,source_type,source_id,commitment_date,amount,status) VALUES (?,?,?,?,?,?,'RESERVED') ON DUPLICATE KEY UPDATE amount=VALUES(amount),commitment_date=VALUES(commitment_date),status='RESERVED'`,[req.user.companyId,l.id,b.sourceType,b.sourceId,date,amount]);return{controlled:true,budgetLineId:l.id,periodNo:l.period_no,periodFrom:l.date_from,periodTo:l.date_to,budgetAmount:n(l.budget_amount),actual:n(act.a),committed:n(comm.a),requested:amount,after,utilizationPct:pct,controlMode:l.control_mode,decision}});res.json(result)}));

 app.post('/api/iran/finance/landed-costs/:id/post-v2',requireRole('FINANCE_MANAGER'),wrap(async(req,res)=>{const id=Number(req.params.id),result=await withTransaction(async conn=>{const [h]=await conn.execute(`SELECT * FROM landed_cost_headers WHERE id=? AND company_id=? FOR UPDATE`,[id,req.user.companyId]);if(!h.length||h[0].status!=='CALCULATED')fail('هزینه خرید ابتدا باید محاسبه شود.',422);const [targets]=await conn.execute(`SELECT t.*,l.accepted_qty,l.unit_cost,gr.warehouse_id,cl.id cost_layer_id,cl.original_qty,cl.remaining_qty FROM landed_cost_targets t JOIN goods_receipt_lines l ON l.id=t.goods_receipt_line_id JOIN goods_receipts gr ON gr.id=l.goods_receipt_id LEFT JOIN inventory_cost_layers cl ON cl.goods_receipt_line_id=l.id WHERE t.landed_cost_id=? FOR UPDATE`,[id]);const invAc=await account(conn,req.user.companyId,'130100'),cogsAc=await account(conn,req.user.companyId,'510100'),clearAc=await account(conn,req.user.companyId,'210600');let invPortion=0,consumedPortion=0;for(const t of targets){const original=Math.max(n(t.original_qty||t.accepted_qty),0),remaining=Math.max(0,Math.min(original,n(t.remaining_qty))),per=original?n(t.allocated_cost)/original:0,ip=per*remaining,cp=n(t.allocated_cost)-ip;invPortion+=ip;consumedPortion+=cp;if(t.cost_layer_id)await conn.execute(`UPDATE inventory_cost_layers SET landed_cost_per_unit=landed_cost_per_unit+?,status='ADJUSTED' WHERE id=?`,[per,t.cost_layer_id]);const [ib]=await conn.execute(`SELECT id,on_hand_qty,average_cost FROM inventory_balances WHERE company_id=? AND warehouse_id=? AND product_id=? AND batch_no IS NULL AND expiry_date IS NULL FOR UPDATE`,[req.user.companyId,t.warehouse_id,t.product_id]);if(ib.length&&n(ib[0].on_hand_qty)>0&&ip>0)await conn.execute(`UPDATE inventory_balances SET average_cost=average_cost+(?/on_hand_qty) WHERE id=?`,[ip,ib[0].id]);await conn.execute(`UPDATE landed_cost_targets SET remaining_qty_at_post=?,inventory_portion=?,consumed_portion=? WHERE id=?`,[remaining,ip,cp,t.id])}const lines=[];if(invPortion>0.01)lines.push({accountId:invAc,debit:invPortion,credit:0});if(consumedPortion>0.01)lines.push({accountId:cogsAc,debit:consumedPortion,credit:0});lines.push({accountId:clearAc,debit:0,credit:invPortion+consumedPortion});const j=await journal(conn,req.user.companyId,h[0].cost_date,'LANDED_COST_V2',id,`هزینه خرید ${h[0].landed_cost_no}`,Number(req.user.sub),lines);await conn.execute(`UPDATE landed_cost_headers SET status='POSTED',journal_entry_id=? WHERE id=?`,[j.journalEntryId,id]);return{ok:true,total:n(h[0].total_cost),inventoryPortion:invPortion,consumedPortion,...j}});res.json(result)}));

 app.get('/api/iran/finance/fiscal-periods/:jalaliYear',requireRole('ACCOUNTANT','FINANCE_MANAGER'),wrap(async(req,res)=>{const y=Number(req.params.jalaliYear);if(y<1300||y>1600)fail('سال شمسی معتبر نیست.');res.json(jalaliPeriods(y))}));
}
