import { pool } from './db.js';
import { requireRole } from './auth.js';
const txt=v=>String(v??'').trim(),wrap=fn=>async(req,res)=>{try{await fn(req,res)}catch(e){console.error('finance v3 extra error',e);res.status(e.status||400).json({error:e.message})}};
export function registerFinanceV3ExtraRoutes(app){
 app.get('/api/iran/finance/ar-credit-notes',requireRole('ACCOUNTANT','FINANCE_MANAGER','SALES_MANAGER'),wrap(async(req,res)=>{const status=txt(req.query.status),[rows]=await pool.execute(`SELECT n.*,p.name customer,si.invoice_no source_invoice FROM ar_credit_notes n JOIN parties p ON p.id=n.customer_party_id LEFT JOIN sales_invoices si ON si.id=n.sales_invoice_id WHERE n.company_id=? AND (?='' OR n.status=?) ORDER BY n.note_date DESC,n.id DESC LIMIT 500`,[req.user.companyId,status,status]);res.json(rows)}));
 app.get('/api/iran/finance/ap-debit-notes',requireRole('ACCOUNTANT','FINANCE_MANAGER'),wrap(async(req,res)=>{const status=txt(req.query.status),[rows]=await pool.execute(`SELECT n.*,p.name supplier,pi.invoice_no source_invoice FROM ap_debit_notes n JOIN parties p ON p.id=n.supplier_party_id LEFT JOIN purchase_invoices pi ON pi.id=n.purchase_invoice_id WHERE n.company_id=? AND (?='' OR n.status=?) ORDER BY n.note_date DESC,n.id DESC LIMIT 500`,[req.user.companyId,status,status]);res.json(rows)}));
 app.get('/api/iran/finance/budgets',requireRole('ACCOUNTANT','FINANCE_MANAGER'),wrap(async(req,res)=>{const [rows]=await pool.execute(`SELECT h.*,(SELECT COALESCE(SUM(budget_amount),0) FROM budget_lines l WHERE l.budget_id=h.id) total_budget,(SELECT COUNT(*) FROM budget_lines l WHERE l.budget_id=h.id) line_count FROM budget_headers h WHERE h.company_id=? ORDER BY h.start_date DESC,h.version_no DESC,h.id DESC`,[req.user.companyId]);res.json(rows)}));
 app.get('/api/iran/finance/asset-classes',requireRole('ACCOUNTANT','FINANCE_MANAGER'),wrap(async(req,res)=>{const [rows]=await pool.execute(`SELECT c.*,a.code asset_account_code,a2.code accumulated_account_code,e.code expense_account_code FROM fixed_asset_classes c JOIN accounts a ON a.id=c.asset_account_id JOIN accounts a2 ON a2.id=c.accumulated_depreciation_account_id JOIN accounts e ON e.id=c.depreciation_expense_account_id WHERE c.company_id=? ORDER BY c.is_active DESC,c.code`,[req.user.companyId]);res.json(rows)}));
 app.get('/api/iran/finance/assets',requireRole('ACCOUNTANT','FINANCE_MANAGER'),wrap(async(req,res)=>{const status=txt(req.query.status),[rows]=await pool.execute(`SELECT a.*,c.code class_code,c.title class_title,p.name custodian FROM fixed_assets a JOIN fixed_asset_classes c ON c.id=a.asset_class_id LEFT JOIN parties p ON p.id=a.custodian_party_id WHERE a.company_id=? AND (?='' OR a.status=?) ORDER BY a.status,a.asset_no`,[req.user.companyId,status,status]);res.json(rows)}));
 app.get('/api/iran/finance/depreciation-runs',requireRole('ACCOUNTANT','FINANCE_MANAGER'),wrap(async(req,res)=>{const [rows]=await pool.execute(`SELECT d.*,(SELECT COUNT(*) FROM depreciation_run_lines l WHERE l.depreciation_run_id=d.id) asset_count FROM depreciation_runs d WHERE d.company_id=? ORDER BY d.period_end DESC,d.id DESC`,[req.user.companyId]);res.json(rows)}));
 app.get('/api/iran/finance/landed-costs',requireRole('ACCOUNTANT','FINANCE_MANAGER'),wrap(async(req,res)=>{const [rows]=await pool.execute(`SELECT h.*,(SELECT COUNT(*) FROM landed_cost_targets t WHERE t.landed_cost_id=h.id) target_count,(SELECT COALESCE(SUM(inventory_portion),0) FROM landed_cost_targets t WHERE t.landed_cost_id=h.id) inventory_portion,(SELECT COALESCE(SUM(consumed_portion),0) FROM landed_cost_targets t WHERE t.landed_cost_id=h.id) consumed_portion FROM landed_cost_headers h WHERE h.company_id=? ORDER BY h.cost_date DESC,h.id DESC`,[req.user.companyId]);res.json(rows)}));
 app.get('/api/iran/finance/projects',requireRole('ACCOUNTANT','FINANCE_MANAGER','SALES_MANAGER'),wrap(async(req,res)=>{const [rows]=await pool.execute(`SELECT p.*,c.name customer,u.full_name manager,(SELECT COUNT(*) FROM project_contracts pc WHERE pc.project_id=p.id) contract_count,(SELECT COALESCE(SUM(CASE WHEN transaction_type='REVENUE' THEN amount ELSE 0 END),0) FROM project_transactions t WHERE t.project_id=p.id) revenue,(SELECT COALESCE(SUM(CASE WHEN transaction_type IN ('DIRECT_COST','INDIRECT_COST') THEN amount ELSE 0 END),0) FROM project_transactions t WHERE t.project_id=p.id) cost FROM management_projects p LEFT JOIN parties c ON c.id=p.customer_party_id LEFT JOIN users u ON u.id=p.manager_user_id WHERE p.company_id=? ORDER BY p.status,p.start_date DESC,p.id DESC`,[req.user.companyId]);for(const x of rows)x.profit=Number(x.revenue||0)-Number(x.cost||0);res.json(rows)}));
 app.get('/api/iran/finance/projects/:id/contracts',requireRole('ACCOUNTANT','FINANCE_MANAGER','SALES_MANAGER'),wrap(async(req,res)=>{const [rows]=await pool.execute(`SELECT c.*,p.name counterparty,(SELECT COALESCE(SUM(amount),0) FROM contract_milestones m WHERE m.project_contract_id=c.id) milestone_total,(SELECT COALESCE(SUM(billed_amount),0) FROM contract_milestones m WHERE m.project_contract_id=c.id) billed_amount,(SELECT COALESCE(SUM(received_paid_amount),0) FROM contract_milestones m WHERE m.project_contract_id=c.id) settled_amount FROM project_contracts c JOIN management_projects pr ON pr.id=c.project_id JOIN parties p ON p.id=c.counterparty_party_id WHERE c.project_id=? AND pr.company_id=? ORDER BY c.start_date,c.id`,[Number(req.params.id),req.user.companyId]);res.json(rows)}));
}
