import { pool, withTransaction } from './db.js';
import { requireRole } from './auth.js';
const n=v=>Number(v||0),txt=v=>String(v??'').trim();
const fail=(m,s=400,d=null)=>{const e=new Error(m);e.status=s;e.details=d;throw e};
const wrap=fn=>async(req,res)=>{try{await fn(req,res)}catch(e){console.error('fx v5 error',e);res.status(e.status||400).json({error:e.message,details:e.details||undefined})}};
async function nextNo(conn,c,type,prefix){const lock=`trz:fx:${c}:${type}`;const [[g]]=await conn.query('SELECT GET_LOCK(?,5) got',[lock]);if(!g?.got)fail('شماره‌گذاری اسناد موقتاً درگیر است.',409);try{let [r]=await conn.execute(`SELECT id,last_number,prefix,pad_length FROM document_sequences WHERE company_id=? AND branch_id IS NULL AND fiscal_year_id IS NULL AND document_type=? ORDER BY id LIMIT 1 FOR UPDATE`,[c,type]);if(!r.length){await conn.execute(`INSERT INTO document_sequences(company_id,document_type,prefix,last_number,pad_length) VALUES (?,?,?,0,6)`,[c,type,prefix]);[r]=await conn.execute(`SELECT id,last_number,prefix,pad_length FROM document_sequences WHERE company_id=? AND branch_id IS NULL AND fiscal_year_id IS NULL AND document_type=? ORDER BY id LIMIT 1 FOR UPDATE`,[c,type])}const x=r[0],v=n(x.last_number)+1;await conn.execute('UPDATE document_sequences SET last_number=? WHERE id=?',[v,x.id]);return`${x.prefix||prefix}-${String(v).padStart(Number(x.pad_length||6),'0')}`}finally{await conn.query('SELECT RELEASE_LOCK(?)',[lock])}}
async function accountId(conn,c,code){const [r]=await conn.execute('SELECT id FROM accounts WHERE company_id=? AND code=?',[c,code]);if(!r.length)fail(`حساب ${code} تعریف نشده است.`,422);return r[0].id}
async function companyPolicy(conn,c){const [r]=await conn.execute('SELECT * FROM company_accounting_policies WHERE company_id=?',[c]);if(!r.length)fail('سیاست حسابداری شرکت تعریف نشده است.',422);return r[0]}
async function closingRate(conn,c,date,currency,base,type){if(currency===base)return 1;const [r]=await conn.execute(`SELECT rate FROM exchange_rates WHERE company_id=? AND rate_date<=? AND from_currency=? AND to_currency=? AND rate_type=? ORDER BY rate_date DESC,id DESC LIMIT 1`,[c,date,currency,base,type]);if(!r.length)fail(`نرخ ${currency}/${base} برای تاریخ تسعیر پیدا نشد.`,422);return n(r[0].rate)}

export function registerFxV5Routes(app){
 app.get('/api/iran/fx/currencies',wrap(async(_req,res)=>{const [r]=await pool.execute('SELECT * FROM currencies WHERE is_active=1 ORDER BY code');res.json(r)}));
 app.get('/api/iran/fx/rates',requireRole('ACCOUNTANT','FINANCE_MANAGER'),wrap(async(req,res)=>{const from=txt(req.query.fromCurrency),to=txt(req.query.toCurrency),where=['company_id=?'],p=[req.user.companyId];if(from){where.push('from_currency=?');p.push(from)}if(to){where.push('to_currency=?');p.push(to)}const [r]=await pool.execute(`SELECT * FROM exchange_rates WHERE ${where.join(' AND ')} ORDER BY rate_date DESC,id DESC LIMIT 500`,p);res.json(r)}));
 app.post('/api/iran/fx/rates',requireRole('FINANCE_MANAGER'),wrap(async(req,res)=>{const b=req.body||{},rate=n(b.rate);if(!b.rateDate||!txt(b.fromCurrency)||!txt(b.toCurrency)||rate<=0)fail('تاریخ، ارز مبدأ، ارز مقصد و نرخ معتبر الزامی است.');await pool.execute(`INSERT INTO exchange_rates(company_id,rate_date,from_currency,to_currency,rate_type,rate,source,entered_by) VALUES (?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE rate=VALUES(rate),source=VALUES(source),entered_by=VALUES(entered_by),created_at=CURRENT_TIMESTAMP`,[req.user.companyId,b.rateDate,b.fromCurrency,b.toCurrency,b.rateType||'CUSTOM',rate,b.source||null,Number(req.user.sub)]);res.json({ok:true})}));

 app.post('/api/iran/fx/manual-journals',requireRole('ACCOUNTANT','FINANCE_MANAGER'),wrap(async(req,res)=>{const b=req.body||{},lines=Array.isArray(b.lines)?b.lines:[];if(!b.entryDate||lines.length<2)fail('تاریخ و حداقل دو ردیف سند الزامی است.');const result=await withTransaction(async conn=>{const policy=await companyPolicy(conn,req.user.companyId),no=await nextNo(conn,req.user.companyId,'JOURNAL_FX','JFX');let dr=0,cr=0;const normalized=[];for(const l of lines){const fd=n(l.foreignDebit),fc=n(l.foreignCredit),currency=txt(l.currencyCode)||policy.base_currency_code,rate=currency===policy.base_currency_code?1:n(l.exchangeRate);if(!l.accountId||rate<=0||((fd>0)===(fc>0)))fail('هر ردیف باید فقط بدهکار یا بستانکار ارزی و دارای نرخ معتبر باشد.',422);const baseDr=fd*rate,baseCr=fc*rate;dr+=baseDr;cr+=baseCr;normalized.push({...l,currency,rate,fd,fc,baseDr,baseCr})}if(Math.abs(dr-cr)>.5)fail('سند ارزی از نظر مبلغ پایه تراز نیست.',422,{debit:dr,credit:cr,difference:dr-cr});const [je]=await conn.execute(`INSERT INTO journal_entries(company_id,entry_no,entry_date,posting_date,status,source_type,description,created_by) VALUES (?,?,?,?, 'PREPARED','MANUAL_FX',?,?)`,[req.user.companyId,no,b.entryDate,b.postingDate||b.entryDate,b.description||'سند ارزی',Number(req.user.sub)]);for(const l of normalized)await conn.execute(`INSERT INTO journal_lines(journal_entry_id,account_id,party_id,cost_center_code,project_code,debit,credit,description,currency_code,foreign_debit,foreign_credit,exchange_rate) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`,[je.insertId,l.accountId,l.partyId||null,l.costCenterCode||null,l.projectCode||null,l.baseDr,l.baseCr,l.description||null,l.currency,l.fd,l.fc,l.rate]);return{id:je.insertId,entryNo:no,debit:dr,credit:cr,status:'PREPARED'}});res.status(201).json(result)}));
 app.post('/api/iran/fx/manual-journals/:id/check',requireRole('ACCOUNTANT','FINANCE_MANAGER'),wrap(async(req,res)=>{const id=Number(req.params.id);const [r]=await pool.execute(`UPDATE journal_entries SET status='CHECKED',checked_by=? WHERE id=? AND company_id=? AND status='PREPARED' AND created_by<>?`,[Number(req.user.sub),id,req.user.companyId,Number(req.user.sub)]);if(!r.affectedRows)fail('کنترل سند مجاز نیست؛ کنترل‌کننده باید با تهیه‌کننده متفاوت باشد.',409);res.json({ok:true,status:'CHECKED'})}));
 app.post('/api/iran/fx/manual-journals/:id/approve',requireRole('FINANCE_MANAGER'),wrap(async(req,res)=>{const id=Number(req.params.id);const [r]=await pool.execute(`UPDATE journal_entries SET status='APPROVED',approved_by=? WHERE id=? AND company_id=? AND status='CHECKED' AND created_by<>? AND checked_by<>?`,[Number(req.user.sub),id,req.user.companyId,Number(req.user.sub),Number(req.user.sub)]);if(!r.affectedRows)fail('تأییدکننده باید مستقل از تهیه‌کننده و کنترل‌کننده باشد.',409);res.json({ok:true,status:'APPROVED'})}));
 app.post('/api/iran/fx/manual-journals/:id/post',requireRole('FINANCE_MANAGER'),wrap(async(req,res)=>{const id=Number(req.params.id);const [r]=await pool.execute(`UPDATE journal_entries SET status='POSTED',posted_at=NOW() WHERE id=? AND company_id=? AND status='APPROVED'`,[id,req.user.companyId]);if(!r.affectedRows)fail('سند آماده ثبت قطعی نیست.',409);res.json({ok:true,status:'POSTED'})}));

 app.get('/api/iran/fx/revaluations',requireRole('ACCOUNTANT','FINANCE_MANAGER'),wrap(async(req,res)=>{const [r]=await pool.execute(`SELECT x.*,u.full_name creator,rv.full_name reviewer FROM fx_revaluation_runs x LEFT JOIN users u ON u.id=x.created_by LEFT JOIN users rv ON rv.id=x.reviewed_by WHERE x.company_id=? ORDER BY x.revaluation_date DESC,x.id DESC`,[req.user.companyId]);res.json(r)}));
 app.post('/api/iran/fx/revaluations/calculate',requireRole('FINANCE_MANAGER'),wrap(async(req,res)=>{const b=req.body||{},date=b.revaluationDate,type=b.rateType||'CLOSING';if(!date)fail('تاریخ تسعیر الزامی است.');const result=await withTransaction(async conn=>{const policy=await companyPolicy(conn,req.user.companyId),base=policy.base_currency_code,no=await nextNo(conn,req.user.companyId,'FX_REVALUATION','FXR');const [run]=await conn.execute(`INSERT INTO fx_revaluation_runs(company_id,run_no,revaluation_date,rate_type,status,created_by) VALUES (?,?,?,?, 'DRAFT',?)`,[req.user.companyId,no,date,type,Number(req.user.sub)]);const [balances]=await conn.execute(`SELECT jl.account_id,jl.party_id,jl.currency_code,SUM(jl.foreign_debit-jl.foreign_credit) foreign_balance,SUM(jl.debit-jl.credit) old_base_balance FROM journal_lines jl JOIN journal_entries je ON je.id=jl.journal_entry_id JOIN accounts a ON a.id=jl.account_id WHERE je.company_id=? AND je.status IN ('POSTED','LOCKED') AND je.entry_date<=? AND a.currency_revaluation_mode='MONETARY' AND jl.currency_code IS NOT NULL AND jl.currency_code<>? GROUP BY jl.account_id,jl.party_id,jl.currency_code HAVING ABS(foreign_balance)>.000001`,[req.user.companyId,date,base]);let gain=0,loss=0,count=0;for(const x of balances){const rate=await closingRate(conn,req.user.companyId,date,x.currency_code,base,type),newBase=n(x.foreign_balance)*rate,delta=newBase-n(x.old_base_balance);if(Math.abs(delta)<.5)continue;await conn.execute(`INSERT INTO fx_revaluation_lines(run_id,account_id,party_id,currency_code,foreign_balance,old_base_balance,closing_rate,new_base_balance,gain_loss_amount) VALUES (?,?,?,?,?,?,?,?,?)`,[run.insertId,x.account_id,x.party_id||null,x.currency_code,x.foreign_balance,x.old_base_balance,rate,newBase,delta]);if(delta>0)gain+=delta;else loss+=-delta;count++}await conn.execute(`UPDATE fx_revaluation_runs SET status='CALCULATED',gain_amount=?,loss_amount=? WHERE id=?`,[gain,loss,run.insertId]);return{id:run.insertId,runNo:no,lineCount:count,gainAmount:gain,lossAmount:loss,status:'CALCULATED'}});res.status(201).json(result)}));
 app.post('/api/iran/fx/revaluations/:id/review',requireRole('FINANCE_MANAGER'),wrap(async(req,res)=>{const id=Number(req.params.id);const [r]=await pool.execute(`UPDATE fx_revaluation_runs SET status='REVIEWED',reviewed_by=? WHERE id=? AND company_id=? AND status='CALCULATED' AND created_by<>?`,[Number(req.user.sub),id,req.user.companyId,Number(req.user.sub)]);if(!r.affectedRows)fail('بازبین تسعیر باید مستقل از محاسبه‌کننده باشد.',409);res.json({ok:true,status:'REVIEWED'})}));
 app.post('/api/iran/fx/revaluations/:id/post',requireRole('FINANCE_MANAGER'),wrap(async(req,res)=>{const id=Number(req.params.id),result=await withTransaction(async conn=>{const [runs]=await conn.execute(`SELECT * FROM fx_revaluation_runs WHERE id=? AND company_id=? FOR UPDATE`,[id,req.user.companyId]);const run=runs[0];if(!run||run.status!=='REVIEWED')fail('تسعیر آماده ثبت نیست.',409);if(Number(run.created_by)===Number(req.user.sub)||Number(run.reviewed_by)===Number(req.user.sub))fail('ثبت‌کننده نهایی باید مستقل از تهیه و بازبینی باشد.',409);const gainAcc=await accountId(conn,req.user.companyId,'420100'),lossAcc=await accountId(conn,req.user.companyId,'710100'),no=await nextNo(conn,req.user.companyId,'JOURNAL_FX_REVAL','JFXR'),[je]=await conn.execute(`INSERT INTO journal_entries(company_id,entry_no,entry_date,posting_date,status,source_type,source_id,description,created_by,posted_at) VALUES (?,?,?,?, 'POSTED','FX_REVALUATION',?,'تسعیر مانده‌های ارزی',?,NOW())`,[req.user.companyId,no,run.revaluation_date,run.revaluation_date,id,Number(req.user.sub)]);const [lines]=await conn.execute('SELECT * FROM fx_revaluation_lines WHERE run_id=?',[id]);let dr=0,cr=0;for(const l of lines){const delta=n(l.gain_loss_amount);if(delta>0){await conn.execute(`INSERT INTO journal_lines(journal_entry_id,account_id,party_id,debit,credit,description,currency_code) VALUES (?,?,?, ?,0,'تعدیل تسعیر',NULL)`,[je.insertId,l.account_id,l.party_id||null,delta]);await conn.execute(`INSERT INTO journal_lines(journal_entry_id,account_id,debit,credit,description) VALUES (?,?,0,?,'سود تسعیر ارز')`,[je.insertId,gainAcc,delta]);dr+=delta;cr+=delta}else if(delta<0){const a=-delta;await conn.execute(`INSERT INTO journal_lines(journal_entry_id,account_id,debit,credit,description) VALUES (?,?,? ,0,'زیان تسعیر ارز')`,[je.insertId,lossAcc,a]);await conn.execute(`INSERT INTO journal_lines(journal_entry_id,account_id,party_id,debit,credit,description,currency_code) VALUES (?,?,?,0,?,'تعدیل تسعیر',NULL)`,[je.insertId,l.account_id,l.party_id||null,a]);dr+=a;cr+=a}}await conn.execute(`UPDATE fx_revaluation_runs SET status='POSTED',journal_entry_id=? WHERE id=?`,[je.insertId,id]);return{ok:true,journalEntryId:je.insertId,debit:dr,credit:cr,status:'POSTED'}});res.json(result)}));
}
