import crypto from 'node:crypto';
import { pool } from './db.js';
import { requireRole } from './auth.js';
const n=v=>Number(v||0),txt=v=>String(v??'').trim(),fail=(m,s=400)=>{const e=new Error(m);e.status=s;throw e},wrap=fn=>async(req,res)=>{try{await fn(req,res)}catch(e){console.error('historical reporting v7 error',e);res.status(e.status||400).json({error:e.message})}};
async function pl(c,from,to){const [r]=await pool.execute(`SELECT a.id,a.code,a.title,a.account_type,a.statement_section,SUM(jl.debit) debit,SUM(jl.credit) credit FROM accounts a JOIN journal_lines jl ON jl.account_id=a.id JOIN journal_entries je ON je.id=jl.journal_entry_id WHERE a.company_id=? AND a.account_type IN ('REVENUE','EXPENSE') AND je.status IN ('POSTED','LOCKED') AND je.source_type<>'YEAR_END_CLOSE' AND COALESCE(je.posting_date,je.entry_date) BETWEEN ? AND ? GROUP BY a.id,a.code,a.title,a.account_type,a.statement_section`,[c,from,to]);const s={OPERATING_REVENUE:0,COST_OF_SALES:0,OPERATING_EXPENSE:0,OTHER_REVENUE:0,OTHER_EXPENSE:0,TAX:0},unmapped=[];for(const a of r){const amount=a.account_type==='REVENUE'?n(a.credit)-n(a.debit):n(a.debit)-n(a.credit);if(a.statement_section==='UNASSIGNED'){if(Math.abs(amount)>.5)unmapped.push({accountId:a.id,code:a.code,title:a.title,amount});continue}if(s[a.statement_section]!==undefined)s[a.statement_section]+=amount}const gross=s.OPERATING_REVENUE-s.COST_OF_SALES,operating=gross-s.OPERATING_EXPENSE,pretax=operating+s.OTHER_REVENUE-s.OTHER_EXPENSE;return{from,to,sections:s,grossProfit:gross,operatingProfit:operating,profitBeforeTax:pretax,netProfit:pretax-s.TAX,unmapped}}
async function hash(c,from,to){const [[x]]=await pool.execute(`SELECT COUNT(*) rows_count,COALESCE(SUM(jl.debit),0) debit,COALESCE(SUM(jl.credit),0) credit,COALESCE(MAX(jl.id),0) max_line FROM journal_lines jl JOIN journal_entries je ON je.id=jl.journal_entry_id WHERE je.company_id=? AND je.status IN ('POSTED','LOCKED') AND je.source_type<>'YEAR_END_CLOSE' AND COALESCE(je.posting_date,je.entry_date) BETWEEN ? AND ?`,[c,from,to]);return crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex')}
export function registerHistoricalReportingOverrideV7(app){
 app.get('/api/iran/finance/profit-loss',requireRole('ACCOUNTANT','FINANCE_MANAGER'),wrap(async(req,res)=>{const from=txt(req.query.dateFrom),to=txt(req.query.dateTo);if(!from||!to)fail('بازه گزارش سود و زیان الزامی است.');const current=await pl(req.user.companyId,from,to);let comparative=null;if(req.query.compareFrom&&req.query.compareTo)comparative=await pl(req.user.companyId,req.query.compareFrom,req.query.compareTo);res.json({current,comparative,sourceHash:await hash(req.user.companyId,from,to),excludedSystemSources:['YEAR_END_CLOSE']})}));
 app.post('/api/iran/finance/report-snapshots',requireRole('FINANCE_MANAGER'),async(req,res,next)=>{try{if(req.body?.reportType!=='PROFIT_LOSS')return next();const b=req.body||{};if(!b.periodStart||!b.asOfDate)fail('ابتدا و انتهای دوره سود و زیان الزامی است.');const result=await pl(req.user.companyId,b.periodStart,b.asOfDate),sourceHash=await hash(req.user.companyId,b.periodStart,b.asOfDate),[r]=await pool.execute(`INSERT INTO financial_report_snapshots(company_id,report_type,as_of_date,period_start,parameters_json,result_json,source_hash,created_by) VALUES (?,?,?,?,?,?,?,?)`,[req.user.companyId,'PROFIT_LOSS',b.asOfDate,b.periodStart,JSON.stringify(b.parameters||{}),JSON.stringify(result),sourceHash,Number(req.user.sub)]);res.status(201).json({id:r.insertId,sourceHash})}catch(e){res.status(e.status||400).json({error:e.message})}});
}
