import { pool, withTransaction } from './db.js';
import { requireRole } from './auth.js';
const n=v=>Number(v||0),txt=v=>String(v??'').trim();
const fail=(m,s=400,d=null)=>{const e=new Error(m);e.status=s;e.details=d;throw e};
const wrap=fn=>async(req,res)=>{try{await fn(req,res)}catch(e){console.error('masterdata v8 error',e);res.status(e.status||400).json({error:e.message,details:e.details||undefined})}};
async function audit(req,action,type,id,payload){try{await pool.execute(`INSERT INTO audit_logs(company_id,user_id,action,entity_type,entity_id,after_json,ip_address,user_agent) VALUES (?,?,?,?,?,?,?,?)`,[req.user.companyId,Number(req.user.sub),action,type,String(id||''),JSON.stringify(payload||{}),req.ip,req.headers['user-agent']||null])}catch{}}

export function registerMasterDataPrintV8(app){
  app.get('/api/iran/v8/product-groups',wrap(async(req,res)=>{const [r]=await pool.execute(`SELECT g.*,p.title parent_title,(SELECT COUNT(*) FROM product_group_members m WHERE m.group_id=g.id) product_count FROM product_groups g LEFT JOIN product_groups p ON p.id=g.parent_id WHERE g.company_id=? ORDER BY g.level_no,g.sort_order,g.title`,[req.user.companyId]);res.json(r)}));
  app.post('/api/iran/v8/product-groups',requireRole('WAREHOUSE_MANAGER','SALES_MANAGER'),wrap(async(req,res)=>{const b=req.body||{};if(!txt(b.code)||!txt(b.title))fail('کد و عنوان گروه کالا الزامی است.');let level=1;if(b.parentId){const [[p]]=await pool.execute('SELECT level_no FROM product_groups WHERE id=? AND company_id=?',[b.parentId,req.user.companyId]);if(!p)fail('گروه بالاتر پیدا نشد.',404);level=n(p.level_no)+1}const [r]=await pool.execute(`INSERT INTO product_groups(company_id,parent_id,code,title,level_no,sort_order) VALUES (?,?,?,?,?,?)`,[req.user.companyId,b.parentId||null,txt(b.code),txt(b.title),level,n(b.sortOrder)]);await audit(req,'CREATE','product_group',r.insertId,b);res.status(201).json({id:r.insertId})}));

  app.get('/api/iran/v8/products/:id/detail',wrap(async(req,res)=>{const id=n(req.params.id);const [r]=await pool.execute(`SELECT p.*,g.id group_id,g.title group_title FROM products p LEFT JOIN product_group_members gm ON gm.product_id=p.id AND gm.is_primary=1 LEFT JOIN product_groups g ON g.id=gm.group_id WHERE p.id=? AND p.company_id=?`,[id,req.user.companyId]);if(!r.length)fail('کالا پیدا نشد.',404);const [units]=await pool.execute('SELECT * FROM product_units WHERE product_id=? ORDER BY is_base DESC,id',[id]);const [stock]=await pool.execute(`SELECT ib.*,w.name warehouse FROM inventory_balances ib JOIN warehouses w ON w.id=ib.warehouse_id WHERE ib.company_id=? AND ib.product_id=? ORDER BY w.name,ib.expiry_date`,[req.user.companyId,id]);res.json({...r[0],units,stock})}));
  app.put('/api/iran/v8/products/:id/detail',requireRole('WAREHOUSE_MANAGER','SALES_MANAGER'),wrap(async(req,res)=>{const id=n(req.params.id),b=req.body||{};await withTransaction(async conn=>{const [old]=await conn.execute('SELECT id FROM products WHERE id=? AND company_id=? FOR UPDATE',[id,req.user.companyId]);if(!old.length)fail('کالا پیدا نشد.',404);await conn.execute(`UPDATE products SET sku=COALESCE(?,sku),barcode=?,name=COALESCE(?,name),short_name=?,brand=?,category=?,unit=COALESCE(?,unit),sale_price=COALESCE(?,sale_price),purchase_price=COALESCE(?,purchase_price),model=?,country_of_origin=?,image_url=?,description=?,technical_spec=?,sales_taxable=COALESCE(?,sales_taxable),purchase_taxable=COALESCE(?,purchase_taxable),track_batch=COALESCE(?,track_batch),track_expiry=COALESCE(?,track_expiry),catch_weight=COALESCE(?,catch_weight),is_active=COALESCE(?,is_active) WHERE id=?`,[b.sku||null,b.barcode??null,b.name||null,b.shortName??null,b.brand??null,b.category??null,b.unit||null,b.salePrice==null?null:n(b.salePrice),b.purchasePrice==null?null:n(b.purchasePrice),b.model??null,b.countryOfOrigin??null,b.imageUrl??null,b.description??null,b.technicalSpec?JSON.stringify(b.technicalSpec):null,b.salesTaxable==null?null:(b.salesTaxable?1:0),b.purchaseTaxable==null?null:(b.purchaseTaxable?1:0),b.trackBatch==null?null:(b.trackBatch?1:0),b.trackExpiry==null?null:(b.trackExpiry?1:0),b.catchWeight==null?null:(b.catchWeight?1:0),b.isActive==null?null:(b.isActive?1:0),id]);if(b.primaryGroupId){await conn.execute('UPDATE product_group_members SET is_primary=0 WHERE product_id=?',[id]);await conn.execute(`INSERT INTO product_group_members(product_id,group_id,is_primary) VALUES (?,?,1) ON DUPLICATE KEY UPDATE is_primary=1`,[id,b.primaryGroupId])}if(Array.isArray(b.units)){await conn.execute('DELETE FROM product_units WHERE product_id=?',[id]);for(const u of b.units)await conn.execute(`INSERT INTO product_units(product_id,unit_name,conversion_factor,barcode,is_base) VALUES (?,?,?,?,?)`,[id,txt(u.unitName),n(u.conversionFactor)||1,u.barcode||null,u.isBase?1:0])}});await audit(req,'UPDATE','product',id,b);res.json({ok:true})}));

  app.get('/api/iran/v8/services',wrap(async(req,res)=>{const [r]=await pool.execute(`SELECT s.*,g.title group_title FROM services s LEFT JOIN service_groups g ON g.id=s.group_id WHERE s.company_id=? ORDER BY s.id DESC`,[req.user.companyId]);res.json(r)}));
  app.post('/api/iran/v8/services',requireRole('SALES_MANAGER','FINANCE_MANAGER'),wrap(async(req,res)=>{const b=req.body||{};if(!txt(b.code)||!txt(b.name))fail('کد و نام خدمت الزامی است.');const [r]=await pool.execute(`INSERT INTO services(company_id,group_id,code,name,unit,sale_price,vat_rate,commission_rate,description) VALUES (?,?,?,?,?,?,?,?,?)`,[req.user.companyId,b.groupId||null,txt(b.code),txt(b.name),b.unit||'عدد',n(b.salePrice),n(b.vatRate),n(b.commissionRate),b.description||null]);await audit(req,'CREATE','service',r.insertId,b);res.status(201).json({id:r.insertId})}));
  app.get('/api/iran/v8/service-groups',wrap(async(req,res)=>{const [r]=await pool.execute('SELECT * FROM service_groups WHERE company_id=? ORDER BY title',[req.user.companyId]);res.json(r)}));
  app.post('/api/iran/v8/service-groups',requireRole('SALES_MANAGER'),wrap(async(req,res)=>{const b=req.body||{};const [r]=await pool.execute('INSERT INTO service_groups(company_id,parent_id,code,title) VALUES (?,?,?,?)',[req.user.companyId,b.parentId||null,txt(b.code),txt(b.title)]);res.status(201).json({id:r.insertId})}));

  app.get('/api/iran/v8/party-groups',wrap(async(req,res)=>{const [r]=await pool.execute(`SELECT g.*,p.title parent_title,(SELECT COUNT(*) FROM party_group_members m WHERE m.group_id=g.id) member_count FROM party_groups g LEFT JOIN party_groups p ON p.id=g.parent_id WHERE g.company_id=? ORDER BY g.title`,[req.user.companyId]);res.json(r)}));
  app.post('/api/iran/v8/party-groups',requireRole('SALES_MANAGER','FINANCE_MANAGER','HR_MANAGER'),wrap(async(req,res)=>{const b=req.body||{};const [r]=await pool.execute('INSERT INTO party_groups(company_id,parent_id,code,title) VALUES (?,?,?,?)',[req.user.companyId,b.parentId||null,txt(b.code),txt(b.title)]);res.status(201).json({id:r.insertId})}));
  app.get('/api/iran/v8/parties/:id/detail',wrap(async(req,res)=>{const id=n(req.params.id);const [r]=await pool.execute(`SELECT p.*,d.prefix,d.first_name,d.last_name,d.company_name,d.registration_no,d.postal_code,d.website,d.opening_balance,d.opening_balance_nature,d.cheque_credit_limit,d.receivable_credit_limit,d.notes,d.photo_url,cp.credit_limit,cp.payment_terms_days FROM parties p LEFT JOIN party_details d ON d.party_id=p.id LEFT JOIN customer_profiles cp ON cp.party_id=p.id WHERE p.id=? AND p.company_id=?`,[id,req.user.companyId]);if(!r.length)fail('شخص پیدا نشد.',404);const [roles]=await pool.execute('SELECT role_code FROM party_roles WHERE party_id=?',[id]);const [contacts]=await pool.execute('SELECT * FROM party_contacts WHERE party_id=? ORDER BY is_primary DESC,sort_order,id',[id]);const [addresses]=await pool.execute('SELECT * FROM party_addresses WHERE party_id=? ORDER BY is_primary DESC,id',[id]);const [groups]=await pool.execute(`SELECT g.id,g.title FROM party_group_members m JOIN party_groups g ON g.id=m.group_id WHERE m.party_id=?`,[id]);res.json({...r[0],roles:roles.map(x=>x.role_code),contacts,addresses,groups})}));
  app.put('/api/iran/v8/parties/:id/detail',wrap(async(req,res)=>{const id=n(req.params.id),b=req.body||{};await withTransaction(async conn=>{const [p]=await conn.execute('SELECT id FROM parties WHERE id=? AND company_id=? FOR UPDATE',[id,req.user.companyId]);if(!p.length)fail('شخص پیدا نشد.',404);await conn.execute(`UPDATE parties SET party_type=COALESCE(?,party_type),code=?,name=COALESCE(?,name),national_id=?,economic_code=?,mobile=?,phone=?,email=?,address=?,is_active=COALESCE(?,is_active) WHERE id=?`,[b.partyType||null,b.code??null,b.name||null,b.nationalId??null,b.economicCode??null,b.mobile??null,b.phone??null,b.email??null,b.address??null,b.isActive==null?null:(b.isActive?1:0),id]);await conn.execute(`INSERT INTO party_details(party_id,prefix,first_name,last_name,company_name,registration_no,postal_code,website,opening_balance,opening_balance_nature,cheque_credit_limit,receivable_credit_limit,notes,photo_url) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE prefix=VALUES(prefix),first_name=VALUES(first_name),last_name=VALUES(last_name),company_name=VALUES(company_name),registration_no=VALUES(registration_no),postal_code=VALUES(postal_code),website=VALUES(website),opening_balance=VALUES(opening_balance),opening_balance_nature=VALUES(opening_balance_nature),cheque_credit_limit=VALUES(cheque_credit_limit),receivable_credit_limit=VALUES(receivable_credit_limit),notes=VALUES(notes),photo_url=VALUES(photo_url)`,[id,b.prefix||null,b.firstName||null,b.lastName||null,b.companyName||null,b.registrationNo||null,b.postalCode||null,b.website||null,n(b.openingBalance),b.openingBalanceNature||'ZERO',n(b.chequeCreditLimit),n(b.receivableCreditLimit),b.notes||null,b.photoUrl||null]);if(Array.isArray(b.roles)){await conn.execute('DELETE FROM party_roles WHERE party_id=?',[id]);for(const role of b.roles)await conn.execute('INSERT INTO party_roles(party_id,role_code) VALUES (?,?)',[id,role])}if(Array.isArray(b.contacts)){await conn.execute('DELETE FROM party_contacts WHERE party_id=?',[id]);for(const c of b.contacts)await conn.execute(`INSERT INTO party_contacts(party_id,contact_type,title,value,is_primary,sort_order) VALUES (?,?,?,?,?,?)`,[id,c.contactType||'OTHER',c.title||null,txt(c.value),c.isPrimary?1:0,n(c.sortOrder)])}if(Array.isArray(b.addresses)){await conn.execute('DELETE FROM party_addresses WHERE party_id=?',[id]);for(const a of b.addresses)await conn.execute(`INSERT INTO party_addresses(party_id,address_type,province,city,address_text,postal_code,latitude,longitude,is_primary) VALUES (?,?,?,?,?,?,?,?,?)`,[id,a.addressType||'MAIN',a.province||null,a.city||null,txt(a.addressText),a.postalCode||null,a.latitude||null,a.longitude||null,a.isPrimary?1:0])}if(Array.isArray(b.groupIds)){await conn.execute('DELETE FROM party_group_members WHERE party_id=?',[id]);for(const g of b.groupIds)await conn.execute('INSERT INTO party_group_members(party_id,group_id) VALUES (?,?)',[id,g])}});await audit(req,'UPDATE','party',id,b);res.json({ok:true})}));

  app.get('/api/iran/v8/bank-accounts',requireRole('ACCOUNTANT','FINANCE_MANAGER'),wrap(async(req,res)=>{const [r]=await pool.execute('SELECT * FROM bank_accounts WHERE company_id=? ORDER BY is_active DESC,bank_name,account_code',[req.user.companyId]);res.json(r)}));
  app.post('/api/iran/v8/bank-accounts',requireRole('FINANCE_MANAGER'),wrap(async(req,res)=>{const b=req.body||{};if(!txt(b.accountCode)||!txt(b.bankName)||!txt(b.accountNo))fail('کد حساب، نام بانک و شماره حساب الزامی است.');const [r]=await pool.execute(`INSERT INTO bank_accounts(company_id,account_code,bank_name,account_type,branch_code,branch_name,account_no,iban,card_no,account_holder,opening_balance,current_balance,phone,fax,address,notes) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[req.user.companyId,txt(b.accountCode),txt(b.bankName),b.accountType||null,b.branchCode||null,b.branchName||null,txt(b.accountNo),b.iban||null,b.cardNo||null,b.accountHolder||null,n(b.openingBalance),n(b.openingBalance),b.phone||null,b.fax||null,b.address||null,b.notes||null]);await audit(req,'CREATE','bank_account',r.insertId,b);res.status(201).json({id:r.insertId})}));

  app.get('/api/iran/v8/price-lists',wrap(async(req,res)=>{const [r]=await pool.execute(`SELECT pl.*,(SELECT COUNT(*) FROM price_list_items i WHERE i.price_list_id=pl.id) item_count FROM price_lists pl WHERE pl.company_id=? ORDER BY pl.id DESC`,[req.user.companyId]);res.json(r)}));
  app.post('/api/iran/v8/price-lists',requireRole('SALES_MANAGER'),wrap(async(req,res)=>{const b=req.body||{};if(!txt(b.code)||!txt(b.title))fail('کد و عنوان لیست قیمت الزامی است.');const [r]=await pool.execute(`INSERT INTO price_lists(company_id,code,title,valid_from,valid_to,currency_code,audience,notes,status,created_by) VALUES (?,?,?,?,?,?,?,?,?,?)`,[req.user.companyId,txt(b.code),txt(b.title),b.validFrom||null,b.validTo||null,b.currencyCode||'IRR',b.audience||null,b.notes||null,b.status||'DRAFT',Number(req.user.sub)]);res.status(201).json({id:r.insertId})}));
  app.get('/api/iran/v8/price-lists/:id',wrap(async(req,res)=>{const id=n(req.params.id);const [h]=await pool.execute('SELECT * FROM price_lists WHERE id=? AND company_id=?',[id,req.user.companyId]);if(!h.length)fail('لیست قیمت پیدا نشد.',404);const [items]=await pool.execute(`SELECT i.*,p.sku,p.name,p.short_name,p.brand,p.unit,p.image_url,p.barcode FROM price_list_items i JOIN products p ON p.id=i.product_id WHERE i.price_list_id=? ORDER BY i.sort_order,i.id`,[id]);res.json({...h[0],items})}));
  app.post('/api/iran/v8/price-lists/:id/items',requireRole('SALES_MANAGER'),wrap(async(req,res)=>{const id=n(req.params.id),b=req.body||{};if(!b.productId)fail('کالا الزامی است.');await pool.execute(`INSERT INTO price_list_items(price_list_id,product_id,unit_name,price,old_price,min_qty,item_note,sort_order) VALUES (?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE price=VALUES(price),old_price=VALUES(old_price),min_qty=VALUES(min_qty),item_note=VALUES(item_note),sort_order=VALUES(sort_order)`,[id,b.productId,b.unitName||null,n(b.price),b.oldPrice==null?null:n(b.oldPrice),b.minQty==null?null:n(b.minQty),b.itemNote||null,n(b.sortOrder)]);res.json({ok:true})}));

  app.get('/api/iran/v8/waybills',requireRole('LOGISTICS_MANAGER','SALES_MANAGER','FINANCE_MANAGER'),wrap(async(req,res)=>{const [r]=await pool.execute(`SELECT w.*,t.trip_no,si.invoice_no FROM waybills w LEFT JOIN trips t ON t.id=w.trip_id LEFT JOIN sales_invoices si ON si.id=w.sales_invoice_id WHERE w.company_id=? ORDER BY w.id DESC`,[req.user.companyId]);res.json(r)}));
  app.post('/api/iran/v8/waybills',requireRole('LOGISTICS_MANAGER'),wrap(async(req,res)=>{const b=req.body||{};if(!txt(b.receiverName))fail('نام گیرنده الزامی است.');const [[seq]]=await pool.execute('SELECT COALESCE(MAX(id),0)+1 n FROM waybills WHERE company_id=?',[req.user.companyId]);const no=b.waybillNo||`WB-${new Date().getFullYear()}-${String(seq.n).padStart(7,'0')}`;const [r]=await pool.execute(`INSERT INTO waybills(company_id,waybill_no,trip_id,sales_invoice_id,issue_date,carrier_name,tracking_no,barcode_value,origin_city,origin_address,destination_city,destination_address,sender_name,sender_phone,receiver_name,receiver_phone,receiver_national_id,goods_description,package_count,gross_weight,declared_value,freight_amount,insurance_amount,packing_amount,loading_amount,cod_amount,payment_method,delivery_note,status,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[req.user.companyId,no,b.tripId||null,b.salesInvoiceId||null,b.issueDate||new Date(),b.carrierName||null,b.trackingNo||null,b.barcodeValue||b.trackingNo||no,b.originCity||null,b.originAddress||null,b.destinationCity||null,b.destinationAddress||null,b.senderName||null,b.senderPhone||null,txt(b.receiverName),b.receiverPhone||null,b.receiverNationalId||null,b.goodsDescription||null,n(b.packageCount),n(b.grossWeight),n(b.declaredValue),n(b.freightAmount),n(b.insuranceAmount),n(b.packingAmount),n(b.loadingAmount),n(b.codAmount),b.paymentMethod||null,b.deliveryNote||null,b.status||'DRAFT',Number(req.user.sub)]);await audit(req,'CREATE','waybill',r.insertId,b);res.status(201).json({id:r.insertId,waybillNo:no})}));
  app.get('/api/iran/v8/waybills/:id',wrap(async(req,res)=>{const [r]=await pool.execute(`SELECT w.*,t.trip_no,si.invoice_no FROM waybills w LEFT JOIN trips t ON t.id=w.trip_id LEFT JOIN sales_invoices si ON si.id=w.sales_invoice_id WHERE w.id=? AND w.company_id=?`,[n(req.params.id),req.user.companyId]);if(!r.length)fail('بارنامه پیدا نشد.',404);res.json(r[0])}));

  app.get('/api/iran/v8/reports/item-profitability',requireRole('FINANCE_MANAGER','ACCOUNTANT','SALES_MANAGER'),wrap(async(req,res)=>{const from=req.query.from||'1900-01-01',to=req.query.to||'2999-12-31';const [r]=await pool.execute(`SELECT p.id product_id,p.sku,p.name,p.unit,
    COALESCE((SELECT SUM(l.qty) FROM purchase_invoice_lines l JOIN purchase_invoices h ON h.id=l.invoice_id WHERE l.product_id=p.id AND h.company_id=p.company_id AND h.invoice_date BETWEEN ? AND ? AND h.status<>'VOID'),0) purchase_qty,
    COALESCE((SELECT SUM(l.line_total) FROM purchase_invoice_lines l JOIN purchase_invoices h ON h.id=l.invoice_id WHERE l.product_id=p.id AND h.company_id=p.company_id AND h.invoice_date BETWEEN ? AND ? AND h.status<>'VOID'),0) purchase_amount,
    COALESCE((SELECT SUM(l.qty) FROM sales_invoice_lines l JOIN sales_invoices h ON h.id=l.invoice_id WHERE l.product_id=p.id AND h.company_id=p.company_id AND h.invoice_date BETWEEN ? AND ? AND h.is_void=0),0) sales_qty,
    COALESCE((SELECT SUM(l.line_total) FROM sales_invoice_lines l JOIN sales_invoices h ON h.id=l.invoice_id WHERE l.product_id=p.id AND h.company_id=p.company_id AND h.invoice_date BETWEEN ? AND ? AND h.is_void=0),0) sales_amount,
    COALESCE((SELECT SUM(COALESCE(l.cogs_amount,0)) FROM sales_invoice_lines l JOIN sales_invoices h ON h.id=l.invoice_id WHERE l.product_id=p.id AND h.company_id=p.company_id AND h.invoice_date BETWEEN ? AND ? AND h.is_void=0),0) cogs_amount
    FROM products p WHERE p.company_id=? AND p.is_deleted=0 ORDER BY p.name`,[from,to,from,to,from,to,from,to,from,to,req.user.companyId]);res.json(r.map(x=>{const pq=n(x.purchase_qty),pa=n(x.purchase_amount),sq=n(x.sales_qty),sa=n(x.sales_amount),c=n(x.cogs_amount),variance=pq-sq;return{...x,purchase_avg:pq?pa/pq:0,sales_avg:sq?sa/sq:0,gross_profit:sa-c,gross_margin_pct:sa?((sa-c)/sa)*100:0,qty_variance:variance,status:variance<0?'OVER_SOLD':Math.abs(variance)<.0001?'SETTLED':'STOCK_REMAINS'}}))}));
  app.get('/api/iran/v8/reports/item-profitability/:productId/transactions',requireRole('FINANCE_MANAGER','ACCOUNTANT','SALES_MANAGER'),wrap(async(req,res)=>{const id=n(req.params.productId),from=req.query.from||'1900-01-01',to=req.query.to||'2999-12-31';const [purchases]=await pool.execute(`SELECT h.invoice_date date,h.invoice_no,l.qty,l.unit_price,l.line_total,s.name party FROM purchase_invoice_lines l JOIN purchase_invoices h ON h.id=l.invoice_id JOIN parties s ON s.id=h.supplier_party_id WHERE h.company_id=? AND l.product_id=? AND h.invoice_date BETWEEN ? AND ? AND h.status<>'VOID' ORDER BY h.invoice_date,h.id`,[req.user.companyId,id,from,to]);const [sales]=await pool.execute(`SELECT h.invoice_date date,h.invoice_no,l.qty,l.unit_price,l.line_total,c.name party FROM sales_invoice_lines l JOIN sales_invoices h ON h.id=l.invoice_id JOIN parties c ON c.id=h.customer_party_id WHERE h.company_id=? AND l.product_id=? AND h.invoice_date BETWEEN ? AND ? AND h.is_void=0 ORDER BY h.invoice_date,h.id`,[req.user.companyId,id,from,to]);res.json({purchases,sales})}));

  app.get('/api/iran/v8/print/sales-invoice/:id',wrap(async(req,res)=>{const id=n(req.params.id);const [h]=await pool.execute(`SELECT si.*,p.name customer,p.national_id,p.economic_code,p.mobile,p.phone,p.address FROM sales_invoices si JOIN parties p ON p.id=si.customer_party_id WHERE si.id=? AND si.company_id=?`,[id,req.user.companyId]);if(!h.length)fail('فاکتور پیدا نشد.',404);const [lines]=await pool.execute(`SELECT l.*,p.sku,p.name,p.unit,p.barcode FROM sales_invoice_lines l JOIN products p ON p.id=l.product_id WHERE l.invoice_id=? ORDER BY l.id`,[id]);const [[company]]=await pool.execute('SELECT * FROM companies WHERE id=?',[req.user.companyId]);res.json({documentType:'SALES_INVOICE',company,header:h[0],lines,print:{pageSize:'A4',rtl:true,showBarcode:true}})}));
  app.get('/api/iran/v8/print/price-list/:id',wrap(async(req,res)=>{const id=n(req.params.id);const [h]=await pool.execute('SELECT * FROM price_lists WHERE id=? AND company_id=?',[id,req.user.companyId]);if(!h.length)fail('لیست قیمت پیدا نشد.',404);const [items]=await pool.execute(`SELECT i.*,p.sku,p.name,p.short_name,p.brand,p.unit,p.image_url,p.barcode FROM price_list_items i JOIN products p ON p.id=i.product_id WHERE i.price_list_id=? ORDER BY i.sort_order,i.id`,[id]);const [[company]]=await pool.execute('SELECT * FROM companies WHERE id=?',[req.user.companyId]);res.json({documentType:'PRICE_LIST',company,header:h[0],items,print:{pageSize:'A4',rtl:true,layout:'PRODUCT_CARDS'}})}));
  app.get('/api/iran/v8/print/waybill/:id',wrap(async(req,res)=>{const [w]=await pool.execute(`SELECT wb.*,t.trip_no,si.invoice_no FROM waybills wb LEFT JOIN trips t ON t.id=wb.trip_id LEFT JOIN sales_invoices si ON si.id=wb.sales_invoice_id WHERE wb.id=? AND wb.company_id=?`,[n(req.params.id),req.user.companyId]);if(!w.length)fail('بارنامه پیدا نشد.',404);const [[company]]=await pool.execute('SELECT * FROM companies WHERE id=?',[req.user.companyId]);res.json({documentType:'WAYBILL',company,waybill:w[0],print:{pageSize:'A4',rtl:true,showBarcode:true}})}));
}