import { pool } from './db.js';
import { requireRole } from './auth.js';
const n=v=>Number(v||0),txt=v=>String(v??'').trim();
const fail=(m,s=400,d=null)=>{const e=new Error(m);e.status=s;e.details=d;throw e};
const wrap=fn=>async(req,res)=>{try{await fn(req,res)}catch(e){console.error('office v4 extra error',e);res.status(e.status||400).json({error:e.message,details:e.details||undefined})}};
export function registerOfficeV4ExtraRoutes(app){
 app.get('/api/iran/forms',wrap(async(req,res)=>{const active=txt(req.query.status),[rows]=await pool.execute(`SELECT f.id,f.code,f.title,f.version_no,f.status,f.schema_json,f.bpm_definition_id,b.title bpm_title,f.created_at FROM dynamic_form_definitions f LEFT JOIN bpm_definitions b ON b.id=f.bpm_definition_id WHERE f.company_id=? AND (?='' OR f.status=?) ORDER BY f.status,f.title,f.version_no DESC`,[req.user.companyId,active,active]);res.json(rows)}));
 app.get('/api/iran/forms/submissions',wrap(async(req,res)=>{const status=txt(req.query.status),[rows]=await pool.execute(`SELECT s.id,s.submission_no,s.status,s.submitted_at,s.created_at,f.title form_title,f.code form_code,u.full_name submitted_by_name,s.bpm_instance_id FROM dynamic_form_submissions s JOIN dynamic_form_definitions f ON f.id=s.form_definition_id JOIN users u ON u.id=s.submitted_by WHERE s.company_id=? AND (?='' OR s.status=?) ORDER BY s.id DESC LIMIT 500`,[req.user.companyId,status,status]);res.json(rows)}));
 app.get('/api/iran/forms/submissions/:id',wrap(async(req,res)=>{const id=Number(req.params.id),[s]=await pool.execute(`SELECT s.*,f.title form_title,f.schema_json FROM dynamic_form_submissions s JOIN dynamic_form_definitions f ON f.id=s.form_definition_id WHERE s.id=? AND s.company_id=?`,[id,req.user.companyId]);if(!s.length)fail('درخواست پیدا نشد.',404);res.json(s[0])}));

 app.get('/api/iran/cases/:id/actions',wrap(async(req,res)=>{const [rows]=await pool.execute(`SELECT a.*,u.full_name responsible_name FROM case_actions a JOIN enterprise_cases c ON c.id=a.case_id JOIN users u ON u.id=a.responsible_user_id WHERE a.case_id=? AND c.company_id=? ORDER BY FIELD(a.status,'OPEN','IN_PROGRESS','DONE','CANCELLED'),a.due_at,a.id`,[Number(req.params.id),req.user.companyId]);res.json(rows)}));
 app.post('/api/iran/cases/:id/actions',wrap(async(req,res)=>{const id=Number(req.params.id),b=req.body||{};if(!txt(b.title)||!b.responsibleUserId)fail('عنوان اقدام و مسئول الزامی است.');const [c]=await pool.execute('SELECT id FROM enterprise_cases WHERE id=? AND company_id=?',[id,req.user.companyId]);if(!c.length)fail('پرونده پیدا نشد.',404);const [r]=await pool.execute(`INSERT INTO case_actions(case_id,title,responsible_user_id,due_at,status,note) VALUES (?,?,?,?,'OPEN',?)`,[id,b.title,b.responsibleUserId,b.dueAt||null,b.note||null]);res.status(201).json({id:r.insertId})}));
 app.put('/api/iran/case-actions/:id/complete',wrap(async(req,res)=>{const id=Number(req.params.id),b=req.body||{};const [a]=await pool.execute(`SELECT a.*,c.company_id FROM case_actions a JOIN enterprise_cases c ON c.id=a.case_id WHERE a.id=?`,[id]);if(!a.length||Number(a[0].company_id)!==Number(req.user.companyId))fail('اقدام پیدا نشد.',404);if(Number(a[0].responsible_user_id)!==Number(req.user.sub)&&!(req.user.roles||[]).some(x=>['SUPER_ADMIN','CRM_MANAGER','BPM_MANAGER'].includes(x)))fail('تکمیل این اقدام برای شما مجاز نیست.',403);if(!txt(b.evidenceRef)&&!txt(b.note))fail('برای تکمیل اقدام، شاهد انجام یا توضیح الزامی است.',422);await pool.execute(`UPDATE case_actions SET status='DONE',evidence_ref=?,note=COALESCE(?,note),completed_at=NOW() WHERE id=?`,[b.evidenceRef||null,b.note||null,id]);res.json({ok:true,status:'DONE'})}));

 app.get('/api/iran/office/letters',requireRole('DMS_MANAGER','BPM_MANAGER','SUPER_ADMIN'),wrap(async(req,res)=>{const q=txt(req.query.q),status=txt(req.query.status),w=['l.company_id=?'],p=[req.user.companyId];if(q){const z=`%${q}%`;w.push('(l.letter_no LIKE ? OR l.subject LIKE ? OR l.sender_text LIKE ? OR l.receiver_text LIKE ?)');p.push(z,z,z,z)}if(status){w.push('l.status=?');p.push(status)}const [rows]=await pool.execute(`SELECT l.*,o.full_name owner_name,(SELECT COUNT(*) FROM letter_referrals r WHERE r.letter_id=l.id AND r.status<>'DONE') open_referrals FROM office_letters l JOIN users o ON o.id=l.owner_user_id WHERE ${w.join(' AND ')} ORDER BY l.letter_date DESC,l.id DESC LIMIT 500`,p);res.json(rows)}));
 app.put('/api/iran/office/referrals/:id',wrap(async(req,res)=>{const id=Number(req.params.id),b=req.body||{},status=txt(b.status).toUpperCase();if(!['READ','IN_PROGRESS','DONE','RETURNED'].includes(status))fail('وضعیت ارجاع معتبر نیست.');const [r]=await pool.execute(`UPDATE letter_referrals r JOIN office_letters l ON l.id=r.letter_id SET r.status=?,r.read_at=CASE WHEN ? IN ('READ','IN_PROGRESS','DONE') AND r.read_at IS NULL THEN NOW() ELSE r.read_at END,r.done_at=CASE WHEN ?='DONE' THEN NOW() ELSE r.done_at END WHERE r.id=? AND l.company_id=? AND (r.to_user_id=? OR ? IN ('SUPER_ADMIN','DMS_MANAGER'))`,[status,status,status,id,req.user.companyId,Number(req.user.sub),(req.user.roles||[]).includes('SUPER_ADMIN')?'SUPER_ADMIN':(req.user.roles||[]).includes('DMS_MANAGER')?'DMS_MANAGER':'']);if(!r.affectedRows)fail('ارجاع قابل تغییر نیست.',403);res.json({ok:true,status})}));

 app.get('/api/iran/office/meetings',wrap(async(req,res)=>{const [rows]=await pool.execute(`SELECT m.*,u.full_name organizer_name,(SELECT COUNT(*) FROM meeting_actions a WHERE a.meeting_id=m.id AND a.status NOT IN ('DONE','CANCELLED')) open_actions FROM meetings m JOIN users u ON u.id=m.organizer_user_id WHERE m.company_id=? ORDER BY m.meeting_at DESC,m.id DESC LIMIT 500`,[req.user.companyId]);res.json(rows)}));
 app.get('/api/iran/office/meetings/:id/actions',wrap(async(req,res)=>{const [rows]=await pool.execute(`SELECT a.*,u.full_name responsible_name FROM meeting_actions a JOIN meetings m ON m.id=a.meeting_id JOIN users u ON u.id=a.responsible_user_id WHERE a.meeting_id=? AND m.company_id=? ORDER BY FIELD(a.status,'OPEN','IN_PROGRESS','OVERDUE','DONE','CANCELLED'),a.due_at,a.id`,[Number(req.params.id),req.user.companyId]);res.json(rows)}));
 app.put('/api/iran/office/meeting-actions/:id/complete',wrap(async(req,res)=>{const id=Number(req.params.id),b=req.body||{};const [a]=await pool.execute(`SELECT a.*,m.company_id FROM meeting_actions a JOIN meetings m ON m.id=a.meeting_id WHERE a.id=?`,[id]);if(!a.length||Number(a[0].company_id)!==Number(req.user.companyId))fail('مصوبه پیدا نشد.',404);if(Number(a[0].responsible_user_id)!==Number(req.user.sub)&&!(req.user.roles||[]).includes('SUPER_ADMIN'))fail('این مصوبه به شما تخصیص داده نشده است.',403);if(!txt(b.evidenceRef))fail('شاهد انجام مصوبه الزامی است.',422);await pool.execute(`UPDATE meeting_actions SET status='DONE',evidence_ref=?,completed_at=NOW() WHERE id=?`,[b.evidenceRef,id]);res.json({ok:true,status:'DONE'})}));

 app.get('/api/iran/dms/documents',wrap(async(req,res)=>{const q=txt(req.query.q),w=['d.company_id=?'],p=[req.user.companyId];if(q){const z=`%${q}%`;w.push('(d.document_no LIKE ? OR d.title LIKE ? OR d.document_class LIKE ?)');p.push(z,z,z)}if(!(req.user.roles||[]).some(x=>['SUPER_ADMIN','DMS_MANAGER'].includes(x))){w.push(`(d.confidentiality<>'VERY_CONFIDENTIAL' OR d.owner_user_id=?)`);p.push(Number(req.user.sub))}const [rows]=await pool.execute(`SELECT d.*,u.full_name owner_name,(SELECT MAX(version_no) FROM dms_versions v WHERE v.document_id=d.id) latest_version,(SELECT COUNT(*) FROM dms_versions v WHERE v.document_id=d.id) version_count FROM dms_documents d JOIN users u ON u.id=d.owner_user_id WHERE ${w.join(' AND ')} ORDER BY d.created_at DESC,d.id DESC LIMIT 500`,p);res.json(rows)}));
 app.put('/api/iran/dms/documents/:id/archive',requireRole('DMS_MANAGER','SUPER_ADMIN'),wrap(async(req,res)=>{const [r]=await pool.execute(`UPDATE dms_documents SET status='ARCHIVED' WHERE id=? AND company_id=? AND status='ACTIVE'`,[Number(req.params.id),req.user.companyId]);if(!r.affectedRows)fail('سند قابل آرشیو نیست.',422);res.json({ok:true,status:'ARCHIVED'})}));

 app.post('/api/iran/automation/rules',requireRole('BPM_MANAGER','SUPER_ADMIN'),wrap(async(req,res)=>{const b=req.body||{};if(!txt(b.title)||!txt(b.triggerType)||!b.action)fail('عنوان، محرک و اقدام اتوماسیون الزامی است.');const [r]=await pool.execute(`INSERT INTO automation_rules(company_id,title,trigger_type,trigger_config_json,condition_json,action_json,is_active,created_by) VALUES (?,?,?,?,?,?,?,?)`,[req.user.companyId,b.title,b.triggerType,JSON.stringify(b.triggerConfig||{}),JSON.stringify(b.condition||{}),JSON.stringify(b.action),b.isActive===false?0:1,Number(req.user.sub)]);res.status(201).json({id:r.insertId})}));
 app.get('/api/iran/automation/rules',requireRole('BPM_MANAGER','SUPER_ADMIN'),wrap(async(req,res)=>{const [rows]=await pool.execute(`SELECT * FROM automation_rules WHERE company_id=? ORDER BY is_active DESC,id DESC`,[req.user.companyId]);res.json(rows)}));
 app.post('/api/iran/automation/run-due',requireRole('BPM_MANAGER','SUPER_ADMIN'),wrap(async(req,res)=>{const created=[];const [rules]=await pool.execute(`SELECT * FROM automation_rules WHERE company_id=? AND is_active=1`,[req.user.companyId]);for(const r of rules){let action={};try{action=typeof r.action_json==='object'?r.action_json:JSON.parse(r.action_json)}catch{}if(r.trigger_type==='OVERDUE_BPM'&&action.type==='ESCALATE'){const [x]=await pool.execute(`SELECT w.id FROM bpm_work_items w JOIN bpm_instances i ON i.id=w.bpm_instance_id WHERE i.company_id=? AND w.due_at<NOW() AND w.status IN ('OPEN','CLAIMED','IN_PROGRESS','WAITING_INFO','RETURNED')`,[req.user.companyId]);for(const w of x){await pool.execute('UPDATE bpm_work_items SET escalation_level=escalation_level+1 WHERE id=?',[w.id]);created.push({ruleId:r.id,workItemId:w.id,action:'ESCALATE'})}}await pool.execute('UPDATE automation_rules SET last_run_at=NOW() WHERE id=?',[r.id])}res.json({executed:created.length,actions:created})}));
}
