import { pool, withTransaction } from './db.js';
import { requireRole } from './auth.js';
const n=v=>Number(v||0),txt=v=>String(v??'').trim();
const fail=(m,s=400)=>{const e=new Error(m);e.status=s;throw e};
const wrap=fn=>async(req,res)=>{try{await fn(req,res)}catch(e){console.error('payroll extra error',e);res.status(e.status||400).json({error:e.message})}};
function json(v){if(!v)return{};if(typeof v==='object')return v;try{return JSON.parse(v)}catch{return{}}}
function page(q){const current=Math.max(1,n(q.page)||1),size=Math.min(200,Math.max(10,n(q.pageSize)||50));return{current,size,offset:(current-1)*size}}
async function audit(req,a,type,id,data){try{await pool.execute(`INSERT INTO audit_logs(company_id,user_id,action,entity_type,entity_id,after_json,ip_address,user_agent) VALUES (?,?,?,?,?,?,?,?)`,[req.user.companyId,Number(req.user.sub),a,type,id,JSON.stringify(data||{}),req.ip,req.headers['user-agent']||null])}catch{}}
export function registerPayrollExtraRoutes(app){
 app.get('/api/iran/hr/employees',requireRole('HR_MANAGER','FINANCE_MANAGER'),wrap(async(req,res)=>{const paged=req.query.page!==undefined,{current,size,offset}=page(req.query),q=txt(req.query.q),status=txt(req.query.status),where=['ep.company_id=?','p.is_deleted=0'],params=[req.user.companyId];if(q){const like=`%${q}%`;where.push('(p.name LIKE ? OR ep.personnel_no LIKE ? OR p.national_id LIKE ? OR ep.insurance_no LIKE ?)');params.push(like,like,like,like)}if(status){where.push('ep.employment_status=?');params.push(status)}const sql=where.join(' AND ');const [[count]]=await pool.execute(`SELECT COUNT(*) total FROM employee_profiles ep JOIN parties p ON p.id=ep.party_id WHERE ${sql}`,params);const [rows]=await pool.query(`SELECT p.id party_id,p.name,p.national_id,p.mobile,p.email,p.address,p.postal_code,p.province,p.city,ep.*,d.title department_title,pos.title position_title FROM employee_profiles ep JOIN parties p ON p.id=ep.party_id LEFT JOIN departments d ON d.id=ep.department_id LEFT JOIN positions pos ON pos.id=ep.position_id WHERE ${sql} ORDER BY ep.personnel_no LIMIT ${size} OFFSET ${offset}`,params);res.json(paged?{rows,total:n(count.total),page:current,pageSize:size}:rows)}));
 app.post('/api/iran/hr/employees',requireRole('HR_MANAGER'),wrap(async(req,res)=>{const b=req.body||{};if(!txt(b.name)||!txt(b.personnelNo))fail('نام و شماره پرسنلی الزامی است.');const result=await withTransaction(async conn=>{const [exists]=await conn.execute(`SELECT party_id FROM employee_profiles WHERE company_id=? AND personnel_no=? LIMIT 1`,[req.user.companyId,b.personnelNo]);if(exists.length)fail('شماره پرسنلی تکراری است.',409);const [p]=await conn.execute(`INSERT INTO parties(company_id,party_type,name,national_id,mobile,phone,email,address,postal_code,province,city) VALUES (?,'NATURAL',?,?,?,?,?,?,?,?,?)`,[req.user.companyId,b.name,b.nationalNo||null,b.mobile||null,b.phone||null,b.email||null,b.address||null,b.postalCode||null,b.province||null,b.city||null]);await conn.execute(`INSERT IGNORE INTO party_roles(party_id,role_code) VALUES (?,'EMPLOYEE')`,[p.insertId]);await conn.execute(`INSERT INTO employee_profiles(party_id,company_id,personnel_no,national_no,father_name,birth_date,birth_place,gender,marital_status,children_count,insurance_no,tax_identifier,hire_date,department_id,position_id,employment_status,education_level,field_of_study,emergency_contact,emergency_phone) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[p.insertId,req.user.companyId,b.personnelNo,b.nationalNo||null,b.fatherName||null,b.birthDate||null,b.birthPlace||null,b.gender||null,b.maritalStatus||null,n(b.childrenCount),b.insuranceNo||null,b.taxIdentifier||null,b.hireDate||null,b.departmentId||null,b.positionId||null,b.employmentStatus||'ACTIVE',b.educationLevel||null,b.fieldOfStudy||null,b.emergencyContact||null,b.emergencyPhone||null]);return{partyId:p.insertId}});await audit(req,'CREATE','employee',result.partyId,b);res.status(201).json(result)}));

 app.get('/api/iran/hr/contracts',requireRole('HR_MANAGER','FINANCE_MANAGER'),wrap(async(req,res)=>{const paged=req.query.page!==undefined,{current,size,offset}=page(req.query),q=txt(req.query.q),status=txt(req.query.status),where=['ec.company_id=?'],params=[req.user.companyId];if(q){const like=`%${q}%`;where.push('(p.name LIKE ? OR ep.personnel_no LIKE ? OR ec.contract_no LIKE ?)');params.push(like,like,like)}if(status){where.push('ec.status=?');params.push(status)}const sql=where.join(' AND ');const [[count]]=await pool.execute(`SELECT COUNT(*) total FROM employment_contracts ec JOIN parties p ON p.id=ec.employee_party_id JOIN employee_profiles ep ON ep.party_id=p.id WHERE ${sql}`,params);const [rows]=await pool.query(`SELECT ec.*,p.name employee_name,ep.personnel_no,d.title department_title,pos.title position_title FROM employment_contracts ec JOIN parties p ON p.id=ec.employee_party_id JOIN employee_profiles ep ON ep.party_id=p.id LEFT JOIN departments d ON d.id=ep.department_id LEFT JOIN positions pos ON pos.id=ep.position_id WHERE ${sql} ORDER BY ec.start_date DESC,ec.id DESC LIMIT ${size} OFFSET ${offset}`,params);res.json(paged?{rows,total:n(count.total),page:current,pageSize:size}:rows)}));

 app.get('/api/iran/payroll/attendance',requireRole('HR_MANAGER','FINANCE_MANAGER'),wrap(async(req,res)=>{const year=n(req.query.yearNo),month=n(req.query.monthNo),q=txt(req.query.q),where=['ams.company_id=?'],params=[req.user.companyId];if(year){where.push('ams.year_no=?');params.push(year)}if(month){where.push('ams.month_no=?');params.push(month)}if(q){const like=`%${q}%`;where.push('(p.name LIKE ? OR ep.personnel_no LIKE ?)');params.push(like,like)}const [rows]=await pool.execute(`SELECT ams.*,p.name employee_name,ep.personnel_no FROM attendance_monthly_summaries ams JOIN parties p ON p.id=ams.employee_party_id JOIN employee_profiles ep ON ep.party_id=p.id WHERE ${where.join(' AND ')} ORDER BY ams.year_no DESC,ams.month_no DESC,ep.personnel_no`,params);res.json(rows)}));
 app.post('/api/iran/payroll/attendance',requireRole('HR_MANAGER'),wrap(async(req,res)=>{const b=req.body||{};if(!b.employeePartyId||n(b.yearNo)<1300||n(b.monthNo)<1||n(b.monthNo)>12)fail('کارمند، سال و ماه الزامی است.');await pool.execute(`INSERT INTO attendance_monthly_summaries(company_id,employee_party_id,year_no,month_no,calendar_days,work_days,paid_leave_days,unpaid_leave_days,absence_days,overtime_hours,night_hours,friday_hours,mission_days,status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,'APPROVED') ON DUPLICATE KEY UPDATE calendar_days=VALUES(calendar_days),work_days=VALUES(work_days),paid_leave_days=VALUES(paid_leave_days),unpaid_leave_days=VALUES(unpaid_leave_days),absence_days=VALUES(absence_days),overtime_hours=VALUES(overtime_hours),night_hours=VALUES(night_hours),friday_hours=VALUES(friday_hours),mission_days=VALUES(mission_days),status='APPROVED'`,[req.user.companyId,b.employeePartyId,n(b.yearNo),n(b.monthNo),n(b.calendarDays)||30,n(b.workDays)||0,n(b.paidLeaveDays),n(b.unpaidLeaveDays),n(b.absenceDays),n(b.overtimeHours),n(b.nightHours),n(b.fridayHours),n(b.missionDays)]);await audit(req,'UPSERT','attendance',`${b.employeePartyId}-${b.yearNo}-${b.monthNo}`,b);res.json({ok:true})}));

 app.get('/api/iran/payroll/loans',requireRole('HR_MANAGER','FINANCE_MANAGER'),wrap(async(req,res)=>{const status=txt(req.query.status),q=txt(req.query.q),where=['el.company_id=?'],params=[req.user.companyId];if(status){where.push('el.status=?');params.push(status)}if(q){const like=`%${q}%`;where.push('(p.name LIKE ? OR ep.personnel_no LIKE ? OR el.loan_no LIKE ?)');params.push(like,like,like)}const [rows]=await pool.execute(`SELECT el.*,p.name employee_name,ep.personnel_no FROM employee_loans el JOIN parties p ON p.id=el.employee_party_id JOIN employee_profiles ep ON ep.party_id=p.id WHERE ${where.join(' AND ')} ORDER BY el.start_date DESC,el.id DESC`,params);res.json(rows)}));
 app.post('/api/iran/payroll/loans',requireRole('HR_MANAGER','FINANCE_MANAGER'),wrap(async(req,res)=>{const b=req.body||{};if(!b.employeePartyId||!txt(b.loanNo)||n(b.principalAmount)<=0||n(b.installmentAmount)<=0||!b.startDate)fail('اطلاعات وام/مساعده کامل نیست.');const [r]=await pool.execute(`INSERT INTO employee_loans(company_id,employee_party_id,loan_no,loan_type,principal_amount,installment_amount,start_date,end_date,remaining_amount,status,description) VALUES (?,?,?,?,?,?,?,?,?,'ACTIVE',?)`,[req.user.companyId,b.employeePartyId,b.loanNo,b.loanType||'LOAN',n(b.principalAmount),n(b.installmentAmount),b.startDate,b.endDate||null,n(b.principalAmount),b.description||null]);await audit(req,'CREATE','employee_loan',r.insertId,b);res.status(201).json({id:r.insertId})}));

 app.post('/api/iran/payroll/legal-parameters',requireRole('FINANCE_MANAGER','HR_MANAGER'),wrap(async(req,res)=>{const b=req.body||{},year=n(b.jalaliYear);if(year<1300||!b.effectiveFrom||!b.parameters)fail('سال شمسی، تاریخ اثر و پارامترها الزامی است.');const params=typeof b.parameters==='object'?b.parameters:json(b.parameters);const result=await withTransaction(async conn=>{if(b.deactivatePrevious!==false)await conn.execute(`UPDATE payroll_legal_parameters SET is_active=0 WHERE company_id=? AND jalali_year=?`,[req.user.companyId,year]);const [r]=await conn.execute(`INSERT INTO payroll_legal_parameters(company_id,title,jalali_year,effective_from,effective_to,parameters_json,legal_reference,is_active) VALUES (?,?,?,?,?,?,?,1)`,[req.user.companyId,b.title||`پارامترهای حقوق ${year}`,year,b.effectiveFrom,b.effectiveTo||null,JSON.stringify(params),b.legalReference||null]);return{id:r.insertId}});await audit(req,'CREATE','payroll_legal_parameter',result.id,b);res.status(201).json(result)}));
}