import crypto from 'node:crypto';
import { pool } from './db.js';
import { requireRole } from './auth.js';
const n=v=>Number(v||0),txt=v=>String(v??'').trim();
const fail=(m,s=400,d=null)=>{const e=new Error(m);e.status=s;e.details=d;throw e};
const wrap=fn=>async(req,res)=>{try{await fn(req,res)}catch(e){console.error('security v5 error',e);res.status(e.status||400).json({error:e.message,details:e.details||undefined})}};
export function registerSecurityV5Routes(app){
 app.get('/api/iran/security/sod-rules',requireRole('SUPER_ADMIN','FINANCE_MANAGER'),wrap(async(req,res)=>{const [r]=await pool.execute(`SELECT * FROM segregation_of_duties_rules WHERE company_id=? OR company_id IS NULL ORDER BY severity DESC,title_fa`,[req.user.companyId]);res.json(r)}));
 app.post('/api/iran/security/sod-rules',requireRole('SUPER_ADMIN'),wrap(async(req,res)=>{const b=req.body||{};if(!txt(b.code)||!txt(b.title)||!txt(b.roleA)||!txt(b.roleB))fail('کد، عنوان و دو نقش متعارض الزامی است.');await pool.execute(`INSERT INTO segregation_of_duties_rules(company_id,code,title_fa,role_a,role_b,severity,action,is_active) VALUES (?,?,?,?,?,?,?,1) ON DUPLICATE KEY UPDATE title_fa=VALUES(title_fa),role_a=VALUES(role_a),role_b=VALUES(role_b),severity=VALUES(severity),action=VALUES(action),is_active=1`,[req.user.companyId,b.code,b.title,b.roleA,b.roleB,b.severity||'HIGH',b.action||'BLOCK']);res.json({ok:true})}));
 app.get('/api/iran/security/sod-conflicts',requireRole('SUPER_ADMIN','FINANCE_MANAGER'),wrap(async(req,res)=>{const [r]=await pool.execute(`SELECT s.code,s.title_fa,s.severity,s.action,u.id user_id,u.full_name,u.email,s.role_a,s.role_b FROM segregation_of_duties_rules s JOIN roles ra ON ra.code=s.role_a JOIN roles rb ON rb.code=s.role_b JOIN user_roles ura ON ura.role_id=ra.id JOIN user_roles urb ON urb.role_id=rb.id AND urb.user_id=ura.user_id JOIN users u ON u.id=ura.user_id WHERE s.is_active=1 AND (s.company_id=? OR s.company_id IS NULL) AND u.company_id=? AND u.is_active=1 ORDER BY FIELD(s.severity,'CRITICAL','HIGH','WARNING'),u.full_name`,[req.user.companyId,req.user.companyId]);res.json(r)}));

 app.get('/api/iran/security/field-policies',requireRole('SUPER_ADMIN'),wrap(async(req,res)=>{const [r]=await pool.execute(`SELECT * FROM field_access_policies WHERE company_id=? OR company_id IS NULL ORDER BY entity_type,field_name,role_code`,[req.user.companyId]);res.json(r)}));
 app.post('/api/iran/security/field-policies',requireRole('SUPER_ADMIN'),wrap(async(req,res)=>{const b=req.body||{};if(!txt(b.entityType)||!txt(b.fieldName)||!txt(b.roleCode))fail('موجودیت، فیلد و نقش الزامی است.');await pool.execute(`INSERT INTO field_access_policies(company_id,entity_type,field_name,role_code,access_mode,mask_pattern) VALUES (?,?,?,?,?,?) ON DUPLICATE KEY UPDATE access_mode=VALUES(access_mode),mask_pattern=VALUES(mask_pattern)`,[req.user.companyId,b.entityType,b.fieldName,b.roleCode,b.accessMode||'MASKED',b.maskPattern||null]);res.json({ok:true})}));

 app.get('/api/iran/security/export-policies',requireRole('SUPER_ADMIN','FINANCE_MANAGER'),wrap(async(req,res)=>{const [r]=await pool.execute(`SELECT * FROM export_policies WHERE company_id=? OR company_id IS NULL ORDER BY role_code,domain_code`,[req.user.companyId]);res.json(r)}));
 app.post('/api/iran/security/export-policies',requireRole('SUPER_ADMIN'),wrap(async(req,res)=>{const b=req.body||{};if(!txt(b.roleCode)||!txt(b.domainCode))fail('نقش و حوزه گزارش الزامی است.');await pool.execute(`INSERT INTO export_policies(company_id,role_code,domain_code,can_export,max_rows,require_reason,require_approval,watermark_exports) VALUES (?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE can_export=VALUES(can_export),max_rows=VALUES(max_rows),require_reason=VALUES(require_reason),require_approval=VALUES(require_approval),watermark_exports=VALUES(watermark_exports)`,[req.user.companyId,b.roleCode,b.domainCode,b.canExport?1:0,Math.max(1,n(b.maxRows)||10000),b.requireReason===false?0:1,b.requireApproval?1:0,b.watermarkExports===false?0:1]);res.json({ok:true})}));
 app.post('/api/iran/security/export-authorize',wrap(async(req,res)=>{const b=req.body||{},domain=txt(b.domainCode),rows=Math.max(0,n(b.rowCount));if(!domain)fail('حوزه خروجی الزامی است.');const roles=req.user.roles||[];if(roles.includes('SUPER_ADMIN')){const [a]=await pool.execute(`INSERT INTO export_audit_logs(company_id,user_id,domain_code,report_code,row_count,reason,filters_json,file_hash) VALUES (?,?,?,?,?,?,?,?)`,[req.user.companyId,Number(req.user.sub),domain,b.reportCode||null,rows,b.reason||'دسترسی مدیر سیستم',JSON.stringify(b.filters||{}),null]);return res.json({allowed:true,auditId:a.insertId,maxRows:rows,watermark:true})}const placeholders=roles.map(()=>'?').join(',');if(!placeholders)fail('هیچ نقش فعالی برای کاربر تعریف نشده است.',403);const [p]=await pool.execute(`SELECT * FROM export_policies WHERE (company_id=? OR company_id IS NULL) AND domain_code=? AND role_code IN (${placeholders}) AND can_export=1 ORDER BY max_rows DESC LIMIT 1`,[req.user.companyId,domain,...roles]);if(!p.length)fail('مجوز خروجی برای این حوزه ندارید.',403);const policy=p[0];if(rows>n(policy.max_rows))fail('تعداد ردیف از سقف مجاز خروجی بیشتر است.',403,{maxRows:n(policy.max_rows)});if(policy.require_reason&&!txt(b.reason))fail('ثبت دلیل خروجی الزامی است.',422);if(policy.require_approval)fail('این خروجی نیازمند تأیید جداگانه است.',409,{approvalRequired:true});const token=crypto.randomBytes(24).toString('hex'),[a]=await pool.execute(`INSERT INTO export_audit_logs(company_id,user_id,domain_code,report_code,row_count,reason,filters_json,file_hash) VALUES (?,?,?,?,?,?,?,?)`,[req.user.companyId,Number(req.user.sub),domain,b.reportCode||null,rows,b.reason||null,JSON.stringify(b.filters||{}),null]);res.json({allowed:true,auditId:a.insertId,authorizationToken:token,maxRows:n(policy.max_rows),watermark:!!policy.watermark_exports})}));
 app.get('/api/iran/security/export-audit',requireRole('SUPER_ADMIN','FINANCE_MANAGER'),wrap(async(req,res)=>{const [r]=await pool.execute(`SELECT e.*,u.full_name FROM export_audit_logs e JOIN users u ON u.id=e.user_id WHERE e.company_id=? ORDER BY e.exported_at DESC LIMIT 500`,[req.user.companyId]);res.json(r)}));
}
