import crypto from 'node:crypto';
import { pool } from './db.js';
import { requireRole } from './auth.js';
const n=v=>Number(v||0),txt=v=>String(v??'').trim(),fail=(m,s=400,d=null)=>{const e=new Error(m);e.status=s;e.details=d;throw e},wrap=fn=>async(req,res)=>{try{await fn(req,res)}catch(e){console.error('unified statement v7 error',e);res.status(e.status||400).json({error:e.message,details:e.details||undefined})}};
function tok(expr){const s=txt(expr),o=[];let i=0;while(i<s.length){if(/\s/.test(s[i])){i++;continue}const m=s.slice(i).match(/^([A-Za-z][A-Za-z0-9_]*|\d+(?:\.\d+)?|[()+\-*/])/);if(!m)fail('فرمول صورت مالی نامعتبر است.',422,{expression:s,at:i});o.push(m[1]);i+=m[1].length}return o}
function calc(expr,vals){const ts=tok(expr),pr={'+':1,'-':1,'*':2,'/':2},out=[],ops=[];let prev=null;for(const t of ts){if(/^\d/.test(t)||/^[A-Za-z]/.test(t)){out.push(t);prev='v'}else if(t==='('){ops.push(t);prev='('}else if(t===')'){while(ops.length&&ops.at(-1)!=='(')out.push(ops.pop());if(ops.pop()!=='(')fail('پرانتز فرمول نامعتبر است.',422);prev='v'}else{if(t==='-'&&(prev==null||prev==='op'||prev==='('))out.push('0');while(ops.length&&pr[ops.at(-1)]>=pr[t])out.push(ops.pop());ops.push(t);prev='op'}}while(ops.length){const x=ops.pop();if(x==='(')fail('پرانتز فرمول بسته نشده است.',422);out.push(x)}const st=[];for(const t of out){if(/^\d/.test(t))st.push(Number(t));else if(/^[A-Za-z]/.test(t)){if(!vals.has(t))fail(`کد سطر ${t} در فرمول پیدا نشد.`,422);st.push(n(vals.get(t)))}else{const b=st.pop(),a=st.pop();if(a==null||b==null)fail('فرمول ناقص است.',422);if(t==='+')st.push(a+b);else if(t==='-')st.push(a-b);else if(t==='*')st.push(a*b);else{if(Math.abs(b)<1e-12)fail('تقسیم بر صفر در فرمول صورت مالی.',422);st.push(a/b)}}}if(st.length!==1)fail('فرمول قابل محاسبه نیست.',422);return st[0]}
async function scope(c,date){const [fy]=await pool.execute(`SELECT * FROM fiscal_years WHERE company_id=? AND ? BETWEEN start_date AND end_date ORDER BY start_date DESC LIMIT 1`,[c,date]);if(!fy.length)return{from:'1900-01-01',fy:null,opening:false};const y=fy[0],[op]=await pool.execute(`SELECT id FROM journal_entries WHERE company_id=? AND source_type='YEAR_OPENING' AND status IN ('POSTED','LOCKED') AND COALESCE(posting_date,entry_date) BETWEEN ? AND ? LIMIT 1`,[c,y.start_date,y.end_date]);return{from:op.length?String(y.start_date).slice(0,10):'1900-01-01',fy:y,opening:!!op.length}}
async function earnings(c,fy,asOf){if(!fy)return 0;const [cl]=await pool.execute(`SELECT id FROM year_end_close_runs WHERE company_id=? AND fiscal_year_id=? AND status IN ('POSTED','OPENING_POSTED') AND posted_at IS NOT NULL LIMIT 1`,[c,fy.id]);if(cl.length&&String(asOf)>=String(fy.end_date).slice(0,10))return 0;const [[x]]=await pool.execute(`SELECT COALESCE(SUM(CASE WHEN a.account_type='REVENUE' THEN jl.credit-jl.debit WHEN a.account_type='EXPENSE' THEN -(jl.debit-jl.credit) ELSE 0 END),0) value FROM journal_lines jl JOIN journal_entries je ON je.id=jl.journal_entry_id JOIN accounts a ON a.id=jl.account_id WHERE je.company_id=? AND je.status IN ('POSTED','LOCKED') AND je.source_type<>'YEAR_END_CLOSE' AND a.account_type IN ('REVENUE','EXPENSE') AND COALESCE(je.posting_date,je.entry_date) BETWEEN ? AND ?`,[c,String(fy.start_date).slice(0,10),asOf]);return n(x.value)}
async function amount(c,line,from,to,excludeClose){const [[x]]=await pool.execute(`SELECT COALESCE(SUM(jl.debit),0) debit,COALESCE(SUM(jl.credit),0) credit FROM financial_statement_account_maps m JOIN journal_lines jl ON jl.account_id=m.account_id JOIN journal_entries je ON je.id=jl.journal_entry_id WHERE m.statement_line_id=? AND m.company_id=? AND je.company_id=? AND je.status IN ('POSTED','LOCKED') ${excludeClose?"AND je.source_type<>'YEAR_END_CLOSE'":''} AND COALESCE(je.posting_date,je.entry_date) BETWEEN ? AND ?`,[line.id,c,c,from,to]);return line.normal_sign==='CREDIT'?n(x.credit)-n(x.debit):n(x.debit)-n(x.credit)}
async function sourceHash(c,from,to,excludeClose){const [[x]]=await pool.execute(`SELECT COUNT(*) rows_count,COALESCE(SUM(jl.debit),0) debit,COALESCE(SUM(jl.credit),0) credit,COALESCE(MAX(jl.id),0) max_line FROM journal_lines jl JOIN journal_entries je ON je.id=jl.journal_entry_id WHERE je.company_id=? AND je.status IN ('POSTED','LOCKED') ${excludeClose?"AND je.source_type<>'YEAR_END_CLOSE'":''} AND COALESCE(je.posting_date,je.entry_date) BETWEEN ? AND ?`,[c,from,to]);return crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex')}
export function registerStatementRenderUnifiedV7(app){
 app.get('/api/iran/finance/statement-templates/:id/render',requireRole('ACCOUNTANT','FINANCE_MANAGER'),wrap(async(req,res)=>{const id=Number(req.params.id),[tr]=await pool.execute(`SELECT * FROM financial_statement_templates WHERE id=? AND company_id=? AND is_active=1`,[id,req.user.companyId]);if(!tr.length)fail('قالب صورت مالی پیدا نشد.',404);const t=tr[0],asOf=txt(req.query.asOf)||txt(req.query.dateTo);if(!asOf)fail('تاریخ گزارش الزامی است.');const performance=['PROFIT_LOSS','EQUITY_CHANGES'].includes(t.statement_type);let from='1900-01-01',sc={fy:null,opening:false};if(t.statement_type==='BALANCE_SHEET'){sc=await scope(req.user.companyId,asOf);from=sc.from}else if(performance){from=txt(req.query.periodStart)||txt(req.query.dateFrom);if(!from)fail('ابتدای دوره برای این صورت مالی الزامی است.')}else if(txt(req.query.periodStart)||txt(req.query.dateFrom))from=txt(req.query.periodStart)||txt(req.query.dateFrom);const [ls]=await pool.execute('SELECT * FROM financial_statement_lines WHERE template_id=? ORDER BY sort_order,id',[id]),vals=new Map(),rows=[];for(const l of ls){let value=0;if(l.line_type==='ACCOUNT_SUM')value=await amount(req.user.companyId,l,from,asOf,performance);else if(l.line_code==='CURRENT_EARNINGS'&&t.statement_type==='BALANCE_SHEET')value=await earnings(req.user.companyId,sc.fy,asOf);else if(['FORMULA','SUBTOTAL','TOTAL'].includes(l.line_type)&&txt(l.formula_text))value=calc(l.formula_text,vals);vals.set(l.line_code,value);rows.push({id:l.id,lineCode:l.line_code,title:l.title_fa,lineType:l.line_type,value,displayLevel:l.display_level,isBold:!!l.is_bold,sortOrder:l.sort_order})}const [unmapped]=await pool.execute(`SELECT a.id,a.code,a.title,a.account_type,a.statement_section FROM accounts a WHERE a.company_id=? AND a.is_active=1 AND a.allow_posting=1 AND a.id NOT IN (SELECT m.account_id FROM financial_statement_account_maps m JOIN financial_statement_lines l ON l.id=m.statement_line_id WHERE l.template_id=? AND m.company_id=?) ORDER BY a.code`,[req.user.companyId,id,req.user.companyId]);res.json({template:t,from,asOf,hasOpeningEntry:sc.opening,lines:rows,unmappedAccounts:unmapped,sourceHash:await sourceHash(req.user.companyId,from,asOf,performance),excludedSystemSources:performance?['YEAR_END_CLOSE']:[]})}));
}
