import crypto from 'node:crypto';
import { pool } from './db.js';
import { requireRole } from './auth.js';
const n=v=>Number(v||0),txt=v=>String(v??'').trim(),fail=(m,s=400,d=null)=>{const e=new Error(m);e.status=s;e.details=d;throw e},wrap=fn=>async(req,res)=>{try{await fn(req,res)}catch(e){console.error('statement render v7 override',e);res.status(e.status||400).json({error:e.message,details:e.details||undefined})}};
function tokenize(expr){const s=txt(expr),o=[];let i=0;while(i<s.length){if(/\s/.test(s[i])){i++;continue}const m=s.slice(i).match(/^([A-Za-z][A-Za-z0-9_]*|\d+(?:\.\d+)?|[()+\-*/])/);if(!m)fail('فرمول گزارش نامعتبر است.',422,{expression:s,at:i});o.push(m[1]);i+=m[1].length}return o}
function evalFormula(expr,vals){const ts=tokenize(expr),prec={'+':1,'-':1,'*':2,'/':2},out=[],ops=[];let prev=null;for(const t of ts){if(/^\d/.test(t)||/^[A-Za-z]/.test(t)){out.push(t);prev='v'}else if(t==='('){ops.push(t);prev='('}else if(t===')'){while(ops.length&&ops.at(-1)!=='(')out.push(ops.pop());if(ops.pop()!=='(')fail('پرانتز فرمول نامعتبر است.',422);prev='v'}else{if(t==='-'&&(prev==null||prev==='op'||prev==='('))out.push('0');while(ops.length&&prec[ops.at(-1)]>=prec[t])out.push(ops.pop());ops.push(t);prev='op'}}while(ops.length){const x=ops.pop();if(x==='(')fail('پرانتز فرمول بسته نشده است.',422);out.push(x)}const st=[];for(const t of out){if(/^\d/.test(t))st.push(Number(t));else if(/^[A-Za-z]/.test(t)){if(!vals.has(t))fail(`کد سطر ${t} شناخته‌شده نیست.`,422);st.push(n(vals.get(t)))}else{const b=st.pop(),a=st.pop();if(a==null||b==null)fail('فرمول ناقص است.',422);st.push(t==='+'?a+b:t==='-'?a-b:t==='*'?a*b:(Math.abs(b)<1e-12?(()=>{throw Object.assign(new Error('تقسیم بر صفر در فرمول صورت مالی.'),{status:422})})():a/b))}}if(st.length!==1)fail('فرمول قابل محاسبه نیست.',422);return st[0]}
async function fiscalStart(c,asOf){const [r]=await pool.execute(`SELECT start_date FROM fiscal_years WHERE company_id=? AND ? BETWEEN start_date AND end_date ORDER BY start_date DESC LIMIT 1`,[c,asOf]);return r[0]?.start_date?String(r[0].start_date).slice(0,10):'1900-01-01'}
async function lineAmount(c,line,from,to,excludeClose){const [r]=await pool.execute(`SELECT COALESCE(SUM(jl.debit),0) debit,COALESCE(SUM(jl.credit),0) credit FROM financial_statement_account_maps m JOIN journal_lines jl ON jl.account_id=m.account_id JOIN journal_entries je ON je.id=jl.journal_entry_id WHERE m.statement_line_id=? AND m.company_id=? AND je.company_id=? AND je.status IN ('POSTED','LOCKED') ${excludeClose?"AND je.source_type<>'YEAR_END_CLOSE'":''} AND COALESCE(je.posting_date,je.entry_date) BETWEEN ? AND ?`,[line.id,c,c,from,to]);const x=r[0]||{};return line.normal_sign==='CREDIT'?n(x.credit)-n(x.debit):n(x.debit)-n(x.credit)}
async function earning(c,from,to){const [[x]]=await pool.execute(`SELECT COALESCE(SUM(CASE WHEN a.account_type='REVENUE' THEN jl.credit-jl.debit WHEN a.account_type='EXPENSE' THEN -(jl.debit-jl.credit) ELSE 0 END),0) value FROM journal_lines jl JOIN journal_entries je ON je.id=jl.journal_entry_id JOIN accounts a ON a.id=jl.account_id WHERE je.company_id=? AND je.status IN ('POSTED','LOCKED') AND je.source_type<>'YEAR_END_CLOSE' AND a.account_type IN ('REVENUE','EXPENSE') AND COALESCE(je.posting_date,je.entry_date) BETWEEN ? AND ?`,[c,from,to]);return n(x.value)}
async function hash(c,from,to,excludeClose){const [[x]]=await pool.execute(`SELECT COUNT(*) rows_count,COALESCE(SUM(jl.debit),0) debit,COALESCE(SUM(jl.credit),0) credit,COALESCE(MAX(jl.id),0) max_line FROM journal_lines jl JOIN journal_entries je ON je.id=jl.journal_entry_id WHERE je.company_id=? AND je.status IN ('POSTED','LOCKED') ${excludeClose?"AND je.source_type<>'YEAR_END_CLOSE'":''} AND COALESCE(je.posting_date,je.entry_date) BETWEEN ? AND ?`,[c,from,to]);return crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex')}
export function registerStatementRenderOverrideV7(app){
 app.get('/api/iran/finance/statement-templates/:id/render',requireRole('ACCOUNTANT','FINANCE_MANAGER'),wrap(async(req,res)=>{const id=Number(req.params.id),[tr]=await pool.execute(`SELECT * FROM financial_statement_templates WHERE id=? AND company_id=? AND is_active=1`,[id,req.user.companyId]);if(!tr.length)fail('قالب صورت مالی پیدا نشد.',404);const t=tr[0],asOf=txt(req.query.asOf)||txt(req.query.dateTo);if(!asOf)fail('تاریخ گزارش الزامی است.');let from='1900-01-01';const performance=['PROFIT_LOSS','EQUITY_CHANGES'].includes(t.statement_type);if(performance){from=txt(req.query.periodStart)||txt(req.query.dateFrom);if(!from)fail('ابتدای دوره برای این صورت مالی الزامی است.')}const fyStart=t.statement_type==='BALANCE_SHEET'?await fiscalStart(req.user.companyId,asOf):from,[ls]=await pool.execute('SELECT * FROM financial_statement_lines WHERE template_id=? ORDER BY sort_order,id',[id]),vals=new Map(),rendered=[];for(const l of ls){let value=0;if(l.line_type==='ACCOUNT_SUM')value=await lineAmount(req.user.companyId,l,from,asOf,performance);else if(l.line_code==='CURRENT_EARNINGS'&&t.statement_type==='BALANCE_SHEET')value=await earning(req.user.companyId,fyStart,asOf);else if(['FORMULA','SUBTOTAL','TOTAL'].includes(l.line_type)&&txt(l.formula_text))value=evalFormula(l.formula_text,vals);vals.set(l.line_code,value);rendered.push({id:l.id,lineCode:l.line_code,title:l.title_fa,lineType:l.line_type,value,displayLevel:l.display_level,isBold:!!l.is_bold,sortOrder:l.sort_order})}const [unmapped]=await pool.execute(`SELECT a.id,a.code,a.title,a.account_type,a.statement_section FROM accounts a WHERE a.company_id=? AND a.is_active=1 AND a.allow_posting=1 AND a.id NOT IN (SELECT m.account_id FROM financial_statement_account_maps m JOIN financial_statement_lines l ON l.id=m.statement_line_id WHERE l.template_id=? AND m.company_id=?) ORDER BY a.code`,[req.user.companyId,id,req.user.companyId]);res.json({template:t,from,asOf,lines:rendered,unmappedAccounts:unmapped,sourceHash:await hash(req.user.companyId,from,asOf,performance),excludedSystemSources:performance?['YEAR_END_CLOSE']:[]})}));
}
