import { pool, withTransaction } from './db.js';
import { requireRole } from './auth.js';
import { reserveFulfillment,pickFulfillment,releaseFulfillmentAllocations } from './inventory_allocation_v5.js';
const fail=(m,s=400)=>{const e=new Error(m);e.status=s;throw e};const wrap=fn=>async(req,res)=>{try{await fn(req,res)}catch(e){console.error('wms fulfillment v5 error',e);res.status(e.status||400).json({error:e.message,details:e.details||undefined})}};
export function registerWmsFulfillmentV5Routes(app){
 app.put('/api/iran/accounting-policy',requireRole('FINANCE_MANAGER'),wrap(async(req,res)=>{const b=req.body||{};const picking=b.defaultPickingStrategy||null;if(picking&&!['FIFO','FEFO','MANUAL'].includes(picking))fail('روش برداشت کالا معتبر نیست.',422);await pool.execute(`UPDATE company_accounting_policies SET inventory_valuation=COALESCE(?,inventory_valuation),revenue_recognition=COALESCE(?,revenue_recognition),inventory_issue_policy=COALESCE(?,inventory_issue_policy),allow_negative_inventory=COALESCE(?,allow_negative_inventory),fiscal_calendar=COALESCE(?,fiscal_calendar),base_currency_code=COALESCE(?,base_currency_code),reporting_currency_code=COALESCE(?,reporting_currency_code),default_picking_strategy=COALESCE(?,default_picking_strategy),block_expired_inventory=COALESCE(?,block_expired_inventory),near_expiry_days=COALESCE(?,near_expiry_days),updated_by=? WHERE company_id=?`,[b.inventoryValuation||null,b.revenueRecognition||null,b.inventoryIssuePolicy||null,b.allowNegativeInventory==null?null:(b.allowNegativeInventory?1:0),b.fiscalCalendar||null,b.baseCurrencyCode||null,b.reportingCurrencyCode||null,picking,b.blockExpiredInventory==null?null:(b.blockExpiredInventory?1:0),b.nearExpiryDays==null?null:Math.max(1,Number(b.nearExpiryDays||30)),Number(req.user.sub),req.user.companyId]);res.json({ok:true})}));
 app.get('/api/iran/sales/fulfillments/:id/allocations',requireRole('WAREHOUSE_MANAGER','SALES_MANAGER','FINANCE_MANAGER'),wrap(async(req,res)=>{const id=Number(req.params.id);const [r]=await pool.execute(`SELECT a.*,p.sku,p.name product_name,w.name warehouse_name FROM sales_fulfillment_allocations a JOIN products p ON p.id=a.product_id JOIN sales_fulfillments f ON f.id=a.fulfillment_id JOIN warehouses w ON w.id=f.warehouse_id WHERE a.fulfillment_id=? AND a.company_id=? ORDER BY a.fulfillment_line_id,a.expiry_date IS NULL,a.expiry_date,a.id`,[id,req.user.companyId]);res.json(r)}));
 app.post('/api/iran/sales/fulfillments/:id/reserve',requireRole('WAREHOUSE_MANAGER','SALES_MANAGER'),wrap(async(req,res)=>{const id=Number(req.params.id),r=await withTransaction(async conn=>{const [fs]=await conn.execute('SELECT * FROM sales_fulfillments WHERE id=? AND company_id=? FOR UPDATE',[id,req.user.companyId]);if(!fs.length)fail('فرآیند آماده‌سازی پیدا نشد.',404);if(!['DRAFT','RESERVED'].includes(fs[0].status))fail('وضعیت برای رزرو مناسب نیست.',422);return reserveFulfillment(conn,fs[0],req.user.companyId)});res.json(r)}));
 app.post('/api/iran/sales/fulfillments/:id/pick',requireRole('WAREHOUSE_MANAGER'),wrap(async(req,res)=>{const id=Number(req.params.id),r=await withTransaction(async conn=>{const [fs]=await conn.execute('SELECT * FROM sales_fulfillments WHERE id=? AND company_id=? FOR UPDATE',[id,req.user.companyId]);if(!fs.length||!['RESERVED','PICKING','PICKED'].includes(fs[0].status))fail('فرآیند در وضعیت قابل برداشت نیست.',422);return pickFulfillment(conn,fs[0],req.user.companyId,req.body?.lines||[])});res.json(r)}));
 app.post('/api/iran/sales/fulfillments/:id/release',requireRole('WAREHOUSE_MANAGER','SALES_MANAGER'),wrap(async(req,res)=>{const id=Number(req.params.id),r=await withTransaction(async conn=>{const [fs]=await conn.execute('SELECT * FROM sales_fulfillments WHERE id=? AND company_id=? FOR UPDATE',[id,req.user.companyId]);if(!fs.length)fail('فرآیند پیدا نشد.',404);if(['ISSUED','DELIVERED'].includes(fs[0].status))fail('پس از خروج/تحویل امکان آزادسازی رزرو وجود ندارد.',422);const x=await releaseFulfillmentAllocations(conn,id);await conn.execute(`UPDATE sales_fulfillment_lines SET reserved_qty=0,picked_qty=0 WHERE fulfillment_id=?`,[id]);await conn.execute(`UPDATE sales_fulfillments SET status='DRAFT',reserved_at=NULL,picked_at=NULL WHERE id=?`,[id]);await conn.execute(`UPDATE sales_invoices SET fulfillment_status='DRAFT' WHERE id=?`,[fs[0].sales_invoice_id]);return{ok:true,status:'DRAFT',...x}});res.json(r)}));
}
