import crypto from 'node:crypto';
const base=process.env.TARAZPAD_URL||'http://127.0.0.1:8080',email=process.env.TARAZPAD_ADMIN_EMAIL||'phase14@tarazpad.test',password=process.env.TARAZPAD_ADMIN_PASSWORD||'Strong_Phase14_2026!';
const log=(s,d='')=>console.log(`[PHASE14] ${s}${d?` :: ${typeof d==='string'?d:JSON.stringify(d)}`:''}`),assert=(v,m,d)=>{if(!v){const e=new Error(m);e.data=d;throw e}};
async function req(p,{token,method='GET',body}={}){const r=await fetch(base+p,{method,headers:{...(token?{authorization:`Bearer ${token}`}:{}) ,...(body!==undefined?{'content-type':'application/json'}:{})},body:body===undefined?undefined:JSON.stringify(body)}),t=await r.text();let d;try{d=JSON.parse(t)}catch{d=t}if(!r.ok){const e=new Error(`${method} ${p} -> ${r.status} ${typeof d==='string'?d:JSON.stringify(d)}`);e.data=d;throw e}return d}
async function login(e,p){const x=await req('/api/auth/login',{method:'POST',body:{email:e,password:p}});assert(x.token,'توکن ورود دریافت نشد',x);return x.token}
async function main(){
 const admin=await login(email,password),stamp=Date.now().toString().slice(-7);log('LOGIN_OK');
 const crmEmail=`crm${stamp}@tarazpad.test`,salesEmail=`sales14${stamp}@tarazpad.test`,dmsEmail=`dms${stamp}@tarazpad.test`;
 const crmU=await req('/api/iran/admin/users',{token:admin,method:'POST',body:{fullName:'مدیر CRM تست',email:crmEmail,password:'Strong_CRM14_2026!',roleCodes:['CRM_MANAGER','CUSTOMER_SERVICE','BPM_MANAGER']}}),salesU=await req('/api/iran/admin/users',{token:admin,method:'POST',body:{fullName:'فروشنده CRM تست',email:salesEmail,password:'Strong_Sales14_2026!',roleCodes:['SALES_PERSON']}}),dmsU=await req('/api/iran/admin/users',{token:admin,method:'POST',body:{fullName:'مدیر اسناد تست',email:dmsEmail,password:'Strong_DMS14_2026!',roleCodes:['DMS_MANAGER']}});const crm=await login(crmEmail,'Strong_CRM14_2026!'),sales=await login(salesEmail,'Strong_Sales14_2026!'),dms=await login(dmsEmail,'Strong_DMS14_2026!');log('USERS_OK');

 const lead=await req('/api/iran/crm/leads',{token:sales,method:'POST',body:{title:'فرصت مشتری جدید',personName:'مشتری آزمایشی',mobile:`0912${stamp}`,source:'وب‌سایت',estimatedValue:5000000,nextActionAt:new Date(Date.now()+86400000).toISOString(),nextActionTitle:'تماس اولیه'}});assert(lead.id,'سرنخ ایجاد نشد',lead);await req(`/api/iran/crm/leads/${lead.id}/status`,{token:sales,method:'PUT',body:{status:'QUALIFIED',nextActionAt:new Date(Date.now()+86400000).toISOString(),nextActionTitle:'ارسال پیشنهاد'}});const conv=await req(`/api/iran/crm/leads/${lead.id}/convert`,{token:crm,method:'POST',body:{partyType:'LEGAL',name:`مشتری CRM ${stamp}`,expectedCloseDate:'2026-09-30',nextActionAt:new Date(Date.now()+86400000).toISOString(),nextActionTitle:'مذاکره',probability:35}});assert(conv.partyId&&conv.opportunityId,'تبدیل سرنخ ناقص است',conv);log('LEAD_CONVERTED',conv);
 const opps=await req('/api/iran/crm/opportunities',{token:crm});assert(opps.some(x=>x.id===conv.opportunityId),'فرصت در پایپ‌لاین نیست',opps);await req(`/api/iran/crm/opportunities/${conv.opportunityId}/stage`,{token:crm,method:'PUT',body:{stage:'PROPOSAL',probability:55,nextActionAt:new Date(Date.now()+172800000).toISOString(),nextActionTitle:'پیگیری پیشنهاد'}});log('PIPELINE_OK');

 const ticket=await req('/api/iran/crm/tickets',{token:crm,method:'POST',body:{partyId:conv.partyId,ticketType:'COMPLAINT',subject:'تست کیفیت خدمت',description:'درخواست رسیدگی',priority:'HIGH',ownerUserId:crmU.id}});assert(ticket.slaHours===24,'SLA اولویت زیاد باید ۲۴ ساعت باشد',ticket);await req(`/api/iran/crm/tickets/${ticket.id}`,{token:crm,method:'PUT',body:{status:'RESOLVED',resolution:'بررسی و رفع شد'}});log('TICKET_SLA_OK');

 // Non-official service invoice for CRM/loyalty and RFM.
 const service=await req('/api/iran/products',{token:admin,method:'POST',body:{sku:`SVC-${stamp}`,name:'خدمت اشتراک تست',productType:'SERVICE',unit:'خدمت',purchasePrice:0,salePrice:100000,vatStatus:'STANDARD',defaultVatRate:10}});const inv=await req('/api/iran/sales-invoices',{token:sales,method:'POST',body:{customerPartyId:conv.partyId,invoiceDate:'2026-08-18',invoiceClassification:'NON_OFFICIAL',settlementType:'CREDIT',salespersonUserId:salesU.id,lines:[{productId:service.id,qty:1,unitPrice:100000}]}});await req(`/api/iran/sales-invoices/${inv.id}/post`,{token:admin,method:'POST',body:{}});log('SALE_FOR_LOYALTY_OK',inv.id);

 await req('/api/iran/loyalty/settings',{token:admin,method:'POST',body:{pointMonetaryValue:1}});await req('/api/iran/loyalty/rules',{token:crm,method:'POST',body:{title:'امتیاز خرید تست',eventType:'SALE',pointsPerAmount:.001,fixedPoints:10,cashbackPercent:1,effectiveFrom:'2026-01-01'}});const loy=await req(`/api/iran/loyalty/process-sale/${inv.id}`,{token:crm,method:'POST',body:{}});assert(loy.pointsEarned===120&&loy.walletEarned===1100,'محاسبه امتیاز/کش‌بک نادرست',loy);const again=await req(`/api/iran/loyalty/process-sale/${inv.id}`,{token:crm,method:'POST',body:{}});assert(again.duplicatePrevented===true,'Idempotency باشگاه عمل نکرد',again);log('LOYALTY_EARN_OK',loy);
 const reward=await req('/api/iran/loyalty/rewards',{token:crm,method:'POST',body:{code:`RW-${stamp}`,title:'کوپن تست',rewardType:'COUPON',pointCost:50,walletCost:0,stockQty:10}});const red=await req('/api/iran/loyalty/redeem',{token:crm,method:'POST',body:{partyId:conv.partyId,rewardId:reward.id,quantity:1,idempotencyKey:`RED-${stamp}`}});assert(red.pointsUsed===50,'مصرف امتیاز نادرست',red);const rfm=await req('/api/iran/loyalty/rfm?asOf=2026-08-31',{token:crm});assert(rfm.rows.some(x=>x.party_id===conv.partyId&&Number(x.frequency)>=1),'RFM مشتری را پیدا نکرد',rfm);log('LOYALTY_RFM_OK');

 const health=await req('/api/iran/crm/health/run',{token:crm,method:'POST',body:{snapshotDate:'2026-08-31'}});assert(health.customers.some(x=>x.partyId===conv.partyId),'Health Score مشتری ساخته نشد',health);const c360=await req(`/api/iran/crm/customer/${conv.partyId}/360`,{token:crm});assert(Number(c360.sales.net_sales)===110000&&c360.health,'Customer 360 ناقص است',c360);log('CUSTOMER_360_OK');

 // BPM + form builder + true maker/checker.
 const def=await req('/api/iran/bpm/definitions',{token:crm,method:'POST',body:{code:`REQ-${stamp}`,title:'گردش درخواست تست',entityType:'FORM_SUBMISSION',status:'ACTIVE',definition:{start:'REVIEW',nodes:[{code:'REVIEW',title:'بازبینی مدیر CRM',type:'APPROVAL',userId:crmU.id,slaHours:24,separationOfDuties:true}]}}});await req(`/api/iran/bpm/definitions/${def.id}/activate`,{token:crm,method:'PUT',body:{}});const form=await req('/api/iran/forms',{token:crm,method:'POST',body:{code:`FORM-${stamp}`,title:'فرم درخواست تست',status:'ACTIVE',bpmDefinitionId:def.id,schema:{fields:[{name:'subject',label:'موضوع',type:'text',required:true},{name:'amount',label:'مبلغ',type:'number',required:true,min:1}]}}});await req(`/api/iran/forms/${form.id}/activate`,{token:crm,method:'PUT',body:{}});const sub=await req(`/api/iran/forms/${form.id}/submit`,{token:sales,method:'POST',body:{data:{subject:'درخواست تست',amount:1000}}});assert(sub.bpmInstanceId,'فرم وارد گردش نشد',sub);const work=await req('/api/iran/bpm/my-work',{token:crm});const wi=work.find(x=>x.bpm_instance_id===sub.bpmInstanceId);assert(wi,'کار BPM به بازبین نرسید',work);const dec=await req(`/api/iran/bpm/work-items/${wi.id}/complete`,{token:crm,method:'POST',body:{decision:'APPROVE',note:'تأیید تست'}});assert(dec.status==='COMPLETED','BPM تکمیل نشد',dec);log('BPM_FORM_SOD_OK');

 // Case management.
 const ca=await req('/api/iran/cases',{token:crm,method:'POST',body:{caseType:'CUSTOMER_COMPLAINT',title:'پرونده تست',priority:'HIGH',ownerUserId:crmU.id,partyId:conv.partyId,actions:[{title:'بررسی علت',responsibleUserId:crmU.id,dueAt:new Date(Date.now()+86400000).toISOString()}]}});const acts=await req(`/api/iran/cases/${ca.id}/actions`,{token:crm});assert(acts.length===1,'اقدام پرونده ساخته نشد',acts);await req(`/api/iran/case-actions/${acts[0].id}/complete`,{token:crm,method:'PUT',body:{evidenceRef:'evidence://case-test',note:'بررسی شد'}});const close=await req(`/api/iran/cases/${ca.id}/close`,{token:crm,method:'PUT',body:{rootCause:'خطای فرایندی تست',resolution:'اصلاح فرایند تست'}});assert(close.status==='CLOSED','پرونده بسته نشد',close);log('CASE_MANAGEMENT_OK');

 // Office correspondence and inbox.
 const letter=await req('/api/iran/office/letters',{token:dms,method:'POST',body:{letterType:'INTERNAL',letterDate:'2026-08-19',subject:'نامه کنترل اتوماسیون',senderText:'واحد اسناد',receiverText:'واحد CRM',confidentiality:'CONFIDENTIAL',urgency:'URGENT',bodyText:'متن آزمون'}});const ref=await req(`/api/iran/office/letters/${letter.id}/refer`,{token:dms,method:'POST',body:{toUserId:crmU.id,instruction:'بررسی و اقدام',dueAt:new Date(Date.now()+86400000).toISOString()}});const inbox=await req('/api/iran/office/inbox',{token:crm});assert(inbox.some(x=>x.id===ref.id),'نامه در کارتابل نیست',inbox);await req(`/api/iran/office/referrals/${ref.id}`,{token:crm,method:'PUT',body:{status:'DONE'}});log('CORRESPONDENCE_OK');

 // Meeting decisions.
 const mt=await req('/api/iran/office/meetings',{token:crm,method:'POST',body:{title:'جلسه کنترل',meetingAt:new Date().toISOString(),location:'اتاق جلسه',agenda:'کنترل فرایند'}});await req(`/api/iran/office/meetings/${mt.id}/close`,{token:crm,method:'POST',body:{minutesText:'جلسه برگزار شد.',actions:[{decisionText:'انجام اقدام تست',responsibleUserId:crmU.id,dueAt:new Date(Date.now()+86400000).toISOString()}]}});const ma=await req(`/api/iran/office/meetings/${mt.id}/actions`,{token:crm});assert(ma.length===1,'مصوبه ساخته نشد',ma);await req(`/api/iran/office/meeting-actions/${ma[0].id}/complete`,{token:crm,method:'PUT',body:{evidenceRef:'evidence://meeting-test'}});log('MEETING_ACTION_OK');

 // DMS versioning and integrity metadata.
 const doc=await req('/api/iran/dms/documents',{token:dms,method:'POST',body:{title:'سند کنترل نسخه',documentClass:'روش اجرایی',confidentiality:'VERY_CONFIDENTIAL',ownerUserId:dmsU.id}}),hash=crypto.createHash('sha256').update('tarazpad-phase14-test').digest('hex');const ver=await req(`/api/iran/dms/documents/${doc.id}/versions`,{token:dms,method:'POST',body:{storageRef:'object://test/doc-v1.pdf',fileName:'doc-v1.pdf',mimeType:'application/pdf',fileSize:1000,sha256:hash,changeNote:'نسخه اول'}});assert(ver.versionNo===1,'نسخه DMS صحیح نیست',ver);const dd=await req(`/api/iran/dms/documents/${doc.id}`,{token:dms});assert(dd.versions[0].sha256===hash,'هش فایل DMS حفظ نشد',dd);log('DMS_VERSIONING_OK');

 // Consent aware campaign + attribution.
 await req(`/api/iran/crm/consent/${conv.partyId}`,{token:crm,method:'PUT',body:{channel:'SMS',consentStatus:'OPT_IN',source:'TEST',frequencyCapPerWeek:2}});const camp=await req('/api/iran/crm/campaigns',{token:crm,method:'POST',body:{code:`CMP-${stamp}`,title:'کمپین تست',channel:'SMS',audienceFilter:{partyIds:[conv.partyId]},content:{text:'پیام تست'}}});const aud=await req(`/api/iran/crm/campaigns/${camp.id}/audience`,{token:crm,method:'POST',body:{}});assert(aud.count===1,'مخاطب کمپین صحیح نیست',aud);await req(`/api/iran/crm/campaigns/${camp.id}/events`,{token:crm,method:'POST',body:{partyId:conv.partyId,eventType:'SENT'}});await req(`/api/iran/crm/campaigns/${camp.id}/events`,{token:crm,method:'POST',body:{partyId:conv.partyId,eventType:'CONVERTED',sourceType:'SALES_INVOICE',sourceId:inv.id,valueAmount:110000}});const an=await req(`/api/iran/crm/campaigns/${camp.id}/analytics`,{token:crm});assert(an.converted===1&&Number(an.conversionValue)===110000,'Attribution کمپین نادرست',an);log('CAMPAIGN_ATTRIBUTION_OK');

 // NPS.
 const survey=await req('/api/iran/crm/surveys',{token:crm,method:'POST',body:{surveyType:'NPS',title:'NPS تست'}});await req(`/api/iran/crm/surveys/${survey.id}/respond`,{token:crm,method:'POST',body:{partyId:conv.partyId,score:10,response:{comment:'عالی'}}});const sr=await req(`/api/iran/crm/surveys/${survey.id}/results`,{token:crm});assert(sr.nps===100,'NPS صحیح نیست',sr);log('NPS_OK');

 // Return/clawback after all assertions.
 const rev=await req(`/api/iran/loyalty/reverse-sale/${inv.id}`,{token:admin,method:'POST',body:{}});assert(rev.reversed>=1,'برگشت وفاداری انجام نشد',rev);log('LOYALTY_REVERSAL_OK',rev);
 const dash=await req('/api/iran/crm/dashboard',{token:crm});assert(dash.open_leads>=0&&dash.open_tickets>=0,'داشبورد CRM ناقص است',dash);log('CRM_DASHBOARD_OK',dash);
 log('PASS');
}
main().catch(e=>{console.error(`[PHASE14][FAIL] ${e.message}`);if(e.data)console.error(JSON.stringify(e.data,null,2));process.exit(1)});
