const base=process.env.TARAZPAD_URL||'http://127.0.0.1:8080';
const email=process.env.TARAZPAD_ADMIN_EMAIL, password=process.env.TARAZPAD_ADMIN_PASSWORD;
const check=(v,m)=>{if(!v)throw new Error(m)};
async function call(path,{method='GET',body,token}={}){const r=await fetch(base+path,{method,headers:{'content-type':'application/json',...(token?{authorization:`Bearer ${token}`}:{})},body:body===undefined?undefined:JSON.stringify(body)});const t=await r.text();let data;try{data=JSON.parse(t)}catch{data=t}if(!r.ok)throw new Error(`${method} ${path} -> ${r.status} ${typeof data==='string'?data:JSON.stringify(data)}`);return data}
console.log('[1] login');
const auth=await call('/api/auth/login',{method:'POST',body:{email,password}}),token=auth.token;check(token,'token missing');
console.log('[2] create product and product group');
const product=await call('/api/products',{method:'POST',token,body:{sku:`P18-${Date.now()}`,name:'کالای تست تصویری ترازپاد',unit:'کیلوگرم',barcode:String(Date.now()),salePrice:12500000}});check(product.id,'product id missing');
const pg=await call('/api/iran/master/product-groups',{method:'POST',token,body:{code:`FG-${Date.now()}`,title:'محصولات منجمد'}});check(pg.id,'product group id missing');
await call(`/api/iran/master/products/${product.id}/classification`,{method:'PUT',token,body:{groupIds:[pg.id],primaryGroupId:pg.id,imageUrl:'https://example.com/tarazpad-product.jpg',caption:'تصویر اصلی',makePrimary:true}});
const pp=await call(`/api/iran/master/products/${product.id}/profile`,{token});check(pp.groups.length===1,'product group relation missing');check(pp.media.length===1&&pp.media[0].is_primary,'primary product image missing');
console.log('[3] create party and full details');
const party=await call('/api/parties',{method:'POST',token,body:{name:'مشتری تست جزئیات ترازپاد',partyType:'LEGAL',nationalId:'14001234567',mobile:'09121234567',roles:['CUSTOMER']}});check(party.id,'party id missing');
const cg=await call('/api/iran/master/party-groups',{method:'POST',token,body:{code:`CG-${Date.now()}`,title:'مشتریان عمده'}});check(cg.id,'party group id missing');
await call(`/api/iran/master/parties/${party.id}/details`,{method:'PUT',token,body:{groupIds:[cg.id],contacts:[{type:'MOBILE',title:'مدیر خرید',value:'09121234567',isPrimary:true},{type:'PHONE',title:'دفتر',value:'02188776655'}],addresses:[{type:'MAIN',title:'دفتر مرکزی',province:'تهران',city:'تهران',postalCode:'1234567890',address:'تهران، خیابان نمونه',isPrimary:true},{type:'SHIPPING',title:'انبار تحویل',province:'البرز',city:'کرج',postalCode:'9876543210',address:'کرج، شهرک صنعتی'}],banks:[{bankName:'ملت',branchName:'مرکزی',branchCode:'101',accountType:'جاری',accountNo:'123456789',cardNo:'6104330000000000',iban:'IR120170000000123456789001',accountHolder:'مشتری تست',isPrimary:true}]}});
const pprof=await call(`/api/iran/master/parties/${party.id}/profile`,{token});check(pprof.groups.length===1,'party group missing');check(pprof.contacts.length===2,'multiple contacts missing');check(pprof.addresses.length===2,'multiple addresses missing');check(pprof.banks.length===1&&pprof.banks[0].is_primary,'party bank missing');
console.log('[4] create and read image-aware price list');
const pl=await call('/api/iran/commercial/price-lists',{method:'POST',token,body:{title:'لیست قیمت تست تصویری',validFrom:'2026-08-20',validTo:'2026-09-20',items:[{productId:product.id,unitPrice:13000000,minQty:1,maxDiscountPct:5}]}});check(pl.id&&pl.code,'price list create failed');
await call(`/api/iran/commercial/price-lists/${pl.id}/activate`,{method:'POST',token,body:{}});
const pld=await call(`/api/iran/commercial/price-lists/${pl.id}`,{token});check(pld.items.length===1,'price list item missing');check(pld.items[0].image_url,'price list product image missing');
console.log('[5] create sales invoice and print model');
const inv=await call('/api/sales/invoices',{method:'POST',token,body:{customerPartyId:party.id,invoiceDate:'2026-08-20',lines:[{productId:product.id,qty:2,unitPrice:13000000,discount:500000,tax:0}]}});check(inv.id,'sales invoice missing');
const print=await call(`/api/iran/sales-invoices/${inv.id}/print-model`,{token});check(print.header.customer_name.includes('مشتری تست'),'invoice print customer missing');check(print.lines.length===1&&Number(print.lines[0].qty)===2,'invoice print lines missing');check(print.addresses.length>=2,'invoice shipping addresses missing');
console.log('[6] create waybill and print model');
const wb=await call('/api/iran/logistics/waybills',{method:'POST',token,body:{salesInvoiceId:inv.id,issueDate:'2026-08-20',carrierName:'حمل ترازپاد',trackingNo:`TRK-${Date.now()}`,origin:'تهران',destination:'کرج',packageCount:4,grossWeight:55.5,netWeight:50,freightAmount:1200000,insuranceAmount:100000,receiverName:'مسئول انبار',receiverPhone:'09120000000',description:'تحویل سالم'}});check(wb.id&&wb.waybillNo,'waybill create failed');
const wbp=await call(`/api/iran/logistics/waybills/${wb.id}/print-model`,{token});check(wbp.waybill.receiver_party.includes('مشتری تست'),'waybill receiver missing');check(Number(wbp.waybill.gross_weight)===55.5,'waybill weight missing');check(wbp.lines.length===1,'waybill invoice lines missing');
console.log('[7] commercial profitability drilldown');
const prof=await call('/api/iran/commercial/product-profitability?from=2026-08-01&to=2026-08-31',{token});check(Array.isArray(prof.rows),'profitability rows missing');const row=prof.rows.find(x=>Number(x.product_id)===Number(product.id));check(row,'product profitability row missing');check(Number(row.sale_qty)===2,'profitability sale quantity mismatch');
const detail=await call(`/api/iran/commercial/product-profitability/${product.id}/details?from=2026-08-01&to=2026-08-31`,{token});check(detail.sales.length===1,'profitability sales drill-down missing');
console.log('[8] print profile');
const pr=await call('/api/iran/system/print-profiles',{method:'POST',token,body:{documentType:'WAYBILL',code:`A4-WB-${Date.now()}`,title:'بارنامه A4 استاندارد',paperSize:'A4',orientation:'PORTRAIT',isDefault:true,template:{showBarcode:true,showSignature:true}}});check(pr.id,'print profile create failed');
const profiles=await call('/api/iran/system/print-profiles',{token});check(profiles.some(x=>Number(x.id)===Number(pr.id)&&x.is_default),'print profile not persisted');
console.log('PHASE18_E2E_PASS');
