const base=process.env.TARAZPAD_URL||'http://127.0.0.1:8080';
const email=process.env.TARAZPAD_ADMIN_EMAIL||'phase13@tarazpad.test';
const password=process.env.TARAZPAD_ADMIN_PASSWORD||'Strong_Phase13_2026!';
const log=(s,d='')=>console.log(`[PHASE13] ${s}${d?` :: ${typeof d==='string'?d:JSON.stringify(d)}`:''}`);
const assert=(v,m,d)=>{if(!v){const e=new Error(m);e.data=d;throw e}};
async function req(path,{token,method='GET',body}={}){const r=await fetch(base+path,{method,headers:{...(token?{authorization:`Bearer ${token}`}:{}) ,...(body!==undefined?{'content-type':'application/json'}:{})},body:body===undefined?undefined:JSON.stringify(body)});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data=text}if(!r.ok){const e=new Error(`${method} ${path} -> ${r.status} ${typeof data==='string'?data:JSON.stringify(data)}`);e.data=data;throw e}return data}
async function main(){
 const auth=await req('/api/auth/login',{method:'POST',body:{email,password}}),token=auth.token;assert(token,'توکن مدیریت دریافت نشد',auth);log('LOGIN_OK');const stamp=Date.now().toString().slice(-7);
 const accounts=await req('/api/iran/accounts',{token});const accountByCode=c=>accounts.find(x=>x.code===c);assert(accountByCode('110100')&&accountByCode('210100'),'حساب‌های پایه پیدا نشد');
 const bank=await req('/api/treasury/bank-accounts',{token,method:'POST',body:{code:`B13-${stamp}`,bankName:'بانک فاز ۱.۳',accountTitle:'حساب کنترل مالی',accountNo:`13${stamp}`,openingBalance:0}});
 const wh=await req('/api/inventory/warehouses',{token,method:'POST',body:{code:`W13-${stamp}`,name:'انبار فاز ۱.۳',warehouseType:'GENERAL'}});
 const customer=await req('/api/iran/parties',{token,method:'POST',body:{name:`مشتری فاز۱۳ ${stamp}`,partyType:'LEGAL',code:`C13-${stamp}`,nationalId:`13${stamp}111`,economicCode:`413${stamp}11`,postalCode:`14${stamp}`,roles:['CUSTOMER']}});
 const supplier=await req('/api/iran/parties',{token,method:'POST',body:{name:`تأمین‌کننده فاز۱۳ ${stamp}`,partyType:'LEGAL',code:`S13-${stamp}`,nationalId:`14${stamp}222`,economicCode:`423${stamp}22`,postalCode:`15${stamp}`,roles:['SUPPLIER']}});
 const product=await req('/api/iran/products',{token,method:'POST',body:{sku:`P13-${stamp}`,name:'کالای فاز مالی مدیریتی',unit:'عدد',purchasePrice:50000,salePrice:90000,vatStatus:'STANDARD',defaultVatRate:10,productType:'GOODS'}});log('MASTERS_OK');

 // Purchase and stock base.
 const po=await req('/api/procurement/orders',{token,method:'POST',body:{supplierPartyId:supplier.id,warehouseId:wh.id,poDate:'2026-08-01',lines:[{productId:product.id,qty:20,unitPrice:50000,discount:0,tax:0}]}});const sub=await req(`/api/procurement/orders/${po.id}/submit`,{token,method:'POST',body:{}});await req(`/api/workflow/approvals/${sub.approvalRequestId}/decision`,{token,method:'POST',body:{action:'APPROVE'}});const ctx=await req(`/api/iran/procurement/context?purchaseOrderId=${po.id}`,{token});const gr=await req('/api/procurement/goods-receipts',{token,method:'POST',body:{purchaseOrderId:po.id,warehouseId:wh.id,receiptDate:'2026-08-02',lines:[{purchaseOrderLineId:ctx.poLines[0].id,receivedQty:20,acceptedQty:20,unitCost:50000}]}});await req(`/api/iran/goods-receipts/${gr.id}/post`,{token,method:'POST',body:{}});const pi=await req('/api/iran/purchase-invoices/auto',{token,method:'POST',body:{supplierPartyId:supplier.id,invoiceDate:'2026-08-03',invoiceClassification:'NON_OFFICIAL',purchaseKind:'GOODS',purchaseOrderId:po.id,goodsReceiptId:gr.id,lines:[{productId:product.id,qty:20,unitPrice:50000,vatStatus:'STANDARD',vatRate:10}]}});await req(`/api/iran/purchase-invoices/${pi.id}/match`,{token,method:'POST',body:{}});await req(`/api/iran/purchase-invoices/${pi.id}/post`,{token,method:'POST',body:{}});log('PURCHASE_BASE_OK');

 // Sales + AR aging + credit note and stock/COGS reversal.
 const sale=await req('/api/iran/sales-invoices',{token,method:'POST',body:{customerPartyId:customer.id,invoiceDate:'2026-08-04',dueDate:'2026-08-10',invoiceClassification:'NON_OFFICIAL',settlementType:'CREDIT',lines:[{productId:product.id,qty:5,unitPrice:90000}]}});await req(`/api/iran/sales-invoices/${sale.id}/post`,{token,method:'POST',body:{}});const aging=await req('/api/iran/finance/aging?type=AR&asOf=2026-09-15',{token});assert(aging.total===495000&&aging.rows.some(x=>x.id===sale.id&&x.bucket!=='جاری'),'تجزیه سنی AR صحیح نیست',aging);log('AGING_OK',aging.buckets);
 const saleLines=await req(`/api/sales/invoices/${sale.id}/lines`,{token}).catch(()=>[]);const sil=saleLines[0];const cn=await req('/api/iran/finance/ar-credit-notes',{token,method:'POST',body:{customerPartyId:customer.id,noteDate:'2026-08-06',salesInvoiceId:sale.id,reasonCode:'RETURN',lines:[{salesInvoiceLineId:sil?.id||null,productId:product.id,quantity:1,unitAmount:90000,netAmount:90000,taxAmount:9000,inventoryReturnRequired:true}]}});await req(`/api/iran/finance/ar-credit-notes/${cn.id}/approve`,{token,method:'POST',body:{}});const cnp=await req(`/api/iran/finance/ar-credit-notes/${cn.id}/post`,{token,method:'POST',body:{warehouseId:wh.id}});assert(cnp.ok&&cnp.appliedToInvoice===99000,'بستانکارنامه فروش صحیح اعمال نشد',cnp);log('AR_CREDIT_NOTE_OK',cnp);

 // AP debit note / purchase return.
 const pil=ctx.poLines[0];const dn=await req('/api/iran/finance/ap-debit-notes',{token,method:'POST',body:{supplierPartyId:supplier.id,noteDate:'2026-08-07',purchaseInvoiceId:pi.id,reasonCode:'PURCHASE_RETURN',lines:[{purchaseInvoiceLineId:null,productId:product.id,quantity:1,unitAmount:50000,netAmount:50000,taxAmount:5000,inventoryReturnRequired:true}]}});await req(`/api/iran/finance/ap-debit-notes/${dn.id}/approve`,{token,method:'POST',body:{}});const dnp=await req(`/api/iran/finance/ap-debit-notes/${dn.id}/post`,{token,method:'POST',body:{warehouseId:wh.id}});assert(dnp.ok&&dnp.appliedToInvoice===55000,'بدهکارنامه خرید صحیح اعمال نشد',dnp);log('AP_DEBIT_NOTE_OK',dnp);

 // Budget with real control modes.
 const expAccount=accountByCode('610900')||accountByCode('610300')||accounts.find(x=>x.account_type==='EXPENSE');assert(expAccount,'حساب هزینه برای بودجه پیدا نشد');const budget=await req('/api/iran/finance/budgets',{token,method:'POST',body:{title:`بودجه فاز۱۳ ${stamp}`,fiscalYearLabel:'۱۴۰۵',startDate:'2026-03-21',endDate:'2027-03-20',versionNo:1,lines:[{accountId:expAccount.id,periodNo:5,budgetAmount:1000000,warningPercent:80,controlMode:'BLOCK'}]}});await req(`/api/iran/finance/budgets/${budget.id}/activate`,{token,method:'POST',body:{}});const budgetAllow=await req('/api/iran/finance/budget-check',{token,method:'POST',body:{accountId:expAccount.id,periodNo:5,sourceType:'TEST',sourceId:1,commitmentDate:'2026-08-01',amount:500000,reserve:true}});assert(budgetAllow.decision==='ALLOW'||budgetAllow.decision==='WARN','بودجه ۵۰٪ نباید مسدود شود',budgetAllow);const budgetBlock=await req('/api/iran/finance/budget-check',{token,method:'POST',body:{accountId:expAccount.id,periodNo:5,sourceType:'TEST',sourceId:2,commitmentDate:'2026-08-01',amount:600000,reserve:false}});assert(budgetBlock.decision==='BLOCK','کنترل سقف بودجه عمل نکرد',budgetBlock);log('BUDGET_CONTROL_OK',{allow:budgetAllow.decision,block:budgetBlock.decision});

 // Fixed asset + depreciation.
 const cls=await req('/api/iran/finance/asset-classes',{token,method:'POST',body:{code:`EQ-${stamp}`,title:'تجهیزات اداری تست',usefulLifeMonths:60,depreciationMethod:'STRAIGHT_LINE'}});const asset=await req('/api/iran/finance/assets',{token,method:'POST',body:{assetClassId:cls.id,title:'رایانه تست دارایی ثابت',acquisitionDate:'2026-04-01',capitalizationDate:'2026-04-01',originalCost:60000000,salvageValue:0,usefulLifeMonths:60}});const cap=await req(`/api/iran/finance/assets/${asset.id}/capitalize`,{token,method:'POST',body:{}});assert(cap.ok&&cap.debit===cap.credit,'فعال‌سازی دارایی متوازن نیست',cap);const dep=await req('/api/iran/finance/depreciation-runs',{token,method:'POST',body:{periodStart:'2026-08-01',periodEnd:'2026-08-31'}});const depCalc=await req(`/api/iran/finance/depreciation-runs/${dep.id}/calculate`,{token,method:'POST',body:{}});assert(depCalc.totalDepreciation>0,'استهلاک محاسبه نشد',depCalc);const depPost=await req(`/api/iran/finance/depreciation-runs/${dep.id}/post`,{token,method:'POST',body:{}});assert(depPost.ok&&Math.abs(depPost.debit-depPost.credit)<1,'سند استهلاک متوازن نیست',depPost);log('FIXED_ASSET_OK',depPost.totalDepreciation);

 // Landed cost allocation to receipt.
 const grctx=await req(`/api/iran/procurement/context?goodsReceiptId=${gr.id}`,{token});const grLine=grctx.grLines[0];assert(grLine,'ردیف رسید برای هزینه خرید پیدا نشد',grctx);const lc=await req('/api/iran/finance/landed-costs',{token,method:'POST',body:{title:`حمل خرید ${stamp}`,costDate:'2026-08-05',allocationBasis:'QUANTITY',sources:[{costType:'FREIGHT',amount:200000}],targets:[{goodsReceiptLineId:grLine.id}]}});const lcc=await req(`/api/iran/finance/landed-costs/${lc.id}/calculate`,{token,method:'POST',body:{}});assert(lcc.allocated===200000,'سرشکن هزینه خرید نادرست',lcc);const lcp=await req(`/api/iran/finance/landed-costs/${lc.id}/post`,{token,method:'POST',body:{}});assert(lcp.ok&&lcp.totalAllocated===200000,'ثبت هزینه خرید نادرست',lcp);log('LANDED_COST_OK',lcp);

 // Project + contract + profitability.
 const project=await req('/api/iran/finance/projects',{token,method:'POST',body:{projectCode:`PJ-${stamp}`,title:'پروژه تست مدیریتی',customerPartyId:customer.id,startDate:'2026-08-01',budgetAmount:5000000,status:'ACTIVE'}});const contract=await req(`/api/iran/finance/projects/${project.id}/contracts`,{token,method:'POST',body:{contractNo:`PC-${stamp}`,contractType:'CUSTOMER',counterpartyPartyId:customer.id,startDate:'2026-08-01',contractAmount:4000000,advancePercent:20,retentionPercent:10,milestones:[{milestoneNo:'M1',title:'مرحله اول',dueDate:'2026-09-01',amount:2000000},{milestoneNo:'M2',title:'مرحله دوم',dueDate:'2026-10-01',amount:2000000}]}});assert(contract.id,'قرارداد پروژه ثبت نشد',contract);for(const x of [{transactionType:'REVENUE',amount:3000000},{transactionType:'DIRECT_COST',amount:1200000},{transactionType:'INDIRECT_COST',amount:300000},{transactionType:'RECEIPT',amount:1000000}])await req(`/api/iran/finance/projects/${project.id}/transactions`,{token,method:'POST',body:{transactionDate:'2026-08-20',...x}});const prof=await req(`/api/iran/finance/projects/${project.id}/profitability`,{token});assert(prof.revenue===3000000&&prof.cost===1500000&&prof.profit===1500000,'سودآوری پروژه نادرست',prof);log('PROJECT_PROFIT_OK',prof);

 // Subledger reconciliation and global balance.
 const recon=await req('/api/iran/finance/reconciliation/run',{token,method:'POST',body:{snapshotDate:'2026-09-30'}});assert(recon.some(x=>x.type==='AR')&&recon.some(x=>x.type==='AP')&&recon.some(x=>x.type==='INVENTORY'),'مرکز تطبیق ناقص است',recon);log('RECONCILIATION_SNAPSHOT_OK',recon);
 const tb=await req('/api/finance/trial-balance',{token});const dr=tb.reduce((s,x)=>s+Number(x.debit||0),0),cr=tb.reduce((s,x)=>s+Number(x.credit||0),0);assert(Math.abs(dr-cr)<1,'تراز کل بعد از فاز ۱.۳ متوازن نیست',{dr,cr});log('TRIAL_BALANCE_OK',{dr,cr});
 log('PASS');
}
main().catch(e=>{console.error(`[PHASE13][FAIL] ${e.message}`);if(e.data)console.error(JSON.stringify(e.data,null,2));process.exit(1)});
