<Project>
  <PropertyGroup>
    <BaseOutputPath>$(MSBuildThisFileDirectory)..\..\.artifacts\desktop\bin\</BaseOutputPath>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)..\..\.artifacts\desktop\obj\</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>$(BaseIntermediateOutputPath)$(MSBuildProjectName)\</MSBuildProjectExtensionsPath>
  </PropertyGroup>
</Project>
