import mysql from 'mysql2/promise';
import assert from 'node:assert/strict';
const base=process.env.TEST_BASE_URL||'http://127.0.0.1:8080';
const db=await mysql.createConnection({host:process.env.MYSQL_HOST||'127.0.0.1',port:Number(process.env.MYSQL_PORT||3306),user:process.env.MYSQL_USER||'tarazpad',password:process.env.MYSQL_PASSWORD||'',database:process.env.MYSQL_DATABASE||'tarazpad',decimalNumbers:true});
async function api(path,{token,method='GET',body,allow=[]}={}){const r=await fetch(base+path,{method,headers:{'content-type':'application/json',...(token?{authorization:`Bearer ${token}`}:{})},body:body===undefined?undefined:JSON.stringify(body)}),text=await r.text();let data;try{data=JSON.parse(text)}catch{data=text}if(!r.ok&&!allow.includes(r.status))throw new Error(`${method} ${path} -> ${r.status}: ${typeof data==='string'?data:JSON.stringify(data)}`);return{status:r.status,data}}
async function login(email,password){return(await api('/api/auth/login',{method:'POST',body:{email,password}})).data.token}
async function createUser(admin,name,email,password,roles){return(await api('/api/iran/admin/users',{token:admin,method:'POST',body:{fullName:name,email,password,roleCodes:roles}})).data}
const pFmt=new Intl.DateTimeFormat('en-US-u-ca-persian',{year:'numeric',month:'numeric',day:'numeric',timeZone:'UTC'}),pp=d=>Object.fromEntries(pFmt.formatToParts(new Date(d)).filter(x=>x.type!=='literal').map(x=>[x.type,Number(x.value)]));
const iso=d=>String(d).slice(0,10),step=s=>console.log(`\n[PHASE17] ${s}`);
try{
 step('startup and segregation-of-duty users');
 assert.equal((await api('/api/health')).data.ok,true);
 const admin=await login(process.env.TARAZPAD_ADMIN_EMAIL,'Strong_P17_Admin_2026!');
 await createUser(admin,'حسابدار سالانه','p17-accountant@tarazpad.test','Strong_P17_Accountant!',['ACCOUNTANT']);
 await createUser(admin,'بازبین مالی سالانه','p17-fin1@tarazpad.test','Strong_P17_Fin1_2026!',['FINANCE_MANAGER']);
 await createUser(admin,'تأییدکننده مالی سالانه','p17-fin2@tarazpad.test','Strong_P17_Fin2_2026!',['FINANCE_MANAGER']);
 await createUser(admin,'مدیر منابع انسانی تست','p17-hr@tarazpad.test','Strong_P17_HR_2026!',['HR_MANAGER']);
 const AT=await login('p17-accountant@tarazpad.test','Strong_P17_Accountant!'),F1=await login('p17-fin1@tarazpad.test','Strong_P17_Fin1_2026!'),F2=await login('p17-fin2@tarazpad.test','Strong_P17_Fin2_2026!'),HR=await login('p17-hr@tarazpad.test','Strong_P17_HR_2026!');
 const adminId=Number((await api('/api/me',{token:admin})).data.user.sub);

 step('Jalali fiscal years 1405 and 1406');
 const fy05=(await api('/api/iran/finance/fiscal-years',{token:F1,method:'POST',body:{yearNo:1405,title:'سال مالی ۱۴۰۵'}})).data,fy06=(await api('/api/iran/finance/fiscal-years',{token:F1,method:'POST',body:{yearNo:1406,title:'سال مالی ۱۴۰۶'}})).data;
 const years=await api('/api/iran/finance/fiscal-years',{token:AT}),y05=years.data.find(x=>Number(x.id)===Number(fy05.id)),y06=years.data.find(x=>Number(x.id)===Number(fy06.id)),p5=y05.periods.find(x=>Number(x.period_no)===5);assert.ok(p5&&y06.periods.length===12);const ps=pp(p5.start_date);assert.equal(ps.year,1405);assert.equal(ps.month,5);assert.equal(ps.day,1);

 step('seed retained earnings and balanced operational GL before hard close');
 let [[ret]]=await db.execute(`SELECT id FROM accounts WHERE company_id=1 AND code='390100'`);if(!ret){const [r]=await db.execute(`INSERT INTO accounts(company_id,parent_id,code,title,level_no,nature,account_type,allow_posting,is_active,statement_section,cash_flow_activity) VALUES (1,NULL,'390100','سود و زیان انباشته تست',1,'CREDIT','EQUITY',1,1,'EQUITY','FINANCING')`);ret={id:r.insertId}}
 const [[ar]]=await db.execute(`SELECT id FROM accounts WHERE company_id=1 AND code='110100'`),[[inv]]=await db.execute(`SELECT id FROM accounts WHERE company_id=1 AND code='130100'`),[[sales]]=await db.execute(`SELECT id FROM accounts WHERE company_id=1 AND code='410100'`),[[cogs]]=await db.execute(`SELECT id FROM accounts WHERE company_id=1 AND code='510100'`);assert.ok(ar&&inv&&sales&&cogs&&ret);
 const d=iso(p5.start_date);const [j1]=await db.execute(`INSERT INTO journal_entries(company_id,entry_no,entry_date,posting_date,status,source_type,description,created_by,posted_at) VALUES (1,'P17-SALE',?,?, 'POSTED','P17_OPERATION','فروش سالانه کنترل',?,NOW())`,[d,d,adminId]);await db.execute(`INSERT INTO journal_lines(journal_entry_id,account_id,debit,credit,description) VALUES (?,?,1000000,0,'مطالبات'),(?,?,0,1000000,'فروش')`,[j1.insertId,ar.id,j1.insertId,sales.id]);const [j2]=await db.execute(`INSERT INTO journal_entries(company_id,entry_no,entry_date,posting_date,status,source_type,description,created_by,posted_at) VALUES (1,'P17-COGS',?,?, 'POSTED','P17_OPERATION','بهای فروش سالانه کنترل',?,NOW())`,[d,d,adminId]);await db.execute(`INSERT INTO journal_lines(journal_entry_id,account_id,debit,credit,description) VALUES (?,?,400000,0,'بهای تمام‌شده'),(?,?,0,400000,'موجودی')`,[j2.insertId,cogs.id,j2.insertId,inv.id]);

 step('payroll source for Iranian salary-tax compliance');
 const emp=(await api('/api/iran/hr/employees',{token:HR,method:'POST',body:{personnelNo:'P17-EMP-001',name:'کارمند تکلیف قانونی',nationalNo:'0088776655',insuranceNo:'P17-INS-1',hireDate:iso(y05.start_date),maritalStatus:'MARRIED',childrenCount:1}})).data.partyId;
 await api('/api/iran/hr/contracts',{token:HR,method:'POST',body:{employeePartyId:emp,contractNo:'P17-CTR-1',contractType:'FIXED_TERM',startDate:iso(y05.start_date),endDate:iso(y05.end_date),baseSalaryMonthly:650000000,insuranceIncluded:true,taxIncluded:true,status:'ACTIVE'}});
 await api('/api/iran/payroll/attendance',{token:HR,method:'POST',body:{employeePartyId:emp,yearNo:1405,monthNo:5,calendarDays:31,workDays:31,overtimeHours:5}});
 const batch=(await api('/api/iran/payroll/batches',{token:HR,method:'POST',body:{yearNo:1405,monthNo:5,title:'حقوق تکلیف ۱۴۰۵/۰۵'}})).data.id;const calcPay=(await api(`/api/iran/payroll/batches/${batch}/calculate`,{token:HR,method:'POST',body:{}})).data;assert.ok(calcPay.employeeCount>=1&&calcPay.totalNet>0);

 step('versioned compliance rule, calculation and source-hash tamper protection');
 const types=(await api('/api/iran/compliance/obligation-types',{token:AT})).data,salaryType=types.find(x=>x.code==='IR_SALARY_TAX');assert.ok(salaryType);
 const rule=(await api('/api/iran/compliance/rules',{token:F1,method:'POST',body:{obligationTypeId:salaryType.id,versionNo:1,effectiveFrom:iso(y05.start_date),dueRule:{daysAfterPeriodEnd:15},legalReference:'مرجع آزمایشی نسخه‌دار - بدون Hard Code قانونی'}})).data;
 const cp=(await api('/api/iran/compliance/periods',{token:AT,method:'POST',body:{obligationTypeId:salaryType.id,ruleVersionId:rule.id,periodKey:'1405-05',periodStart:iso(p5.start_date),periodEnd:iso(p5.end_date)}})).data;const expectedDue=new Date(`${iso(p5.end_date)}T00:00:00Z`);expectedDue.setUTCDate(expectedDue.getUTCDate()+15);assert.equal(cp.dueDate,expectedDue.toISOString().slice(0,10));
 const c1=(await api(`/api/iran/compliance/periods/${cp.id}/calculate`,{token:AT,method:'POST',body:{}})).data;assert.equal(c1.status,'CALCULATED');assert.ok(c1.payableAmount>0);assert.match(c1.sourceHash,/^[a-f0-9]{64}$/);
 const [[slip]]=await db.execute(`SELECT ps.id,ps.salary_tax FROM payroll_slips ps JOIN payroll_batches pb ON pb.id=ps.payroll_batch_id WHERE pb.id=? LIMIT 1`,[batch]);await db.execute(`UPDATE payroll_slips SET salary_tax=salary_tax+1000 WHERE id=?`,[slip.id]);const blockedReview=await api(`/api/iran/compliance/periods/${cp.id}/review`,{token:F1,method:'POST',body:{},allow:[409]});assert.equal(blockedReview.status,409);assert.match(JSON.stringify(blockedReview.data),/محاسبه مجدد/);
 const c2=(await api(`/api/iran/compliance/periods/${cp.id}/calculate`,{token:AT,method:'POST',body:{}})).data;assert.equal(Number(c2.payableAmount),Number(c1.payableAmount)+1000);await api(`/api/iran/compliance/periods/${cp.id}/review`,{token:F1,method:'POST',body:{}});await api(`/api/iran/compliance/periods/${cp.id}/approve`,{token:F2,method:'POST',body:{}});await api(`/api/iran/compliance/periods/${cp.id}/file`,{token:F2,method:'POST',body:{filingReference:'P17-FILE-REF-001'}});await api(`/api/iran/compliance/periods/${cp.id}/accept`,{token:F2,method:'POST',body:{accepted:true,note:'پذیرش آزمایشی'}});const paid=(await api(`/api/iran/compliance/periods/${cp.id}/pay`,{token:F2,method:'POST',body:{paymentReference:'P17-PAY-REF-001'}})).data;assert.equal(paid.status,'PAID');

 step('standard financial templates and editable clone before close');
 const templates=(await api('/api/iran/finance/statement-templates',{token:AT})).data,stdPl=templates.find(x=>x.code==='STD_PL'),stdBs=templates.find(x=>x.code==='STD_BS');assert.ok(stdPl&&stdBs);
 const prePl=(await api(`/api/iran/finance/statement-templates/${stdPl.id}/render?periodStart=${iso(y05.start_date)}&asOf=${iso(y05.end_date)}`,{token:AT})).data;const preNet=prePl.lines.find(x=>x.lineCode==='NET_PROFIT');assert.equal(Number(preNet.value),600000);
 const clone=(await api(`/api/iran/finance/statement-templates/${stdPl.id}/clone`,{token:F1,method:'POST',body:{code:'P17_PL_CUSTOM',title:'سود و زیان مدیریتی تست'}})).data;await api(`/api/iran/finance/statement-templates/${clone.id}/lines`,{token:F1,method:'POST',body:{lineCode:'GROSS_MARGIN_PCT',title:'حاشیه سود ناخالص درصد',lineType:'FORMULA',normalSign:'AUTO',formulaText:'GROSS_PROFIT/OPERATING_REVENUE*100',sortOrder:105,displayLevel:1,isBold:true}});const custom=(await api(`/api/iran/finance/statement-templates/${clone.id}/render?periodStart=${iso(y05.start_date)}&asOf=${iso(y05.end_date)}`,{token:AT})).data;assert.equal(Math.round(Number(custom.lines.find(x=>x.lineCode==='GROSS_MARGIN_PCT').value)),60);

 step('hard-close all 1405 periods for controlled year-end');
 await db.execute(`UPDATE fiscal_periods SET status='HARD_CLOSED',closed_by=?,closed_at=NOW() WHERE fiscal_year_id=?`,[adminId,fy05.id]);
 await api('/api/iran/finance/year-end-settings',{token:F1,method:'PUT',body:{retainedEarningsAccountId:ret.id,requireAllPeriodsHardClosed:true,autoCreateOpeningEntry:true}});
 const yec=(await api('/api/iran/finance/year-end-runs/calculate',{token:AT,method:'POST',body:{fiscalYearId:fy05.id,nextFiscalYearId:fy06.id}})).data;assert.equal(Number(yec.netProfitLoss),600000);assert.match(yec.sourceHash,/^[a-f0-9]{64}$/);await api(`/api/iran/finance/year-end-runs/${yec.id}/review`,{token:F1,method:'POST',body:{}});await api(`/api/iran/finance/year-end-runs/${yec.id}/approve`,{token:F2,method:'POST',body:{}});const close=(await api(`/api/iran/finance/year-end-runs/${yec.id}/post-closing`,{token:F2,method:'POST',body:{}})).data;assert.equal(close.status,'POSTED');assert.equal(Number(close.debit),Number(close.credit));
 const [[nominalZero]]=await db.execute(`SELECT ABS(COALESCE(SUM(CASE WHEN a.account_type='REVENUE' THEN jl.credit-jl.debit ELSE jl.debit-jl.credit END),0)) net FROM journal_lines jl JOIN journal_entries je ON je.id=jl.journal_entry_id JOIN accounts a ON a.id=jl.account_id WHERE je.company_id=1 AND a.account_type IN ('REVENUE','EXPENSE') AND COALESCE(je.posting_date,je.entry_date) BETWEEN ? AND ?`,[iso(y05.start_date),iso(y05.end_date)]);assert.ok(Number(nominalZero.net)<1);
 const [[retBal]]=await db.execute(`SELECT COALESCE(SUM(jl.credit-jl.debit),0) bal FROM journal_lines jl JOIN journal_entries je ON je.id=jl.journal_entry_id WHERE je.company_id=1 AND jl.account_id=? AND COALESCE(je.posting_date,je.entry_date)<=?`,[ret.id,iso(y05.end_date)]);assert.equal(Number(retBal.bal),600000);

 step('historical P&L survives closing entry and balance sheet transfers earnings');
 const hist=(await api(`/api/iran/finance/profit-loss?dateFrom=${iso(y05.start_date)}&dateTo=${iso(y05.end_date)}`,{token:AT})).data;assert.equal(Number(hist.current.netProfit),600000);assert.ok(hist.excludedSystemSources.includes('YEAR_END_CLOSE'));
 const plAfter=(await api(`/api/iran/finance/statement-templates/${stdPl.id}/render?periodStart=${iso(y05.start_date)}&asOf=${iso(y05.end_date)}`,{token:AT})).data;assert.equal(Number(plAfter.lines.find(x=>x.lineCode==='NET_PROFIT').value),600000);
 const bsBeforeMap=(await api(`/api/iran/finance/statement-templates/${stdBs.id}`,{token:AT})).data,equityLine=bsBeforeMap.lines.find(x=>x.line_code==='EQUITY');assert.ok(equityLine);await api(`/api/iran/finance/statement-lines/${equityLine.id}/auto-map`,{token:F1,method:'POST',body:{statementSection:'EQUITY'}});const bsStd=(await api(`/api/iran/finance/statement-templates/${stdBs.id}/render?asOf=${iso(y05.end_date)}`,{token:AT})).data;assert.equal(Number(bsStd.lines.find(x=>x.lineCode==='BALANCE_DIFFERENCE').value),0);const bs=(await api(`/api/iran/finance/balance-sheet?asOf=${iso(y05.end_date)}`,{token:AT})).data;assert.equal(Number(bs.current.currentEarnings),0);assert.equal(Number(bs.current.totalAssets),600000);assert.equal(Number(bs.current.totalEquity),600000);assert.ok(Math.abs(Number(bs.current.balanceDifference))<1);

 step('opening entry and fiscal-scope reporting prevent double count');
 const opening=(await api(`/api/iran/finance/year-end-runs/${yec.id}/post-opening`,{token:F2,method:'POST',body:{}})).data;assert.equal(opening.status,'OPENING_POSTED');assert.equal(Number(opening.debit),Number(opening.credit));const nextStart=iso(y06.start_date);const bsNext=(await api(`/api/iran/finance/balance-sheet?asOf=${nextStart}`,{token:AT})).data;assert.equal(bsNext.current.fiscalScopeFrom,nextStart);assert.equal(bsNext.current.hasOpeningEntry,true);assert.equal(Number(bsNext.current.totalAssets),600000);assert.equal(Number(bsNext.current.totalEquity),600000);assert.ok(Math.abs(Number(bsNext.current.balanceDifference))<1);
 const ledger=(await api(`/api/iran/finance/account-ledger/${ar.id}?dateFrom=${nextStart}&dateTo=${nextStart}`,{token:AT})).data;assert.equal(Number(ledger.openingBalance),0);assert.equal(ledger.rows.length,1);assert.equal(Number(ledger.rows[0].running_balance),1000000);assert.equal(ledger.rows[0].source_type,'YEAR_OPENING');
 const runDetail=(await api(`/api/iran/finance/year-end-runs/${yec.id}`,{token:AT})).data;const retainedLine=runDetail.lines.find(x=>Number(x.account_id)===Number(ret.id));assert.ok(retainedLine);assert.equal(Number(retainedLine.opening_credit),600000);

 step('final invariant: GL remains balanced across closing and opening');
 const [[bal]]=await db.execute(`SELECT COALESCE(SUM(jl.debit-jl.credit),0) diff FROM journal_lines jl JOIN journal_entries je ON je.id=jl.journal_entry_id WHERE je.company_id=1 AND je.status IN ('POSTED','LOCKED')`);assert.ok(Math.abs(Number(bal.diff))<1);
 console.log('\nPHASE17_YEAR_END_COMPLIANCE_PASS');
}finally{await db.end()}
